web/projects/portal/src/app/portal/schedule/schedule-task-editor/actions/action-accordian/action-accordion.component.ts

When overwriting an existing format, the options in the model's saveFormats should be removed along with the deletion of the path.

Fix Bug #70045:

---

web/projects/portal/src/app/vsobjects/format/vs-formats-pane.component.html

merge 13.8 to 14.0.now alpha can not clear value to null since it have default value 100, so the warning for it is useless, so just remove it.

Fix Bug #70027:

---

core/src/main/java/inetsoft/uql/XQuery.java
core/src/main/java/inetsoft/uql/asset/internal/SQLBoundTableAssemblyInfo.java
core/src/main/java/inetsoft/util/dep/AbstractSheetAsset.java
core/src/main/java/inetsoft/util/dep/ViewsheetAsset.java
core/src/main/java/inetsoft/util/dep/WorksheetAsset.java
core/src/main/java/inetsoft/web/portal/controller/database/QueryManagerService.java

the bug is caused by the ws use sql bound query in it, and when run mv, in mv thread, its current organization is host, but the query's organization is other organization, so it will not get right datasource.
for ws and vs, its identify will have its organztion id, but for datasource in xquery, it do not save its organzation, so we should save organization id in xquery when create query and when import to other organzation. Then when mv to execute sql query, it can get its datasource from right organization.
the bug not existed for sso, but for normal config have the same issue, get datasource from current organization is not safe, should save its organization id in XQuery to keep it always right.

fix Bug #69851:

---

core/src/main/java/inetsoft/sree/RepletEngine.java

The change in #69783 caused the current organization of the logged-in user to be fetched, but we might need to query content from other organizations via the web API, so relying on the logged-in user is incorrect. Rework Bug #69783

Fix Bug #70058:

---

web/projects/portal/src/app/composer/dialog/ws/aggregate-dialog.component.ts

the bug is caused by when column have alias, when check the column is trap or not only using equals to find column. So if it have alias, will not find in grayed out fields. so we should compare attribute and its entity when have alias in column

fix Bug #70059:

---

core/src/main/java/inetsoft/web/share/ShareController.java

Do not switch the organization ID in the principal through the `@SwitchOrg` annotation in the aspect when retrieving the share config, as this could lead to an incorrect organization ID in the principal when fetching repository entries. Instead, use the `OrganizationManager.runInOrgScope()` method to ensure that it does not affect other threads.

refix Bug #69783

---

core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java
core/src/main/java/inetsoft/report/internal/RuntimeAssetEngine.java
core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
core/src/main/java/inetsoft/uql/asset/AssetRepository.java
core/src/main/java/inetsoft/uql/asset/sync/AssetDependencyTransformer.java
core/src/main/java/inetsoft/uql/viewsheet/VSBookmark.java
core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java

Prevent bookmarks from getting lost. Make changes to the VSBookmark instance from the storage as it could have changes from other inetsoft server instances or other runtime viewsheets. Add a distributed lock around this area of the code to prevent race conditions. Debounce the code to update last accessed time of a bookmark and do it in a separate thread.

Merge forward Bug #69919 - Prevent bookmarks from getting lost

---

core/src/main/java/inetsoft/web/admin/viewsheet/ViewsheetModel.java

The viewsheet created in the task is public, so the user is null, but it is associated with an organization. Therefore, instead of retrieving the current organization each time the model is accessed, the organization from the runtime viewsheet should be used for isolation.

Fix Bug #70078:

---

core/src/main/java/inetsoft/sree/schedule/TimeCondition.java

fix Bug #70077:
this is an old bug for hourly time, because time can set by differnt time zone, so after change hour to server time zone, it maybe in diffent date.
such as(UTC): 1:30---19:30
change to(UTC+8): 7:30--3:30
then it will find end < start so it will not get right time for task.
In fact, if new hour(hour + hoff) is large than 24 hours, should make day+1, if hours < 0, should make day - 1. Then it can get right time.

fix Bug #70077

---

core/src/main/resources/inetsoft/util/srinter.properties
web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.component.ts
web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-editor.component.html

fix Bug #70110. Disable switching condition type and show a warning message until the task save is completed.

fix Bug #70110. Disable switching condition type and show a warning message until the task save is completed.

---

web/projects/shared/util/guard/can-component-deactivate.service.ts

Because "Enable Security" is set to false, the Security Providers page is directly hidden, which means the CanDeactivate guard is not triggered. The purpose of the CanDeactivate guard is to show a dialog if the form has not been saved. However, when "Enable Security" is false, there's no need to consider whether the form has been saved, so the CanDeactivate guard is not required, and the navigation can proceed directly.

Fix Bug #70093:

---

core/src/main/java/inetsoft/web/admin/security/SSOSettingsService.java
core/src/main/java/inetsoft/web/security/AbstractSecurityFilter.java

When setting the `sso.default.roles` property, there is no need to explicitly set the organization ID, as this property currently only takes effect in non-multi-tenant environments.

fix Bug #70174. 

---

core/src/main/java/inetsoft/web/admin/logviewer/LogSettingService.java

Do not load the Fluentd config when the log provider is not Fluentd to avoid incorrectly saving the default Fluentd config after editing the log config.

fix Bug #70190

---

core/src/main/java/inetsoft/sree/schedule/CloudRunnerServerScheduleClient.java
core/src/main/java/inetsoft/sree/schedule/RestartSchedulerMessage.java
core/src/main/java/inetsoft/sree/schedule/Scheduler.java
core/src/main/java/inetsoft/web/admin/schedule/SchedulerConfigurationController.java
core/src/main/java/inetsoft/web/admin/schedule/SchedulerConfigurationService.java

For the scheduler cloud runner, automatically restart the scheduler server when the schedule configuration is changed to apply the latest config. This is because when configuring the cloud runner, the user does not have a way to restart the scheduler.

fix Bug #70203

---

core/src/main/java/inetsoft/sree/schedule/Scheduler.java
core/src/main/java/inetsoft/sree/schedule/TimeCondition.java

fix Bug #70179:
for schedule task condtion, should using condition time zone to check all conditions and then change time to server time zone. In old logic, all time change to server will cause date not rightly. using local time zone all date will not change to other day, so all logic will works rightly.
fix null point of for time zone

fix Bug #70208:

---

core/src/main/java/inetsoft/sree/schedule/TimeCondition.java

When calculating 12-hour time for Run Once tasks, do not do an extra timezone conversion

Bug #70105  Fix Condition description for Run Once Tasks

---

core/src/main/java/inetsoft/sree/schedule/TimeCondition.java

the bug is caused by end time using server time zone but current time using local time zone, so it will compare wrong, all calculate and compare should using local time zone to do.

fix Bug #70264:

---

core/src/main/java/inetsoft/uql/asset/sync/TaskAssetDependencyTransformer.java

to update the task in scheduler server after TaskAssetDependencyTransformer process the task, should get the schedule task by the org id.

fix Bug #70072

---

core/src/main/java/inetsoft/sree/schedule/jobstore/ClusterJobStore.java

call storeTrigger from storeJobsAndTriggers, do not check the job exist. jobsByKey is a LocalClusterMap, it needs some time to sync local map and distributed map, so frequent map operations can lead to inconsistencies between the local map and the distributed map in LocalClusterMap.

fix Bug #70132

---

core/src/main/java/inetsoft/uql/viewsheet/internal/VsToReportConverter.java

When exporting the viewsheet to PDF format, the datatip should be hidden to maintain consistency with other formats.

Fix Bug #70261:

---

web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.component.ts

should set default value of "show server time zone" to false because in Cloud the server will not important.

fix Bug #70207：

---

web/projects/portal/src/app/composer/dialog/script/save-script-dialog.component.html
web/projects/portal/src/app/composer/dialog/script/save-script-dialog.component.ts
web/projects/shared/util/form-validators.ts

According to the old version of the code, make check invalid js function name logic is same with old version studio.

fix Bug #70283

---

web/projects/em/src/app/settings/schedule/schedule-configuration-view/schedule-classpath-dialog/schedule-classpath-dialog.component.ts

use correct class path item height to calculate the scrollbar position for the schedule class path dialog.

fix Bug #70191

---

web/projects/portal/src/app/composer/gui/tablestyle/editor/save-table-style-dialog.component.html
web/projects/portal/src/app/composer/gui/tablestyle/editor/save-table-style-dialog.component.ts

According to the old version of the code, the table style name role is same to report. do not allow the '~' char for it(see LibManager.SEPARATOR)

fix Bug #70282

---

web/projects/em/src/app/settings/schedule/task-options-pane/task-options-pane.component.ts

the bug is caused by task option time zone should set default value as local time zone. Then if user only set time do not set time zone, should using default time zone.

fix Bug #70270：

---

web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-editor.component.ts

when using url to link to no permission tasks, it will show error 403, then should show proper warning for user but not only show empty dialog.

fix Bug #70277:

---

core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java

Load VSBookmark from the storage before checking if a bookmark with the given name exists. This will ensure that we're checking against the most recent copy of VSBookmark.

Bug #70266 Load VSBookmark from the storage before checking if bookmark exists

---

web/projects/portal/src/app/vsobjects/viewer-app.component.ts

1. Prevent users from other organizations  save bookmarks of host-org.
2. When non-host-org users switch to bookmarks of host-org, automatically discard changes without prompting the user that the bookmark has not been saved.

fix Bug #70288.Bug #70322.

---

core/src/main/java/inetsoft/web/portal/controller/PortalProfileController.java
web/projects/portal/src/app/vsobjects/dialog/profiling-dialog.component.ts
web/projects/portal/src/app/vsobjects/viewer-app.component.ts

Format the timestamp using the client's time zone. Such processing should not be done on the frontend because if the data volume is large, formatting will be slow, leading to the initial display of timestamp data and subsequent refresh into time format.

fix Bug #70287.

---

web/projects/em/src/app/auditing/audit-bookmark-history/audit-bookmark-history.component.ts
web/projects/em/src/app/auditing/audit-schedule-history/audit-schedule-history.component.ts

Because the parameters passed from the frontend contain special characters such as /, &, =, and ,, which cause parsing errors on the backend, it is necessary to encode these parameters on the frontend and decode them on the backend.

Fix Bug #70300:

---

core/src/main/resources/inetsoft/web/resources/js/login.js

The reason for the login failure is that the header information contains non-ISO-8859-1 characters, specifically Chinese characters. The solution is to use encodeURIComponent to encode the Chinese characters.

Fix Bug #70294:

---

core/src/main/java/inetsoft/uql/jdbc/JDBCDataSource.java
core/src/main/java/inetsoft/uql/jdbc/util/JDBCUtil.java
core/src/main/java/inetsoft/uql/listing/AmazonAuroraMySQLDataSourceListing.java
core/src/main/java/inetsoft/uql/listing/AmazonAuroraPostgreSQLDataSourceListing.java
core/src/main/java/inetsoft/uql/listing/AmazonEMRDataSourceListing.java
core/src/main/java/inetsoft/uql/listing/AmazonRedshiftDataSourceListing.java
core/src/main/java/inetsoft/uql/listing/GoogleBigQueryDataSourceListing.java
core/src/main/java/inetsoft/uql/listing/NetezzaDataSourceListing.java
core/src/main/java/inetsoft/uql/listing/SnowflakeDataSourceListing.java
core/src/main/java/inetsoft/web/admin/content/database/DatabaseDefinition.java
core/src/main/java/inetsoft/web/admin/content/repository/DatabaseDatasourcesService.java
core/src/main/java/inetsoft/web/portal/data/DatabaseDatasourcesController.java
core/src/main/resources/inetsoft/util/srinter.properties
web/projects/shared/util/datasource/data-source-settings-page.ts
web/projects/shared/util/model/database-definition-model.ts

Fixes the error message handling when testing a data source connection.
Also has a new message specifically for 504 errors, and an additional custom message for cloud hosted data sources.
This message is configured by setting the "datasource.cloudError" property.
The datasources are specified as "cloud-hosted" by setting the field in their listing class.

Bug #70256  Created "datasource.cloudError" property to allow custom error messages for cloud data sources connection tests.

---

web/projects/portal/src/app/format/objects/formatting-pane.component.html
web/projects/portal/src/app/format/objects/formatting-pane.component.ts

When replacing or modifying the userformat, it is necessary to check whether the previously set format exists. If it does not exist, the model's format should be cleared.

Fix Bug #70333:

---

utils/inetsoft-xml-formats/src/main/java/inetsoft/web/viewsheet/service/PoiImportXLSService.java

for update vs by excel, should load the table data after fresh it, because refresh will overwrite the form table lens changed flag in the VSTableModel.

fix Bug #70318

---

core/src/main/java/inetsoft/util/dep/ViewsheetAsset.java

The fix for bug #70134 may result in occasionally fetching the wrong key from the calcmap, so we use sheet.getBaseWorksheet().getPrimaryAssemblyName() to retrieve it.

Fix Bug #70349:

---

web/projects/em/src/app/settings/schedule/task-action-pane/backup-file/backup-file.component.ts

do not subscribe the repository tree changed event after destroy the component.

fix Bug #70336

---

web/projects/portal/src/app/vsobjects/viewer-app.component.html
web/projects/portal/src/app/vsobjects/viewer-app.component.ts

When clicking the bookmark icon to display bookmarks, do not goto to a specific bookmark, as doing so would cause the loss of ongoing operations, making it impossible to save these changes.

fix Bug #70390. 

---

core/src/main/java/inetsoft/report/filter/AverageFormula.java

When converting a double value to a long type and then assigning it back to a double parameter, the resulting value still retains decimal points, thus appearing as a double.  To obtain the correct value, directly returning the converted long type will yield the accurate result.

Bug #70172

---

core/src/main/java/inetsoft/sree/schedule/Scheduler.java
core/src/main/java/inetsoft/web/admin/schedule/model/TimeZoneModel.java
web/projects/em/src/app/settings/schedule/task-options-pane/task-options-pane.component.ts
web/projects/shared/schedule/model/time-zone-model.ts
web/projects/shared/util/date-type-formatter.ts

support select time zone for task option dates.
When select date, it will create one date object in client with current local time zone, but it should set model to server with select time zone in model. So we should convert the date to right timestamp.
Such as: in local china local, we select 2025-01-02 00:00:00, it will create date 2025-01-02 00:00:00 UTC+8, and after date.getTime, it will get date 2025-01-01 16:00:00 UTC. It will be wrong.
In fact, if we select date 2025-01-02 00:00:00(2025-01-02 00:00:00 UTC+8) and select time zone to UTC0, we want timestamp to 2025-01-02 00:00:00 UTC0, so we should +8 hours for timestamp to get right time we want.
However, when populate date time to date picker, we should change time to local time zone to shwo right date. so that we can keep date …

fix Bug #70329:

---

core/src/main/java/inetsoft/web/binding/controller/ModifyCalculateFieldController.java
core/src/main/resources/inetsoft/util/srinter.properties
web/projects/portal/src/app/binding/widget/binding-tree/vs-binding-tree-actions.ts

1. When switching between Detail and Aggregate types and also the calcfield was used by any bindable assembly, should popup confirm dialog to let the user know the effect.
2. Once user confirmed or directly apply the changes(calc type not changed), should force to sync the assemblies which used the calcfield. so remove the old logic of checking used assemblies.

fix Bug #70415, Optimize the logic of editing calcfield

---

web/projects/portal/src/app/format/objects/formatting-pane.component.html
web/projects/portal/src/app/format/objects/formatting-pane.component.ts

Roll back the changes for Bug #70333, as the format box allows for custom input, so there is no need to consider whether the list exists or not.

Fix Bug #70406,#70333:

---

core/src/main/java/inetsoft/util/dep/ViewsheetAsset.java

The Assemblies in BaseWorksheet cannot accurately retrieve calcFields; they should be obtained based on the sheet's CalcFieldSources.

code review

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleConditionService.java

the bug is caused by date and time instant data will saved by same type in server(use timestamp to save it) so when timestamp without time it will treat it as date. This is old logic for report. When get parameter from report, it will get all parameter name and parameter value and type will according to value. But in styleBI, we do not support report, so we can just get data type from its defined type.
For array timeinstant, it will caused old logic, do not have issue. only change not aray timeinstant case.

fix Bug #69773:

---

core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
web/projects/em/src/app/app.component.ts
web/projects/em/src/app/settings/security/users/users-settings-page/users-settings-page.component.ts

When creating an organization, display a loading page. Automatically close the notification dialog and remove the success notification, as the loading state will exit after a successful creation.

fix Bug #70405.

---

core/src/main/java/inetsoft/web/admin/general/DataSpaceSettingsService.java

Cloud environments typically use Linux or Unix systems, where the file path separator is / instead of \. Using File.separator ensures cross-platform compatibility.

Fix Bug #70173:

---

utils/inetsoft-xml-formats/src/main/java/inetsoft/report/io/viewsheet/excel/PoiExcelVSUtil.java

1. when export form server, the sheet name of RefersToFormula always quoted, see PoiExcelVSUtil#setCellName.
2. after edit sheet, the quote will be auto removed. so use them together to match

fix Bug#70431, use correct cell refersToFormula to find the cell at sheet during import the Excel file to the vs

---

core/src/main/java/inetsoft/web/admin/security/IdentityService.java

the user identity id will be change when the org id is changed. the task id contains the use identity id, so the task id also be change.

fix Bug #70430, update the schedule task permission after the org id is changed

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java

Manually refreshing should obtain the latest status, so don't use activities cache when refresh task list.

fix Bug #70407, don't use activities cache when refresh task list.

---

connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/datasource/surveymonkey/SurveyMonkeyDataSource.java

Since the access token is generated through authorization, there is no need to display the "Use Secret ID" checkbox.

Fix Bug #70448:

---

connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/datasource/linkedin/LinkedinDataSource.java

Since the access token is generated through authorization, there is no need to display the "Use Secret ID" checkbox.

Fix Bug #70449:

---

core/src/main/java/inetsoft/web/admin/schedule/EMScheduleTaskController.java
core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
web/projects/em/src/app/settings/schedule/schedule-task-list/schedule-task-list.component.ts

the bug is caused by when new task, it will create timecondition in server and set server time zone to the condition. In fact, we want to using local time zone by default. So should deliver the local time zone to server when new task.
Should not set time zone in client after new task because new task in server will create condition with server time zone and save it. We should set client time zone before saved new created task.

fix Bug #70126:

---

core/src/main/java/inetsoft/sree/web/dashboard/DashboardRegistry.java
core/src/main/java/inetsoft/web/admin/security/IdentityService.java

1.  user of the UserDashboardRegistry should use new org id when copy dashboard registry from old org to new org. 
2.  after change org id, just copy the old org user`s DashboardRegistry.

fix Bug #70459

---

core/src/main/java/inetsoft/web/viewsheet/service/VSExportService.java

when vs do not have tables, it should not support exporting it to csv type. UI will disable ok button and show warning for user, but this case is using url link to export, should check in server request.

fix Bug #70464:

---

web/projects/shared/util/datasource/data-source-settings-page.ts

Triggered by the changes in #70256, if the cloudError of the database is null, it indicates that the current environment is not in the cloud, and the databaseStatus should be directly output.

Fix Bug #70462:

---

core/src/main/java/inetsoft/web/portal/controller/database/DatabaseDataSourceModelController.java
core/src/main/java/inetsoft/web/portal/controller/database/LogicalModelController.java
web/projects/portal/src/app/portal/services/can-database-model-activate.service.ts

Since the databasePath has already been encoded before being passed, decoding it on the frontend could result in special characters being included in the URL, causing the request to fail. Therefore, it should be decoded on the backend.

Fix Bug #70325:

---

core/src/main/java/inetsoft/web/portal/service/datasource/DataSourceStatusService.java

show timestamp at the end of the error message.

fix Bug #70474, show timestamp at the end of the error message.

---

core/src/main/java/inetsoft/web/composer/ws/dialog/ExpressionDialogController.java
web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts

When the variable name contains characters other than letters and numbers, use `parameter['VAR_NAME']` instead of `parameter.VAR_NAME`.

fix Bug #70394. 

---

core/src/main/java/inetsoft/uql/service/DataSourceRegistry.java
core/src/main/java/inetsoft/web/portal/controller/database/DataSourceService.java
core/src/main/java/inetsoft/web/portal/controller/database/PhysicalModelManagerService.java
core/src/main/java/inetsoft/web/portal/data/DataSourceBrowserService.java
core/src/main/java/inetsoft/web/portal/data/DataSourceController.java
core/src/main/java/inetsoft/web/portal/data/DatasourcesBaseService.java

1. remove logic of setting datasource.isCheckingDuplicate property of the current principal as true for check datasource items duplicate. it maybe affects other requests and threads.
2.  replace it with DataSourceRegistry.IGNORE_GLOBAL_SHARE thread local.

fix Bug #70490, Bug #70488,Bug #70487

---

web/projects/portal/src/app/portal/data/data-datasource-browser/data-datasource-browser.component.html

The attribute name is misspelled.

Fix Bug #70476:

---

core/src/main/java/inetsoft/report/composition/WorksheetEngine.java
core/src/main/java/inetsoft/web/admin/content/repository/AutoSaveController.java
core/src/main/java/inetsoft/web/admin/content/repository/AutoSaveService.java

Hardcoded the value for WorksheetEngine.CACHE_NAME, so that it could be used in the @ClusterProxyMethod annotations.
The IgniteCallable<T> generic doesn't accept void for type T, so I made the restoreAutoSaveAssets() method return a Boolean when it returned void before.

Feature #70119  AutoSaveController service proxy

---

core/src/main/java/inetsoft/web/binding/VSBindingController.java
core/src/main/java/inetsoft/web/binding/VSBindingService.java

The insertChild() controller method uses RuntimeViewsheetRef in the service, so I'll need to revisit it once it is moved out of the service.

Feature #70119  VSBindingController service proxy

---

build-tools/cluster-proxy-annotations/src/main/resources/inetsoft/cluster/apt/Proxy.java.mustache
core/src/main/java/inetsoft/web/binding/VSChartBindingController.java
core/src/main/java/inetsoft/web/binding/VSChartBindingService.java

I needed to update the mustache template used to generate the class.
Before it would escape the type names, so if the types were parameterized, they would have turned into encoded html, like so:
java.util.List&lt;String&gt;
It should now not escape values for the types.

Feature #70119  VSChartBindingController service proxy

---

core/src/main/java/inetsoft/web/admin/monitoring/MonitorDataController.java
core/src/main/java/inetsoft/web/admin/monitoring/MonitorDataService.java

The MonitorDataController itself isn't a websocket.
It takes in the sessionID and updates the websockets of that session.

Feature #70119  MonitorDataController service proxy

---

web/projects/em/src/app/settings/schedule/schedule-task-list/schedule-task-list.component.html

for task next run time is using local time zone to show, but its tooltip do not change, should also using local time zone to show.

fix Bug #70547：

---

web/projects/shared/util/date-type-formatter.ts

when timestamp <= 0, should show empty for time. it means no time for it.

fix Bug #70548：

---

core/src/main/java/inetsoft/uql/util/filereader/CSVLoader.java

Rollback the changes made in Bug #67218. The issue in Bug #67218 was a NullPointerException, which was fixed while addressing Bug #69846. Moreover, the changes in Bug #69846 are the proper solution.

fix Bug #70534

---

core/src/main/java/inetsoft/web/portal/controller/RepositoryTreeController.java

identifier of the asset entry can not as the bookmark id, should use the VSUtil.createBookmarkIdentifier() to generate the bookmark id, it will process some special char.

fix Bug #70511

---

web/projects/em/src/app/settings/security/security-provider/authentication-provider-detail-view/authentication-provider-detail-view.component.ts

The change from #70489 suggests that to maintain the value of name, the judgment should only be made where name is assigned, and not where the model is assigned.

Fix Bug #70576:

---

web/projects/em/src/app/common/util/mat-ckeditor/mat-ckeditor.component.ts

The change event should only be triggered when the value actually changes; otherwise, it will mistakenly indicate that the message in "Deliver to Emails" has been modified, causing the task to be marked as changed.

fix Bug #70395

---

core/src/main/java/inetsoft/web/composer/ws/dialog/ExpressionDialogController.java
web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts

When the variable name contains characters other than letters and numbers, use parameter['VAR_NAME'] instead of parameter.VAR_NAME.

fix Bug #70577, refix Bug #70394

---

core/src/main/resources/inetsoft/util/srinter.properties
web/projects/em/src/app/settings/schedule/schedule-cycle-editor-page/schedule-cycle-editor-page.component.ts

do not allow user to switch the current org on edit data cycle page, because same name data cycle maybe not exist in others org.

fix Bug #70509

---

web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-data-model-browser/data-model-browser.service.ts

In byteEncode, the "/" character is also treated as a special character and gets encoded, which prevents navigation from working properly.

Fix Bug #70550:

---

web/projects/portal/src/app/vsobjects/objects/table/vs-table.component.html

when sort number is 0, should show icon as old version, if number is large than 0, should number instand of the icon.

fix Bug #70571：

---

core/src/main/java/inetsoft/report/composition/execution/AssetQuery.java
core/src/main/java/inetsoft/report/composition/execution/AssetQuerySandbox.java
core/src/main/java/inetsoft/report/script/formula/TableAssemblyScriptable.java

This change prevents fresh query execution when the asset query sandbox is already disposed.

Merge forward Bug #70441 - prevent query execution with disposed asset query sandbox

---

core/src/main/java/inetsoft/uql/asset/sync/TaskAssetDependencyTransformer.java

Fix the issue where the renamed private viewsheet is lost in the task's backup action.

fix Bug #70541

---

core/src/main/java/inetsoft/web/admin/security/OpenIDConfig.java
core/src/main/java/inetsoft/web/admin/security/SSOSettingsService.java

do not send the sso audience to client when audience is empty. because it will get client id as audience for default, after apply setting, the client id will be set to audience, and it will not be changed next changing.

fix Bug #70581

---

core/src/main/java/inetsoft/web/viewsheet/controller/dialog/IdentityTreeService.java

To determine whether the set contains an element, ensure the type consistency between the set collection and the target object.  Due to organizational considerations, modify the type of the set collection.

Fix Bug #70564:

---

core/src/main/java/inetsoft/mv/MVManager.java

ignore the mvDef and log it when can not get the mvDef by key. to ensure the cycle task can load correctly when the storage has error.

fix Bug #70248,

---

web/projects/portal/src/app/vsobjects/objects/output/text/vs-text.component.ts

The bug only occor on docker firfox open vs in tab first time, it will cut text as "xxx...". After refresh it, it will be ok.
The text in case set text size can set content, so we should not cut text. Should init display text after view is changed. So should call textChanged in ngAfterViewChecked()

fix Bug #70592:

---

core/src/main/java/inetsoft/analytic/composition/event/VSEventUtil.java

use Math.round to replace the Math.floor to avoid gaps between two adjacent components after applying scale

fix Bug #70615,

---

core/src/main/java/inetsoft/sree/web/dashboard/DashboardRegistry.java
core/src/main/java/inetsoft/sree/web/dashboard/VSDashboard.java

1. When copying the dashboard registry, the new registry should be saved to the dataspace.
2. If the dashboard references a private viewsheet, the owner's organization ID should be updated.

fix Bug #70546

---

core/src/main/java/inetsoft/util/dep/TableStyleAsset.java
web/projects/em/src/app/settings/schedule/task-action-pane/backup-file/backup-file.component.ts

The path of a tableStyle will change after renaming, so the tableStyleAsset should store the id instead of the path. Additionally, permission validation should compare against the backend's allowed list.

Fix Bug #70630:

---

web/projects/em/src/app/settings/presentation/presentation-themes-view/add-theme-dialog/add-theme-dialog.component.html
web/projects/em/src/app/settings/presentation/presentation-themes-view/add-theme-dialog/add-theme-dialog.component.ts

When adding a theme, the validation logic for the theme name should be the same as the validation logic for the data space file name.

fix Bug #70623

---

core/src/main/java/inetsoft/web/composer/RuntimeSheetTransformController.java
core/src/main/java/inetsoft/web/composer/RuntimeSheetTransformService.java

RuntimeSheetTransformController has multiple methods iterating through the the runtime viewsheets, but only one actually processes the rvs.
The other methods just send even messages with the runtime viewsheet ID to be handled elsewhere.

Feature #70119 RuntimeSheetTransformController service proxy

---

core/src/main/java/inetsoft/web/portal/controller/database/PhysicalModelManagerService.java

Ignore global sharing when creating a physical view; otherwise, a physical view with the same name under the host organization may be retrieved, preventing the physical view from being saved.

fix Bug #70555

---

core/src/main/java/inetsoft/web/admin/security/IdentityService.java

when rename organization, should copy its auto save folder to new org the same as other folders when copy organization.

fix Bug #70613:

---

core/src/main/java/inetsoft/web/portal/controller/TemplateLocalizationController.java

Catch exception that occur when writing a response after the client connection is closed.

fix Bug #70660

---

core/src/main/java/inetsoft/sree/RepletEngine.java

Fix the issue where the viewsheet in dependency info is not updated, causing the viewsheet to not execute the transform logic. Please refer to `AbstractAssetEngine.java:3066`.

fix Bug #70621

---

core/src/main/java/inetsoft/sree/UserEnv.java
core/src/main/java/inetsoft/sree/security/LocaleService.java

Even if localization is not configured in EM, it should still be localized based on the user's browser locale.

fix Bug #70382

---

web/projects/em/src/app/page-header/page-header.service.ts

show the combobox that switch the current org for Materialized Views page, because it loads mvs of the current org.

fix Bug #70685, show the combobox that switch the current org for Materialized Views page, because it loads mvs of the current org.

---

core/src/main/java/inetsoft/web/admin/security/IdentityService.java

after clone the org, will add new org task to scheduler server. during load the new org tasks, should switch current org to new org id, because the backup action will use the current org id during parse xml.

fix Bug #70678

---

core/src/main/java/inetsoft/uql/asset/sync/AssetWSDependencyTransformer.java

If the info is a table, there is no need to modify the AutoDrill information because AutoDrill does not contain table-related data.

Fix Bug #69036:

---

web/projects/portal/src/app/composer/dialog/vs/viewsheet-device-layout-dialog.component.html
web/projects/portal/src/app/composer/dialog/vs/viewsheet-device-layout-dialog.component.ts
web/projects/shared/util/form-validators.ts

When validating the layout name, the following special characters are not allowed: / \ % ^ ~ < > * | ? ".

fix Bug #70608

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java

after rename task, it will transform other task using current task, but when current task use current task, it will not transform. In order to avoid cycle for dependency, so we just change its own actions to using new path when rename task.

fix Bug #70633:

---

core/src/main/java/inetsoft/uql/viewsheet/internal/VSAssemblyInfo.java

When VS is opened again, it is no longer in runtime, so the runtime link has no value. Therefore, the link value should be taken directly.

Fix Bug #70690:

---

web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-editor.component.ts

After saving, the currently saved model should be used as the originalModel for comparison.

Bug #70648

---

core/src/main/java/inetsoft/web/portal/controller/database/DatabaseModelBrowserService.java

When storing the logic model and physical view, the connector symbol between datasource and folder is ^__^, so the same symbol should be used in renameinfo

Fix Bug #70669:

---

core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartControllerService.java

To fix the conflict, I needed to autowire the VSChartAreasServiceProxy and use that instead of the static method that no longer exists.

Feature #70119 Create VSChartControllerService which will be the parent class of all the proxied VSChartController services

---

core/src/main/java/inetsoft/web/AutoSaveUtils.java

When security is false, use the current principal to get the user name instead of the _NULL_ user.

fix Bug #70699

---

core/src/main/java/inetsoft/uql/asset/sync/TaskAssetDependencyTransformer.java

when rename worksheet, the worksheet name is in the batch path, we should transform it.

fix Bug #70670:

---

core/src/main/java/inetsoft/uql/XQuery.java

do not use the curOrgID to replace the org id of the query, if org id changed should sync it. it has done in the MigrateWorksheetTask.

fix Bug #70733, do not use the curOrgID to replace the org id of the query, if org id changed should sync it. it has done in the MigrateWorksheetTask.

---

core/src/main/java/inetsoft/uql/asset/LocalDependencyHandler.java
core/src/main/java/inetsoft/uql/asset/sync/DependencyTransformer.java
core/src/main/java/inetsoft/uql/asset/sync/RenameInfo.java
core/src/main/java/inetsoft/uql/asset/sync/TaskAssetDependencyTransformer.java
core/src/main/java/inetsoft/web/portal/controller/DashboardController.java

1. when task using user dashboard or global dashboard(not viewsheet) in it, should save dashboard dependency in dependency storage.
2. when rename dashboard in portal, should create dashboard asset id for rename info to transform tasks using it.
3. for portal, user dashboard will get from login user, so should using login user to create asset id for user dashboard.
4. after transform tasks, should update storage to new key in dependency storage in order to fix next time rename.
5. add dashboard type in Rename info check if action is rename dashboard or not.
6. for dashboard dependency should using asset identifier as oldname/newname because it should split glocal dashboard and user dashboard(global dashobard will be:  ds name +　”__global“,　 user dashboard will have user scope and user …

fix Bug #70631：

---

core/src/main/java/inetsoft/uql/viewsheet/Viewsheet.java

VSUtil.isTipView should use the AbsoluteName of the assembly and root vs, because the AbsoluteName is relative to the root vs.

fix Bug #70697, VSUtil.isTipView should use the AbsoluteName of the assembly and root vs, because the AbsoluteName is relative to the root vs.

---

web/projects/em/src/app/settings/schedule/task-condition-pane/time-condition-editor/time-condition-editor.component.html

When setting the condition, it depends on the `timeRangeEnabled` property, so the value of `timeRangeEnabled` must be set first.

fix Bug #70694

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
core/src/main/java/inetsoft/web/admin/security/IdentityService.java
web/projects/portal/src/app/portal/schedule/schedule-task-editor/options/task-options-pane.component.ts

1. Avoid using an empty string as the user's alias.
2. Retrieving the latest user from the security provider and then obtaining the alias from the user ensures the alias is correct.

fix Bug #70647, Bug #70794

---

core/src/main/java/inetsoft/analytic/composition/SheetLibraryEngine.java

In scripts, since `-` is not a valid character, it is replaced with `_`.

fix Bug #70702

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
web/projects/em/src/app/settings/schedule/task-action-pane/backup-file/backup-file.component.ts

Bug #70796, don't include cube models in backup task selection. They are implicit dependencies of the XMLA data source.

Bug #70796, don't include cube models in backup task selection.

---

core/src/main/java/inetsoft/uql/viewsheet/VSBookmark.java
core/src/main/java/inetsoft/web/viewsheet/controller/VSBookmarkController.java
core/src/main/java/inetsoft/web/viewsheet/service/VSBookmarkService.java

Don't remove a bookmark first before saving the current bookmark. This prevents the bookmark from going missing if there is a problem with adding the bookmark later. Check for the appropriate bookmark permission that can actually be set in the EM.

Merge forward changes for Bug #69919

---

core/src/main/java/inetsoft/uql/asset/LocalDependencyHandler.java

Update the last modified time of the logical model when the dependencies are updated. This ensures that the resulting blob digest also changes. Without this, there’s a risk that a previously seen digest could reappear, leading to a race condition where the blob is being removed and added at the same time.

Merge forward Bug #70746 - Update the last modified time of the logical model

---

core/src/main/java/inetsoft/uql/asset/sync/AssetDependencyTransformer.java
core/src/main/java/inetsoft/uql/asset/sync/AssetHyperlinkDependencyTransformer.java
core/src/main/java/inetsoft/uql/asset/sync/AssetWSDependencyTransformer.java

pop up the dependency change and reload warning for the runtime viewsheet. when the logic model auto drill is changed by the dependency transformer.

fix Bug #70695, pop up the dependency change and reload warning for the runtime viewsheet

---

web/projects/em/src/app/settings/content/drivers-and-plugins/plugins-view/plugins-view.component.scss

adjust the Plugins list UI to avoid excess blank space when the plugins are few.

fix Bug #70712, adjust the Plugins list UI to avoid excess blank space when the plugins are few.

---

core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java

runtime sheet id may be a worksheet id, for global share assets, just switch to org for the vs, user just can open the shared vs.

fix Bug #70770, runtime sheet id may be a worksheet id, for global share assets, just switch to org for the vs, user just can open the shared vs.

---

web/projects/portal/src/app/portal/report/tree/repository-tree-view.component.ts

the bug is caused by when seach to server, it will get new root nodes of search result, its all nodes is right for client, but client tree will not refresh to new nodes. If you click some action, it will refresh and get right nodes. In fact, we should refresh tree when search is finished.

fix Bug #70111:

---

web/projects/portal/src/app/vsobjects/objects/chart/vs-chart.component.ts

Pass the asset ID to avoid a npe when initializing palettes in `b-categorical-color-pane`.

fix Bug #70834

---

core/src/main/java/inetsoft/uql/asset/sync/ViewsheetBookmarkChangedEvent.java
core/src/main/java/inetsoft/web/composer/RuntimeSheetTransformController.java
core/src/main/java/inetsoft/web/viewsheet/controller/VSBookmarkController.java

the bug is caused by different browse open the same bookmark of the same vs, one user to rename the bookmark, the other browse refresh to new bookmarks but do not select new bookmark.
1  when rename bookmark, add bookmark old name, nname, owner to the event.
2  when browse get bookmark rename event, if opened bookmark is renamed bookmark, should update to new bookmark name.
coding review for it

fix Bug #70099:

---

web/projects/portal/src/app/vsobjects/objects/output/text/vs-text.component.ts

Revert the change for Bug #70592 (GH-482).
Call the textChanged() method less frequently as it creates a DOM element which is a really expensive operation.

Bug #70726 - viewsheet performance fix

---

core/src/main/java/inetsoft/sree/security/Permission.java
core/src/main/java/inetsoft/uql/service/DataSourceRegistry.java

The bug occurred because, when renaming a folder in the cloned organization, the permission key was directly modified. For example, if the current key is DataSourceFolder:f1, the corresponding value (the permission object) contains permissions not only for the original organization but also for the cloned organization. When renaming a folder under the cloned organization, the original key should not be deleted. Instead, only the permissions related to the cloned organization within the original key’s value should be removed. After that, a new key should be created and the corresponding permissions stored under it. This will properly resolve the issue.

Bug #70780

---

core/src/main/java/inetsoft/util/migrate/MigrateDocumentTask.java

when copy organzation we will migate sheets and its document children is right, but inetsoft-asset node is create by cloned org, if clone from host to org0, the inetsoft-asset will be host, we should remove it and it will create new node for it in BlobIndexStorage.putDocument

fix Bug #70788:

---

web/projects/portal/src/app/graph/objects/chart-plot-area.component.ts

If there are no tiles to load then mark the plot area as loaded

Bug #70705 - fix chart loading icon that doesn't want to go away

---

web/projects/em/src/app/settings/schedule/schedule-task-list/schedule-task-list.component.html

The 'next run starting' field should not show tooltip when the task is disabled.

fix Bug #70884

---

web/projects/em/src/app/settings/security/users/users-settings-page/users-settings-page.component.ts

When deleting an organization identity, the organization dropdown should be refreshed.

fix Bug #70887

---

core/src/main/java/inetsoft/sree/internal/SUtil.java
core/src/main/java/inetsoft/util/dep/ResourceNotFoundException.java
core/src/main/java/inetsoft/util/dep/TableStyleAsset.java

table style is a special resource, for table with a tablestyle which alreay have not exist should not effect the dashboard execution, so add ResourceNotFoundException, and only ignore ResourceNotFoundException when doing export.

for Bug #70859, add ResourceNotFoundException

---

core/src/main/java/inetsoft/sree/internal/cluster/ClusterCache.java

Get the value of `lastInstance` again before destroying the cache to avoid the cache being destroyed prematurely.

fix Bug #70587

---

core/src/main/java/inetsoft/sree/security/AbstractEditableAuthenticationProvider.java
core/src/main/java/inetsoft/uql/asset/AssetEntry.java
core/src/main/java/inetsoft/util/AbstractIndexedStorage.java
core/src/main/java/inetsoft/util/BlobIndexedStorage.java
core/src/main/java/inetsoft/util/IndexedStorage.java
core/src/main/java/inetsoft/util/IndexedStorageWrapper.java
core/src/main/java/inetsoft/web/admin/security/IdentityService.java

when rename organzation, its favoritesUser should keep for asset folder, if copy organization to create new org, should clear favorite users.
In fact, vs's favorite user will save in its asset folder in storage, so when copy org not rename org, we should clear favoritessUser for all asset folders.

fix Bug #70847:

---

core/src/main/java/inetsoft/web/viewsheet/EventAspect.java

When adding an audit entry, check if the objectName contains an organization name. If it does, remove the organization part.

Fix Bug #70823：

---

web/projects/portal/src/app/vsobjects/viewer-app.component.ts

The || as the quote parameter value needs to be URL-encoded.

Fix Bug #70895:

---

core/src/main/resources/inetsoft/web/resources/css/login.css
core/src/main/resources/inetsoft/web/resources/login.html

Since login.html is under the java directory, it cannot recognize the modal-header component located under the web directory. As a result, the title does not appear.
To roll back the code:
Previously, the close icon appeared on the left because the .close style was not applied—it was likely overridden by other styles such as .btn-close. To fix this, you need to increase the specificity of the .close style so that it takes effect.

Bug #70816

---

core/src/main/java/inetsoft/web/admin/content/repository/RepositoryObjectService.java

do not set the updateGrantAllByOrg as true when do not set any identity to the new folder permission.

fix Bug #70910, do not set the updateGrantAllByOrg as true when do not set any identity to the new folder permission.

---

core/src/main/java/inetsoft/web/admin/content/repository/RepositoryDashboardService.java

the bug is caused by bug#70778, it want to use owner to get dashboards from registry, should check owner is null, for global dashboard, its owner will be null, should using anonymous as identity.

fix Bug #70925:

---

core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationProvider.java
core/src/main/java/inetsoft/util/Plugins.java

When the driver is uninstalled or installed, reset the database provider's connection and cache to ensure that the next time accessing the database provider's data, it can re-establish the connection and retrieve the data.

fix Bug #70912

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
web/projects/em/src/app/settings/schedule/task-action-pane/viewsheet-action-editor/viewsheet-action-editor.component.ts

1, do not allow user to save the task when the selected bookmark do not exist. 
2, fix NPE when Viewsheet action do not selected any bookmark.

fix Bug #70896,

---

web/projects/em/src/app/settings/security/security-provider/authentication-provider-list-page/authentication-provider-list-page.component.ts

After changing the order of the providers, use the first provider in the current order to refresh the page.

fix Bug #70939

---

core/src/main/java/inetsoft/sree/internal/cluster/ignite/IgniteCluster.java

add custom thread pool to ignite executor to avoid deadlocks caused by thread pool exhaustion.

fix Bug #70869, add custom thread pool to ignite executor to avoid deadlocks caused by thread pool exhaustion.

---

web/projects/em/src/app/settings/schedule/schedule-task-list/schedule-task-list.component.ts

the bug is caused by when server send message to remove task, its task id will have user and org info, but when no security, its task name only have name, so we should check name and its owner is match or not.

fix Bug #70924:

---

core/src/main/java/inetsoft/mv/trans/SelectionDownTransformer.java

Check for the existence of the aggregate by the attribute and if it's found then don't push down the pre runtime conditions.

Bug #70858 - don't push down the pre runtime conditions

---

core/src/main/java/inetsoft/sree/security/AbstractAuthorizationProvider.java
core/src/main/java/inetsoft/sree/security/AbstractSecurityProvider.java
core/src/main/java/inetsoft/sree/security/AuthorizationChain.java
core/src/main/java/inetsoft/sree/security/AuthorizationProvider.java
core/src/main/java/inetsoft/sree/security/FileAuthorizationProvider.java
core/src/main/java/inetsoft/sree/security/ResourceKey.java
core/src/main/java/inetsoft/sree/security/VirtualAuthorizationProvider.java
core/src/main/java/inetsoft/util/Tuple4.java
core/src/main/java/inetsoft/web/admin/security/IdentityService.java
core/src/test/java/inetsoft/sree/security/CustomAuthorizationProvider.java

The bug occurs because resources with identical paths across different organizations share a single permission object, causing permission changes for one org to affect others. Two solutions were considered:
1. Adjust permission-setting/deletion logic everywhere.
2. Include the org ID in the resource key for isolation.
Though option 2 involves more interface changes, it’s more maintainable long-term, so I proceeded with it.

fix Bug #70916, Include the org ID in the resource key for isolation.

---

core/src/main/java/inetsoft/web/admin/content/repository/ContentRepositoryTreeService.java

Except for the program-specific names, other entries should display the name instead of the alias on the EM side.

Bug #70934

---

core/src/main/resources/inetsoft/web/resources/login.html

In Bootstrap 5, the data-dismiss attribute has been deprecated and replaced with data-bs-dismiss.

Fix Bug #70816:

---

core/src/main/java/inetsoft/web/admin/schedule/model/ScheduleTaskModel.java
web/projects/portal/src/app/portal/schedule/schedule-task-list/schedule-task-list.component.ts
web/projects/shared/schedule/model/schedule-task-model.ts

when edit task in em to backup action or batch action, we should remove it from portal because portal do not support this type tasks.

fix Bug #70928:

---

core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java

Fixed the issue of not switching to the new organization after creation. 
In the `try{}` block, it's not guaranteed that the `principal` in `ThreadContext` remains the currently logged-in user because it could be set to something else during the process of copying the organization. Therefore, the old `principal` is restored to `ThreadContext` in the `finally{}` block, and then the `curr_org_id` property is updated to the newly created organization.

fix Bug #70892

---

web/projects/em/src/app/settings/content/repository/import-export/selected-asset-list/selected-asset-list.component.html
web/projects/em/src/app/settings/content/repository/import-export/selected-asset-list/selected-asset-list.component.ts

Fixed the issue where the names of the extended model/view were not displayed correctly in the selected-asset-list.  I checked the previous version, and the `getLabel()` method was added to handle the autosave file, please refer to  `https://repo.inetsoft.com/svn/product/changeset/127760`.

fix Bug #70955

---

web/projects/em/src/app/settings/schedule/task-action-pane/backup-file/backup-file.component.ts

fix Bug #70953
the bug is caused by when logicmodel and partition, only add the node when no children. In fact, when backup file, we should backup logicmodel and partitaion and its children.

fix Bug #70953:

---

web/projects/portal/src/app/portal/schedule/schedule-task-editor/actions/task-action-pane.component.ts
web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.component.ts

When deleting a task condition or task action, do not directly request to delete it. All modifications to the task should be temporary, and changes should only be saved when the "save" button is clicked. This approach ensures consistency with the behavior on the EM side.

fix Bug #70996

---

core/src/main/java/inetsoft/web/portal/controller/RepositoryTreeController.java

Validate the case where the alias is an empty string. If the alias is null or an empty string, renaming the viewsheet should modify the viewsheet's name, not the alias.

fix Bug #70983

---

core/src/main/java/inetsoft/uql/asset/sync/DependencyTransformer.java

When importing cases, all information should be updated to the new organization. Therefore, the organization of audtodirll should be modified before the transformer processes them.

Fix Bug #70951:

---

core/src/main/java/inetsoft/web/composer/ws/CancelLoadingController.java

Send a `ClearLoadingCommand` to immediately exit the loading state when the cancel button is clicked in the WS pane.

fix Bug #71006

---

core/src/main/java/inetsoft/mv/MVManager.java
core/src/main/java/inetsoft/mv/fs/FSService.java
core/src/main/java/inetsoft/mv/fs/XFileSystem.java
core/src/main/java/inetsoft/mv/fs/internal/BlockFileStorage.java
core/src/main/java/inetsoft/mv/fs/internal/DefaultBlockSystem.java
core/src/main/java/inetsoft/mv/fs/internal/LocalFileSystem.java
core/src/main/java/inetsoft/web/admin/security/IdentityService.java

1, fix mv data migrate logic to make it work well. 
step1: clone or rename fs.xml and bs.xml.
step2: clone or rename the mvBlock storage file.
step3: process MVManager.getManager().migrateStorageData to update the mv and block file name to new org. 
2, when update new org XFileSystem item, just rename it, need`t to copied, because fs.xml, bs.xml，mvBlock storage file have been updated. new org has copy data from old org. 
3, need`t copy server node data by FSService.copyServerNode, fs.xml, bs.xml have been copied, and have updated at MVManager.getManager().migrateStorageData.

fix Bug #70991,

---

core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
web/projects/em/src/app/settings/security/property-table-view/property-table-view.component.html
web/projects/em/src/app/settings/security/property-table-view/property-table-view.component.scss
web/projects/em/src/app/settings/security/property-table-view/property-table-view.component.ts

I don't think users should be allowed to manually edit all the org properties from here, since that would require permission to the properties component. I've added the remaining org properties to the list as uneditable rows.

Bug #70964  List all organization scoped properties in the organization editor pane

---

web/projects/portal/src/app/vsobjects/objects/selection/selection-list-cell.component.ts

To maintain consistency with other content, only the icons should be enlarged in mobile mode, not the text.

Fix Bug #71031:

---

core/src/main/java/inetsoft/util/dep/TableStyleAsset.java
core/src/main/java/inetsoft/web/admin/deploy/DeployService.java

parseIdentifier should not check table style exist, during import assets, fist step is get asset list by identifier, if check exist at there, will cause error.

fix Bug #71012, rollback Bug #70630 modify and refix it

---

core/src/main/java/inetsoft/uql/asset/sync/UpdateDependencyHandler.java

example vs "Construction Dashboard" binding asset entry do not have "mainType" property, so can not know source is worksheet, so can not transform binding info during import to target folder. to ensure work well, if binding have AssetEntry.WORKSHEET_TYPE property, think it binding worksheet source.

fix Bug #71024

---

core/src/main/java/inetsoft/uql/asset/sync/TaskAssetDependencyTransformer.java

when rename datasource folder, it will create rename info with datasourcefolder type and full datasource name. So we should using the info to update task backup actions.

fix Bug #70987:

---

web/projects/portal/src/app/vsobjects/objects/table/vs-table-cell.component.ts
web/projects/portal/src/app/vsobjects/objects/table/vs-table.component.html
web/projects/portal/src/app/vsobjects/objects/table/vs-table.component.ts

The table loads data in batches (group by group), and tableData only contains one batch of data. To determine which row within this batch is selected, simply subtract the starting index from the selected row number.

Fix Bug #70960:

---

core/src/main/java/inetsoft/uql/asset/sync/TaskAssetDependencyTransformer.java

when rename alias, it should change alias from old name to newname, but if rename name not alias, it should change new name to entity+newname, but if not entity, should using newname. So add check for newColName is null, should using newname as parameter value.

fix Bug #71019:

---

core/src/main/java/inetsoft/uql/asset/internal/AssetUtil.java

Don't do fuzzy matching when trying to find an aliased column. Adjust the logic which was originally added for Bug #38624.

Merge forward Bug #71081 - fuzzy column matching

---

core/src/main/java/inetsoft/web/composer/AssetTreeRefreshController.java

remove the listener from runtimeAssetRepository before destroy AssetTreeRefreshController.

fix Bug #71058, remove the listener from runtimeAssetRepository before destroy AssetTreeRefreshController.

---

core/src/main/java/inetsoft/sree/internal/cluster/ClusterCache.java

should not decrement the reference count again in the Cluster cache destroy method.

fix Bug #71059, should not decrement the reference count again in the Cluster cache destroy method.

---

core/src/main/java/inetsoft/uql/asset/sync/UpdateDependencyHandler.java
core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
core/src/main/java/inetsoft/util/migrate/MigrateWorksheetTask.java

1. Validate the case where the user is an empty string.
2. Handle the case where the organization is not null but equal when renaming a scheduled task.
3. Rename the source in the worksheet when the username changes.

fix Bug #71014. Fix user renaming issues.

---

web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-data-model-browser/data-model-browser.service.ts

The bug is extend view will not transform in task, so when rename source, it will be lost in task backup list. It caused by saved wrong folder for extend view when no folder, its folder should be null, not "null",  is add extend model parameters should set folder to "" to avoid it add "null" to url.

fix Bug #71068:

---

web/projects/portal/src/app/vsobjects/objects/selection/selection-list-cell.component.html
web/projects/portal/src/app/vsobjects/objects/selection/selection-list-cell.component.scss
web/projects/portal/src/app/vsobjects/objects/selection/vs-selection.component.html
web/projects/portal/src/app/vsobjects/objects/selection/vs-selection.component.scss
web/projects/portal/src/app/vsobjects/objects/selection/vs-selection.component.ts

Adjust the size of the "others" icon on mobile to match the other selection list cells.

Bug-71074 <mobile-selectionlist>"others"icon should adjust larger 

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java

the bug is caused by when task's identity is null, it will not match with bookmark user, so should using modelID to check, modelID will set to owner id when identity is null.

fix Bug #71047: fix issue of bookmarks can not saved for task

---

web/projects/em/src/app/settings/schedule/task-action-pane/backup-file/backup-file.component.ts

Because entity. type = 1024 and node.data.type = 1025, reopening the page allows adding the same datasource again.  Bitwise comparison shows that both include DATA_SOURCE, but 1025 is actually 1024 | 1, meaning it also includes FOLDER. Therefore, even though they refer to the same resource, the types are not exactly equal, which leads to them being treated as different objects. Using a "bitwise contains" check instead of "strict equality"—to be consistent with the service—can resolve this issue.

bug-71028 when add same datasource to backup of schedule,list show repeat datasource

---

core/src/main/java/inetsoft/web/admin/security/IdentityService.java

The bug occurs because the orgId was not passed when calling getPermissions, which caused orgId to be null during getResourceKey.  As a result, the key was generated using the default organization host-org, resulting in: SECURITY_ORGANIZATION:host-org:organization0~;~organization0. The correct key should be:
SECURITY_ORGANIZATION:organization0:organization0~;~organization0. Adding the orgId parameter will resolve the issue.

Bug-71066 <api><security>can't get 'adminIdentities' by web api

---

core/src/main/java/inetsoft/report/PDFPrinter.java

When Arabic numerals (0-9) are present, retain the calculated character spacing to prevent overstretching, which could cause the text to be cut off at the end.

fix Bug #70639, avoid text to be cut off at the end when export with printlayout.

---

web/projects/em/src/app/settings/security/property-table-view/property-table-view.component.ts

Sort the org properties on the frontend so that editable org properties appear first when adding a new org property.

fix Bug #71055. Sort the org properties.

---

core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java

the bug is caused by after rename any bookmark, the home bookmark will changed to current bookmark state because rename will send event to update bookmarks to latest. In fact, we should only update home bookmark when updateHome is true.

fix Bug #71097: should only update Home bookmark to current vs when updateHome is true

---

connectors/inetsoft-onedrive/src/main/java/inetsoft/uql/onedrive/OneDriveQuery.java

the bug is caused by Bug#69653, it remove loadColumns when init the one drive query, it is wrong, should rollback it. After testing, the old bug can not reproduce and works right.

fix Bug #70949: rollback changes(should load columns when init sheet for oneDrive db)

---

core/src/main/java/inetsoft/web/composer/vs/objects/controller/ComposerVSTableController.java

the same as worksheet column, column alias should not the same as other column name, if the same, show warning for user.

fix Bug #71119: fix duplicate alias with other column name

---

core/src/main/java/inetsoft/sree/schedule/ScheduleTask.java

Use the @LinkURL annotation to extract the URL and add it when creating the ViewSheet action. The shell-side issue has been resolved by #71125.

Fix Bug #71117:

---

connectors/inetsoft-odata/src/main/java/inetsoft/uql/odata/ODataRuntime.java

Only successful responses need to be parsed with parseXml; otherwise, it may result in a parsing error.

fix Bug #70917. Fix response parsing error.

---

connectors/inetsoft-googledoc/src/main/java/inetsoft/uql/gdata/GDataRuntime.java

Parse the value of a TIME-type cell in a Google Spreadsheet.

fix Bug #71101. Parse the value of a TIME-type cell in a Google Spreadsheet.

---

core/src/main/java/inetsoft/sree/security/AuthorizationChain.java

use current org id to get permission when org id is null.

fix Bug #71123, use current org id to get permission when org id is null.

---

web/projects/portal/src/app/widget/color-picker/cp-color-pane.component.ts

Wait briefly to let browser autofill capture the input value before emitting the new color and closing the dropdown.

Merge forward fix for Bug #71144 - color browser autofill

---

core/src/main/java/inetsoft/report/composition/execution/VSAQuery.java

The bug is caused by in embed vs, calc use assembly binding such as "viewsheet1.crosstab1", when execute calc in next layer vs(old vs as embed vs), then the assembly binding should add calc's parent on the before("viewsheet1.viewsheet1.crosstab"

fix Bug #71112: fix assembly binding issue when embed vs for some layers

---

core/src/main/java/inetsoft/sree/schedule/TaskBalancer.java

The value of `slotsPerThread` should be at least 1. The cause of the bug is that the start and end times become equal after rounding, which results in a duration of 0. When the duration is 0, `slotsPerThread` becomes 0, leading to the calculation of `requiredThreads` as `Integer.MAX_VALUE`, which ultimately causes continuous object creation and results in an `OutOfMemoryError`.

fix Bug #71118. Fix OutOfMemoryError.

---

web/projects/portal/src/app/vsobjects/objects/viewsheet/vs-viewsheet.component.html
web/projects/portal/src/app/vsobjects/objects/viewsheet/vs-viewsheet.component.scss
web/projects/portal/src/app/vsobjects/objects/viewsheet/vs-viewsheet.component.ts

The event is not being triggered because the parent component (or another higher-level component) is intercepting it. When child and parent components have the same z-index, the child components stack on top of the parent. Therefore, in cases of multi-level nesting, the z-index of child components should be reduced by 1 to ensure proper event propagation.

Fix Bug #71044:

---

core/src/main/java/inetsoft/web/viewsheet/controller/VSBookmarkController.java

Fix NullPointerException: Only notify other sessions when the currently opened bookmark is confirmed to be non-null, ensuring safe deletion.

Fix Bug #71139:

---

core/src/main/java/inetsoft/web/portal/controller/PortalController.java
web/projects/shared/util/guard/global-parameter-guard.service.ts

Because different systems may interpret special characters differently, using encodeURI is sufficient as it only encodes the necessary special characters.

Fix Bug #71085:

---

core/src/main/java/inetsoft/report/lens/CrossJoinTableLens.java
core/src/main/java/inetsoft/util/css/CSSDictionary.java

Fix VSFormatTableLensTest and CrossJoinTableLensTest. 
In CrossJoinTableLens don't recreate the left and right threads in the deserialized table when the processing has already been completed.
In CSSDictionary check if the file isn't null before adding it to the list to test equality. Otherwise lastModified always returns System.currentTimeMillis().

Feature #70313 - fix serialization tests that were failing randomly

---

core/src/main/java/inetsoft/web/admin/content/repository/RepositoryObjectService.java

Except for the self user, the current user should not be added to the user grants for newly created resources. The tracking log shows that it was added when bug # 27925 was resolved on 13.1, but it is unclear what the reason was at that time, the modification seems to not match the description of the bug. Considering that self users do not have permission to log in to EM, fix by deleting the logic of setting permisson for the new created resource.

Bug 71162, shouldn't add permission for the new created resource.

---

core/src/main/java/inetsoft/web/admin/content/repository/RepletRegistryManager.java

Avoid extraneous call to set folder alias, resulting in debouncer task failure

Bug #71161

---

core/src/main/java/inetsoft/mv/MVDef.java
core/src/main/java/inetsoft/mv/MVWorksheetStorage.java
core/src/main/java/inetsoft/mv/fs/internal/BlockFileStorage.java
core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
core/src/main/java/inetsoft/uql/asset/EmbeddedDataCacheHandler.java
core/src/main/java/inetsoft/uql/asset/EmbeddedTableAssembly.java
core/src/main/java/inetsoft/uql/asset/SnapshotEmbeddedTableAssembly.java
core/src/main/java/inetsoft/uql/asset/Worksheet.java
core/src/main/java/inetsoft/util/CoreTool.java
core/src/main/java/inetsoft/util/Tool.java
core/src/main/java/inetsoft/web/admin/security/IdentityService.java

According to the dump file, it was found that the issue was caused by `XSwapper.getSwapper().waitForMemory();` consumes a significant amount of time.", which prevented the current process from completing in a timely manner. By inspecting real-time memory objects, it was discovered that millions of `byte[]` instances and hundreds of thousands of `String` instances existed, leading to high memory usage. Analysis of the case revealed that many worksheet contained embedded tables, and repeatedly creating materialized views (MV) would repeatedly write embedded data, resulting in the generation of a massive number of instances. Therefore, the following optimizations were implemented:  
1. Added cache files for embedded data blocks for MV to utilize disk caching and avoid generating a large …

Bug 70747, performance issue.

---

web/projects/portal/src/app/vsobjects/objects/table/vs-table-cell.component.ts

should not use setTimeout in the table cell component, because table cells is too many, it will cause other setTimeout can not execute on time.

fix Bug #71179, should not use setTimeout in the table cell component.

---

core/src/main/java/inetsoft/uql/viewsheet/graph/MergedVSChartInfo.java
core/src/main/java/inetsoft/uql/viewsheet/graph/VSMapInfo.java
core/src/main/java/inetsoft/uql/viewsheet/internal/VsToReportConverter.java

When collecting all runtime fields, if the object is a Map type, geographic fields should be included (consistent with the previous Report processing logic). Additionally, any hyperlink fields should also be added to the geographic fields collection.

Fix Bug #71140:

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java

in old version, it will change timeInstant value without time to date.
In stylebi, it will change date to timeInstant value.
The two issue becaused date and timeInstant in client will all change to java.util.Date, and  in 13.8, it check value is date or timeinstant according with time or not, in stylebi, it will change all java.util.date object to timeInstant by using Tool.getDataString method.
In fact, we should split right types to avoid the two issues. For date type value should using java.sql.Date to save value, timeInstant keep old type.

fix Bug #71170: split date and timeinstant type value in task embed parameters

---

web/projects/portal/src/app/composer/gui/composer-main.component.ts

fix show '%s$0' in vs expired dialog

bug-71178 show '%s$0' in vs expired dialog

---

core/src/main/java/inetsoft/report/io/viewsheet/pdf/PDFVSExporter.java
core/src/main/java/inetsoft/uql/viewsheet/internal/VsToReportConverter.java

The bug occurs because the SVG image does not properly handle transparency. Using the opacity attribute may sometimes have no effect, as some SVG renderers ignore the <svg> element's opacity when converting to PDF or printing. Therefore, using fill-opacity and stroke-opacity, which directly affect the drawing properties, can effectively achieve the desired transparency.

bug-71095 image setting alpha layout header,it can not applied

---

core/src/main/java/inetsoft/web/binding/VSFormulaController.java
web/projects/portal/src/app/binding/widget/binding-tree/vs-binding-tree-actions.ts
web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts

the bug is caused by user create agg and binding agg do not split and we should only support to delete user agg, binding agg should not delete from calc pane.
check agg is user agg or not according to get it from aggregatemap in viewsheet.

fix Bug #71175: split user create aggregates and binding create aggregates in calc pane

---

core/src/main/java/inetsoft/report/composition/execution/ViewsheetSandbox.java
core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java

When obtaining the content of the text, it is retrieved based on the viewsheet stored in the sandbox's bmap (used to store EmbeddedViewsheet). When we perform a refresh, the viewsheet in the sandbox is updated, but the viewsheet in the bmap is not. Therefore, when assigning a value to the text, it only updates the viewsheet in the bmap and does not update the current runtimeViewsheet. Thus, during a manual refresh, the content of the bmap should be cleared.

Fix Bug #71180:

---

core/src/main/java/inetsoft/web/viewsheet/controller/dialog/ScheduleDialogController.java

Under the condition of no cache, the startTime will be assigned the default value of -1. When saving data on the backend, only null values were handled, but negative numbers were not processed. Simply add logic to handle negative numbers.

Fix Bug #71187:

---

web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts

set useragg to null if not aggregate only to prevent css set as summary extraneously

Bug #71200

---

core/src/main/java/inetsoft/sree/security/ldap/LdapAuthenticationProvider.java

For the LDAP provider, organizations are not supported. Therefore, when retrieving roles, any role that does not belong to the "host-org" or has a null organization ID should be filtered out. Since organization support is not available, roles like "org-admin" should also be excluded.

bug-71169  setting ldap at first, switch to actions pane and add permission, some role load duplicate

---

core/src/main/java/inetsoft/web/portal/data/DataSourceBrowserService.java

For folders without permission, only the parent path should be displayed during the move operation, rather than showing the path as if the current data source has already been moved into the new location. Otherwise, it may give a misleading impression that the move has already been completed.

bug-71181 permission prompts is wrong

---

web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts

Only newly created aggregates have a delete menu; the original ones should not be displayed. The reason for the display is that node?.data?.useragg is a string-type value, which should be compared with true to return a boolean value.

Fix Bug #71205:

---

core/src/main/java/inetsoft/report/composition/execution/ViewsheetSandbox.java
core/src/main/java/inetsoft/uql/viewsheet/Viewsheet.java

Use the absolute name to find an assembly in embedded viewsheet.

Bug 71174. Find the assembly to avoid NPE.

---

core/src/main/java/inetsoft/report/composition/execution/ViewsheetSandbox.java
core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java

1. don't add sub viewsheet assembly entrise to main changed list when parent entry have already in data list, else will cause refresh duplicated times which will effect performance.
2. in refresh assembly logic, shouldn't to recursive to get all the assemblies to init tables, that will make assemblies in nested embedded viewsheet be refresh multi times.

fix Bug #71142, improve performance.

---

core/src/test/java/inetsoft/web/composer/vs/controller/ComposerViewsheetApiControllerTest.java

The ComposerViewsheetServiceProxy creates the ComposerViewsheetService by getting the bean from the configuration context.
In the test case, we have to mock the getBean method on the configuration context to return a new instance of the ComposerViewsheetService  that we created in the setup method.

Fix Test Cases for ComposerViewsheetApiController

---

core/src/main/java/inetsoft/sree/security/AbstractAuthenticationProvider.java
core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationProvider.java
core/src/main/java/inetsoft/sree/security/ldap/LdapAuthenticationProvider.java

return null when the role do not exist during get role by IdentityID.

fix Bug #71223, return null when the role do not exist during get role by IdentityID.

---

core/src/main/java/inetsoft/util/migrate/MigrateDocumentTask.java

the bug is caused by bug#70788, it removed old document's inetsoft-asset child node becaused putDocument will create new node for it. But for auto save file, it will not put, so should get old node to change to new organization node. so should split them.

fix Bug #71176: should not remove asset header for auto save files

---

web/projects/portal/src/app/widget/fixed-dropdown/fixed-dropdown.component.ts
web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.html
web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts

The bug occurs because the event listener is attached to the document level, but in the formula-editor-dialog component, blockMouse is applied to the body, which prevents event bubbling. As a result, the event does not reach the document and is not captured. By attaching the listener directly to the form element under the body, the event is not blocked, which resolves the issue.

bug-71204 multiple delete menu pop up, they have coverage.

---

core/src/main/java/inetsoft/sree/schedule/AbstractAction.java

for smtp emai, should send email according to the config server and mail, should not use the user email because user email will not match with smtp server.

fix Bug #71250: fix smtp email should not use user email to send email in task

---

core/src/main/java/inetsoft/report/composition/execution/PreAssetQuery.java
core/src/main/java/inetsoft/uql/jdbc/XExpression.java
core/src/main/java/inetsoft/uql/jdbc/util/ConditionListHandler.java

When performing queries, the attribute types should be consistent with the database. Therefore, the type of a Variable cannot be changed according to the column type. However, considering the application of Variables in other contexts, we should modify the type of the Variable to match the type of the attribute being queried in the database when constructing the SQL statement.

Fix Bug #71232:

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskChangeController.java

send the status change model to portal when the group share task finish.

fix Bug #71257, send the status change model to portal when the group share task finish.

---

core/src/main/java/inetsoft/uql/viewsheet/Viewsheet.java

Due to the changes in #71174, when fetching the Assembly, the logic was modified from directly retrieving the innermost chart to getting the outermost viewsheet and then searching layer by layer downwards. However, this approach can only reach the second layer and will fail with multiple nested layers. Therefore, it should be changed to search in reverse (from inner to outer).

Fix Bug #71258:

---

core/src/main/java/inetsoft/web/binding/VSFormulaService.java
core/src/main/java/inetsoft/web/binding/controller/VSTableLayoutService.java
core/src/main/java/inetsoft/web/binding/handler/VSColumnHandler.java
core/src/main/java/inetsoft/web/composer/vs/dialog/SelectionListService.java
core/src/main/java/inetsoft/web/composer/vs/objects/controller/VSObjectPropertyService.java
core/src/main/java/inetsoft/web/viewsheet/service/VSInputService.java
core/src/main/java/inetsoft/web/viewsheet/service/VSOutputService.java
core/src/test/java/inetsoft/web/composer/vs/dialog/ImagePropertyDialogControllerTest.java
core/src/test/java/inetsoft/web/composer/vs/objects/controller/VSObjectPropertyServiceTest.java

VSInputService -> VSObjectPropertyService -> VSInputService
Move getTableColumns() from VSInputService to VSColumnHandler

Fix a circular dependency issue

---

web/projects/portal/src/app/binding/editor/data-editor.component.scss

Since the table binding area can accommodate many fields, it is necessary to set a maximum display height of three rows of data, with a scrollbar appearing for any overflow content.

Fix Bug #71280:

---

core/src/main/java/inetsoft/util/script/JavaScriptEngine.java

this is an old bug, return quarter of year is interval is "q" as document describes.

fix Bug #71285, return quarter of year is interval is "q" as document describes.

---

core/src/main/java/inetsoft/web/portal/controller/RepositoryTreeSearchController.java

When searching tree nodes, folder nodes should be in the expanded state.

fix Bug #71286. When searching tree nodes, folder nodes should be in the expanded state.

---

core/src/main/java/inetsoft/report/script/viewsheet/ViewsheetVSAScriptable.java

If a multi-level nested embedded viewsheet correctly obtains its scope during script execution, there is no need to repeatedly search for the embedded viewsheet during the process, as doing so may lead to incorrect script execution hierarchy.

Fix Bug #71222: Modify multi-layer nested embedded viewsheet execution script.

---

web/projects/portal/src/app/vsobjects/dialog/graph/hyperlink-dialog.component.ts

The `fields` property is used when adding a parameter of type "field" for a hyperlink. It is not used when sending a request to set the hyperlink. If there are too many fields, it may exceed the WebSocket request size limit. Therefore, the `fields` property value is not included when submitting the hyperlink model.

fix Bug #71295. Handle errors caused by request messages exceeding the WebSocket size limit.

---

core/src/main/java/inetsoft/sree/PropertiesEngine.java

Remove `sree.properties` since the current properties are stored in the `blob` and `kv` directories.

fix Bug #71299. Remove `sree.properties` property.

---

web/projects/portal/src/app/vsobjects/dialog/combo-box-editor.component.ts

This bug occurs because value is an empty array ([]), so value[0] is undefined. As a result, accessing value[0].value causes an error. You need to handle this case separately—only access value[0].value when value has at least one element.

bug-71302 open combox has default value,pop up error 

---

core/src/main/java/inetsoft/report/script/viewsheet/ViewsheetScope.java
core/src/main/java/inetsoft/web/viewsheet/service/VSExportService.java

The bug occurred because when a new ViewsheetSandbox object was created, the original VariableTable was also reset. However, executing the script requires values from the parameter, and since the parameter did not contain any data (e.g., date: 2024-01-24), the script execution resulted in the text component displaying its default value. To fix this, the original VariableTable should be set into the new ViewsheetSandbox object after it is created. This ensures that the script executes successfully and the text component can retrieve the correct value.

bug-71238 script parameter value can't display in print layout

---

core/src/main/java/inetsoft/web/viewsheet/controller/OnClickController.java

When there are multiple levels of nested viewsheets, obtain the `ViewsheetSandbox` based on the name of the innermost viewsheet to ensure it can be retrieved correctly.

fix Bug #71303. Fix NPE.

---

core/src/main/java/inetsoft/util/dep/ViewsheetAsset.java

Due to an incorrect way of referencing the worksheet in the 'runQuery' script, a `null` was added to the dependency list. Therefore, add a check for `null` values.

fix Bug #71300. Add a check for `null` values when collect 'runQuery' script dependencies.

---

core/src/main/java/inetsoft/util/script/CalcMath.java

When calculating the greatest common divisor of two numbers, an exception should be thrown if either number is negative.

fix Bug #71329. Throw an exception if either number is negative when computing the GCD.

---

core/src/main/java/inetsoft/web/admin/content/repository/RepositoryObjectService.java

The bug occurred because when deleting the style folder on the EM side, only the current folder was deleted without removing all the table styles under it. To fix this, all styles and subfolders within the folder should also be deleted.

bug-71322  delete table styles folder, style always display in table

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskFolderService.java

do not load uses for EditTaskFolderDialogModel, because now it do not support change owner, task folder is global. please see Bug #43793.

fix Bug #71324, 

---

core/src/main/java/inetsoft/uql/viewsheet/VSDimensionRef.java

Due to the changes in #70201, when a column cannot be found, a warning pops up but the operation cannot proceed, so the previous code that did not invoke the old events and commands is being added back.

Fix Bug #71336:When a column cannot be found, a warning pops up but the operation cannot proceed.

---

core/src/main/java/inetsoft/util/script/CalcTextData.java

for CalcTextData.substitute to avoid infinite loop  when old_text is empty return original text.

fix Bug #71361,  for CalcTextData.substitute to avoid infinite loop  when old_text is empty return original text.

---

core/src/main/java/inetsoft/report/composition/execution/TimeSliderVSAQuery.java

for rangslider binding cube date(cube string column define as date to be a date column), it will treat unit as Month and using min and max date to get all dates in them. should fix it as this
1.  when cube data, should return tablelens for rangslider and get values from tablelens.
2. when value is CubeDate(as date for olap column), should get its MemberObj and to get its caption to as value, then it will using the value to create right condition in MDX.

fix Bug #71305: fix rangslider binding olap column which setting as date attribute

---

web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts

The bug was caused by assigning a value to an undefined object when closing `newAggrDialog`, so a default value is assigned to the `userAggNames` object.

fix Bug #71365. Fix can't add aggregate.

---

core/src/main/java/inetsoft/web/admin/deploy/DeployService.java

The modified logic checks orgID equality if multi-tenancy is enabled, otherwise verifies EM access permissions.

Fix Bug #71298:The modified logic checks orgID equality if multi-tenancy is enabled, otherwise verifies EM access permissions.

---

core/src/main/java/inetsoft/web/composer/ws/dialog/AssemblyConditionDialogController.java
web/projects/portal/src/app/composer/dialog/ws/assembly-condition-dialog.component.ts

1 for olap column set as date, it can do date level group to column, and then it can only do pre condition for original column, but can post condition for group columns. 
2 for pre-condition pane, should not load cube columns in list(maybe table from olap and normal to join, so should check cube type for every field, field list maybe have different columns mixed) 
3 when add simple condition to list, should change olap orginal column to pre condition, date group for olap time dimension should push to post conditions

fix Bug #71314: olap date group only can create post condition

---

core/src/main/java/inetsoft/web/composer/model/vs/VSSortRefModel.java
core/src/main/java/inetsoft/web/composer/vs/dialog/VSSortingDialogController.java
web/projects/portal/src/app/composer/data/vs/vs-sort-ref-model.ts
web/projects/portal/src/app/composer/dialog/vs/vs-sorting-dialog.component.ts
web/projects/portal/src/app/composer/dialog/vs/vs-sorting-pane.component.html

Don't send data ref objects to the client. Column names are sufficient.
Exclude unsorted columns from the final result sent to the server, as they are never accessed.

Bug #71364 - optimization fixes for the sorting dialog

---

core/src/main/java/inetsoft/util/dep/ScheduleTaskAsset.java

parent and ancestor folders should be imported recursively when importing a task folder.

fix Bug #71380, parent and ancestor folders should be imported recursively when importing a task folder.

---

core/src/main/java/inetsoft/util/log/LogManager.java

When not in multi-tenant mode, retrieving the context level should ignore the organization part in the custom log level name.

fix Bug #71355. Fix the issue where `custom log level - role` does not work in non-multi-tenant mode.

---

core/src/main/java/inetsoft/web/viewsheet/handler/crosstab/CrosstabDrillHandler.java

not only occor for olap, normal db have same issue. for embed crosstab to drill, should using its abosolute name not name to get tablelens. for normal assemblies, they are same, for crosstab in embed vs, they are different.

fix Bug #71382:  crosstab in embed vs drill issue.

---

core/src/main/java/inetsoft/uql/viewsheet/internal/ImageVSAssemblyInfo.java

image's pop up component can not apply alpha, because we add alpha value for ImaggeVSAssemblyInfo in 2013, but add alphaValue for ClickableOutputVSAssemblyInfo in 2023(image's parent class) so the attribute is duplicate, remove it from ImageVSAssemblyInfo

fix Bug #71296: image‘s popup component can not apply alpha

---

web/projects/em/src/app/settings/logging/add-logging-level-dialog/add-logging-level-dialog.component.html
web/projects/em/src/app/settings/logging/add-logging-level-dialog/add-logging-level-dialog.component.ts

The "organization" field should only be displayed when both "enterprise" is enabled and "isMultiTenant" is turned on. When the "organization" field is selected, a dropdown selector should appear. The backend should receive the selected value using the "name" attribute.

Fix Bug #71392:Update the settings for the 'organization' option.

---

core/src/main/java/inetsoft/util/log/LogContext.java

Add organization information to the MDC, so that logs can be filtered based on the custom log level of type 'ORGANIZATION'.

fix Bug #71378. Fix the issue where logs cannot be filtered by the 'ORGANIZATION' log level.

---

web/projects/portal/src/app/composer/gui/composer-main.component.ts

When opening the "Save As" dialog, the created model must pass not only the name but also the identifie; otherwise, the identifier will be null, causing an error.

Fix Bug #71402:Assign a value to the ​​identifier​​ in the model.

---

core/src/main/java/inetsoft/util/log/LogContext.java
core/src/main/java/inetsoft/util/log/LogManager.java

Unify the naming convention for log levels so that the organization ID is always included, regardless of whether the system is multi-tenant. This ensures that switching tenants does not affect the retrieval of log levels.

fix Bug #71386. Fix the issue where the custom log level does not take effect.

---

web/projects/portal/src/app/widget/fixed-dropdown/fixed-dropdown.component.ts

Add a click event listener to the form on the page, allowing it to trigger the documentClick method and close after clicking.

Fix Bug #71401:Add a click event listener to the form on the page.

---

core/src/test/java/inetsoft/test/TestCluster.java

don't fire event when initing visual security providers, else will cause dead lock  like: sree init -> log -> init security engine(locked) -> init&save visual security -> PutBlobTask  -> LocalKeyValueStorage.entryAdded(new thread) -> log -> init security engine(blocked)

fix dead lock for auto test.

---

core/src/main/java/inetsoft/util/script/CalcDateTime.java

Fix the issue in the `CALC.time()` script function where the result is incorrect when the hour, minute, or second parameters exceed their valid ranges. The cause was that the overflow part of these values was discarded in the code, whereas Excel applies carry-over logic in such cases.

fix Bug #71436. Fix incorrect value calculation in the `CALC.time()` script function.

---

core/src/main/java/inetsoft/report/filter/CrossTabFilter.java

when date group for crosstab, it will create default format according to deta level, but if level is none, should not set default format for it and then make to use source format.

fix Bug #71377: none date level should not create default format according to level, should use source format

---

core/src/main/java/inetsoft/analytic/composition/event/ChartVSSelectionUtil.java

should add measure ref in size field for treemap so it can get right MDX to drillthrough and then to get right data for show detail.

fix Bug #71461: should add size measure to MDX to get right drillthrough result for MDX

---

core/src/main/java/inetsoft/report/composition/execution/AssetQuery.java

percentage data which less than 1 were changed to 0 when convert data by data type in formulatablelens, fixed by using double datatype if origin column applied percentage option.

fix Bug 71434, fix datatype.

---

core/src/main/java/inetsoft/report/filter/TextComparer.java

The bug occurred because the JVM parameter -Duser.language=en was not used, causing the system's default locale to be applied instead. When performing string comparisons, the behavior depends on the locale, specifically by using RuleBasedCollator, which considers linguistic rules—a relatively time-consuming approach. Also, testing on JDK 1.8 and JDK 21 revealed that JDK 21 is nearly twice as slow as JDK 1.8, which are the two root causes of this bug.
To optimize performance, we improved the compare method in TextComparer. If both strings are ASCII-only, the default string comparison is used instead, reducing the execution time from 45s to 12s.

fix Bug #71460, improve performance

---

web/projects/portal/src/app/binding/editor/binding-editor.component.scss

should only show horizontal for table to show all columns, should hide vertical scrollbar for object container to show better, for table will have its vertical scrollbar to loading data according scrollbar. show two vertical scrollbar will be duplicate.

fix Bug #71455: should only show horizontal for vs object container.

---

core/src/main/java/inetsoft/report/LibManager.java
core/src/main/java/inetsoft/report/composition/execution/MirrorQuery.java
core/src/main/java/inetsoft/report/composition/execution/TableFilter2.java
web/projects/portal/src/app/embed/viewer/embed-viewer.component.html
web/projects/portal/src/app/embed/viewer/embed-viewer.component.scss
web/projects/portal/src/app/embed/viewer/embed-viewer.component.ts
web/projects/portal/src/app/vsobjects/action/chart-actions.ts
web/projects/portal/src/app/vsobjects/viewer-app.component.ts

Bug #71351
Fix popover component positioning.
Since TableFilter2 is cloned when retrieved from the cache, store the column identifier in TableFilter2 instead of passing it down to the base table lens to avoid issues when a table lens is shared across different viewsheets. Move LibManager initialization inside the lock to avoid uninitialized usage by other threads.
Bug #71396
Stop loading on error
Bug #71468
Fix dialogs, dropdowns, data tips and pop components from showing behind other web components. Format pane doesn't render well inside the web component so hide the action.

Merge forward bug fixes for web components

---

core/src/main/java/inetsoft/sree/internal/SUtil.java
core/src/main/java/inetsoft/sree/schedule/ScheduleServer.java
core/src/main/java/inetsoft/sree/schedule/ScheduleTask.java
core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java

Use the correct format of log level name to retrieve the log level. The correct format is: `UserName:TaskName^OrgId`.
For non-enterprise environments, the log level name without the organization ID is used. In this case, the correct format should be: `UserName:TaskName`.

fix Bug #71443. Fix the issue where custom log levels for Schedule Task do not take effect.

---

web/projects/portal/src/app/widget/tree/tree.component.ts

when get column data from tree node, it only add table name and column name, should also add entity name to compare. For olap data, some column with same column name and table, it will find wrong. For other case, entity will be null so do not affect.

fix Bug #71477: add entity for column node data to find right column to expand

---

web/projects/portal/src/app/vsobjects/objects/selection/vs-selection.component.html

Adjust the size of the "More" icon on mobile to match the other selection list cells.

Fix Bug #71471:Adjust the size of the "More" icon

---

core/src/main/java/inetsoft/report/composition/graph/VGraphPair.java
core/src/main/java/inetsoft/web/viewsheet/controller/AssemblyImageService.java

for legends with large data, it will caused to use two images, the second image have only serval legend should using title height to paint to do not show some gap in legend place.

fix Bug #71370: legend content should paint right height to do not show gap in bottom

---

core/src/main/java/inetsoft/web/portal/controller/database/DataSourceService.java

In the self organization, each role operates independently, so the dataSource is not public. However, dataSource names must remain unique across different roles. Therefore, we can add a name-based check to determine which meta data to reference, and subsequently, which cache to retrieve.

Fix Bug #71469:Add the judgment of "name"

---

core/src/main/java/inetsoft/web/admin/logviewer/LogSettingService.java
web/projects/em/src/app/settings/logging/add-logging-level-dialog/add-logging-level-dialog.component.ts

To modify the two issues:
1.When the Log type is organization, the name and organization fields both display the organization name, causing duplication. It should only display in the name field. 
2.On the backend, both storing values in contextLevels and retrieving values from MDC should be based solely on the orgID.

Fix Bug #71470:Modify the UI display and value storage/retrieval.

---

core/src/main/java/inetsoft/report/composition/execution/CubeQuery.java

For cube worksheets, all conditions are post-processed. If a condition depends on a range column, should add its base attribute to the query instead of the range column itself.

fix Bug #71489. Fix NPE and condition application issues.

---

core/src/main/java/inetsoft/report/composition/execution/AssetQuery.java
core/src/main/java/inetsoft/report/filter/SummaryFilter.java

olap as date column can not apply its output format because in SummaryFilter, it get default format accordong to date level, but for olap date it should not apply date level and we should use the db format as default format. Crosstab and chart will be ok.

fix Bug #71499: olap as date column should apply db format

---

core/src/main/java/inetsoft/web/composer/ws/OpenWorksheetController.java
core/src/main/java/inetsoft/web/viewsheet/service/VSLifecycleService.java

When adding log records, to distinguish between resources under different organizations and private spaces, we uniformly use the format:user's name + "/" + sheet's path.

Fix Bug #71472:Uniformly use user's name + '/' + sheet's path for logging.

---

core/src/main/java/inetsoft/uql/viewsheet/CrosstabVSAssembly.java

when rename calc fields, should rename its ranking col value, if ranking value have total, should rename column name after ":"

fix Bug #711515: olap calc rename should rename its rankingcol with total

---

core/src/main/java/inetsoft/sree/schedule/ScheduleManager.java

when change one user, tasks of this user will update, but other user's task maybe used this user's task, then we should update it and resave to new use name.

fix Bug #71478: user renamed should update some tasks of other user if it used current user's task as condition.

---

core/src/main/antlr/inetsoft/uql/util/sqlparser/SQLParser.g
core/src/main/java/inetsoft/uql/util/XUtil.java

for varaible in sql, should not quote it for it will replace to right value when executequery(replacevariables)

fix Bug #71462: should not quote variable in sql parser

---

web/projects/portal/src/app/widget/condition/top-n-editor.component.ts

In frontend development, you cannot simply check if a value equals null - you must also exclude empty strings ("") and undefined.

Fix Bug #71535:Exclude empty strings ("") and undefined.

---

core/src/main/java/inetsoft/web/portal/data/DataSetService.java
core/src/main/java/inetsoft/web/portal/data/WorksheetBrowserInfo.java

If no worksheet permission, only can not edit worksheet but can rename and move, rename and move only check asset permission, but edit ws should open composer so should have worksheet permission in compose

fix Bug #71622: can not open worsheet to edit when no worksheet permission

---

core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartBrushController.java
web/projects/portal/src/app/vsobjects/objects/chart/vs-chart.component.html
web/projects/portal/src/app/vsobjects/objects/chart/vs-chart.component.ts
web/projects/portal/src/app/vsobjects/objects/vs-object-container.component.html
web/projects/portal/src/app/vsobjects/objects/vs-object-container.component.ts
web/projects/portal/src/app/vsobjects/viewer-app.component.html

This bug reproduces when the chart has thousands of plot items and dimension labels. fix by following logic:
1. Don't send ClearChartLoadingCommand after finishing brush. This is because if the graph is too complex, even though the brush operation has ended, the refresh of the chart area is slow, resulting in a situation where neither the loading indicator is shown nor the brushed chart area is immediately displayed. The logic to send ClearChartLoadingCommand after brushing was originally added to fix Bug #25716. However, since SetChartAreasCommand (which ends chart loading) is sent after the chart area refresh completes, removing this logic is acceptable.
2. Support showing chart loading in max mode. Originally, disabled chart loading in max mode is added to fix Bug #39759. The solution …

fix Bug #71500, fix brush issue for complex chart

---

web/projects/em/src/app/settings/schedule/task-options-pane/task-options-pane.component.html
web/projects/em/src/app/settings/schedule/task-options-pane/task-options-pane.component.ts

The visibility of the loading spinner should not directly depend on whether `adminName` has a value, because for non-administrator users like `user0`, `adminName` will be `null`   Therefore, whether the spinner is shown should depend on when the subscription for `adminName` responds with a result.

fix Bug #71566. Fix spinner always showing.

---

core/src/main/java/inetsoft/web/viewsheet/controller/dialog/EmailDialogController.java
core/src/main/resources/inetsoft/util/srinter.properties

fix Bug#71709
the bug is caused when no expand component permission, UI will disable expand option, but user can change html page to enable it, then select it to server, we should check permission in server and do not support it to o

fix Bug #71709: when no permission to expand, should check permission in server

---

core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java
core/src/main/java/inetsoft/web/viewsheet/service/VSBookmarkService.java

fix Bug #71546, refresh bookmark map in case other user updated bookmarks.
fix Bug #71564 modify and refix it. apply the bookmark after reset viewsheet Runtime, it will update the embedded vs, overwrite current bookmark.

fix Bug 71546 71585

---

core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartController.java

the bug is only caused when when close max mode in embed vs, do not reload table data for embed vs, in fact, we should reload all assemblies in embed viewshee

fix Bug #71701: close max mode, should loading all data in embed viewsheet

---

core/src/main/java/inetsoft/report/composition/execution/AssetQuery.java

when execute worksheet query, should check null for viewsheetsandbox to void query can not execute.

fix Bug #71727: check null to avoid worksheet query can not execute

---

core/src/main/java/inetsoft/web/composer/vs/objects/controller/VSObjectPropertyService.java

The code needs to consider that a group may contain tabs, and tabs can contain embedded viewsheets, so such groups should also be excluded.

Fix Bug #71651:Embedded viewsheets are not allowed in PopComponent.

---

web/projects/portal/src/app/vsobjects/objects/table/vs-table-cell.component.ts

pageX/pageY are coordinates that include the scrolling offset. For a dropdown menu, if the page is scrolled, using these will cause the menu to be positioned incorrectly. Therefore, clientX/clientY, which are based on the browser’s viewport, should be used to display the menu.

fix Bug #71678. Fix the position of hyperlink item not right.

---

core/src/main/java/inetsoft/sree/schedule/ScheduleManager.java

Fix the issue where chained tasks were not executed. When the "Run After" task in the chained condition changes, add the current task to the `changedTasks` set to ensure it gets saved.

fix Bug #71526. Fix chained task can't be triggered after rename user.

---

web/projects/portal/src/app/vsobjects/objects/chart/vs-chart.component.ts
web/projects/portal/src/app/vsobjects/objects/data-tip/adhoc-filter.service.ts
web/projects/portal/src/app/vsobjects/objects/table/base-table.ts
web/projects/portal/src/app/vsobjects/objects/table/vs-calctable.component.ts
web/projects/portal/src/app/vsobjects/objects/table/vs-crosstab.component.ts
web/projects/portal/src/app/vsobjects/objects/table/vs-table.component.ts

fix Bug #71680, when maxmode, should always show scrollbar's tooltip on left, for chart will in full screen to overlap the tip
Bug #71670:
when open max mode or close max mode, should hide adhoc filter(if filter have data filter, it will move it to container, if do not have data, it will remove)

Bug 71680(tooltip show in left when maxmode) and  Bug #71670(adhoc filter apply when change max mode)

---

core/src/main/java/inetsoft/web/portal/data/DataSetService.java

When a user operates on assets under the USER_SCOPE, there is no need to check whether they have permission for the asset they are operating on.

fix Bug #71718. Fix the issue where moving a folder under User\_Scope prompts a permission error.

---

core/src/main/java/inetsoft/web/portal/data/WorksheetBrowserInfo.java

Fix the error caused by the missing `canWorksheet` property when constructing `WorksheetBrowserInfo`.

fix Bug #71746. Fix IllegalStateException.

---

web/projects/portal/src/app/portal/schedule/schedule-task-list/schedule-task-list.component.ts

Based on conditional checks, block dialog pop-ups to prevent modifying button properties via F12 (DevTools) and subsequent unauthorized operations.

Fix Bug #71748:Based on conditional checks, block dialog pop-ups

---

core/src/main/java/inetsoft/report/internal/Util.java
core/src/main/java/inetsoft/uql/jdbc/util/JDBCUtil.java
core/src/main/java/inetsoft/web/admin/content/repository/DatabaseDatasourcesService.java
web/projects/shared/util/datasource/data-source-settings-page.ts

Hide the password of the `JdbcDatasource` when reopening after saving the datasource.

fix Bug #71753. Avoid directly exposing the datasource password in the response to the frontend.

---

core/src/main/java/inetsoft/uql/util/XNodeTable.java

for XNodeTable, when the base table canceled cause the current table process break, cancel current table.

fix Bug #71763, for XNodeTable, when the base table canceled cause the current table process break, cancel current table.

---

core/src/main/java/inetsoft/report/composition/execution/MirrorQuery.java
core/src/main/java/inetsoft/report/composition/execution/PreAssetQuery.java

If the mirror table has a crosstab structure, it relies on the actual data in the base table to generate the column headers. Therefore, in the subquery of the mirror query, it should not be in the metadata state; otherwise, the conditions set on the base table will not be applied during the execution of the subquery.

fix Bug #71503. Fix the issue where the data displayed in a crosstab-structured mirror table does not apply the conditions from the base table.

---

core/src/main/java/inetsoft/web/portal/data/DataSetService.java
web/projects/portal/src/app/portal/data/data-folder-browser/data-folder-list-view/data-folder-list-view.component.html

The "Edit" button should not be hidden, and the edit option should not be disabled if the user has read permission.

Fix Bug #71773:The "Edit" button should not be hidden.

---

core/src/main/java/inetsoft/web/viewsheet/controller/dialog/EmailDialogController.java

if select "expand components", match layout will be false, then if no expand permission should show uer warning

fix Bug #71772: use match layout to check select expand components or not

---

core/src/main/java/inetsoft/report/script/viewsheet/ViewsheetVSAScriptable.java

should always use absolute name to get sandbox, because it always from root box to get.

fix Bug #71774, should always use absolute name to get sandbox, because it always from root box to get.

---

core/src/main/java/inetsoft/mv/formula/NthMostFrequentFormula.java

return cloned object for NthMostFrequentFormula.

fix Bug #71786, return cloned object for NthMostFrequentFormula.

---

core/src/main/java/inetsoft/web/admin/schedule/ScheduleCycleService.java

Because StyleBI now has organizations, permissions are stored with cycle as name + orgId. Therefore, queries should also be performed based on name + orgId.

Fix Bug #71797:Queries should also be performed based on name + orgId.

---

core/src/main/java/inetsoft/report/composition/execution/ViewsheetSandbox.java

After the sub viewsheets are updated, execute the view for assemblies that use the "thisParameter" script to ensure they can get the parameters from the sub viewsheets.

fix Bug #71812. Fix the issue where assemblies using the "thisParameter" script collect incomplete parameters from sub viewsheets.

---

core/src/main/java/inetsoft/sree/internal/SUtil.java

If a password is set, it should display a placeholder; if not set, it should display null.

Fix Bug #71854:If a password is set, it should display a placeholder; if not set, it should display null.

---

web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/datasources-database.component.ts

should split create new datasource and edit new datasource by different route, if create new datasource it will select listing db names and to edit db page, but edit will to edit db page directly.

Bug #71827: should split createdb and editdb to different check

---

core/src/main/java/inetsoft/web/admin/security/ChangePasswordController.java

should show user name in audit for change password action, only can edit users in current org, so org info should ignore.

Bug #71828: only show user name for change password record

---

web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-query/database-query.component.html
web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-query/database-query.component.ts
web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-query/query-preview/sql-query-preview-pane.component.ts
web/projects/portal/src/app/widget/dialog/sql-query-dialog/simple-query-pane.component.html
web/projects/portal/src/app/widget/dialog/sql-query-dialog/simple-query-pane.component.ts

When switching to the preview pane, if parameter collection is cancelled during the process, return to the previous tab instead of staying on the preview tab.

fix Bug #71873. Go back to the previous tab when the parameter collection dialog is cancelled.

---

web/projects/portal/src/app/vsobjects/viewer-app.component.ts

when emit onViewerSizeChanged event, min width should be mini toolbar width to ensure display well.

fix Bug #71877, when emit onViewerSizeChanged event, min width should be mini toolbar width to ensure display well.

---

core/src/main/java/inetsoft/report/composition/event/AssetEventUtil.java
core/src/main/java/inetsoft/web/composer/ws/dialog/ImportCSVDialogController.java

When uploading the file, the runtime ID in the cache key is normalized, so the same normalization should be applied when touching the file.

fix Bug #71849. Normalize the runtime ID when touching the file.

---

core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
core/src/main/java/inetsoft/uql/service/DataSourceRegistry.java

According to the code analysis, the issue is likely due to limited cloud service resources causing slow response times. When deleting an organization, if someone simultaneously requests resources from that organization may get host org resources.
The solution is to ensure that the AssetEntry used to obtain resources holds the correct orgID. Specifically, when an org user accesses shared global resources, the AssetEntry's orgID should be set to the host organization's ID.

fix Bug #71850, Bug #71859,  fix issue that other org user get host org resource

---

core/src/main/java/inetsoft/web/admin/content/repository/MVService.java

if vs mv has parent vs, change label from parent -> child to "parent" -> "child", because other vs can be renamed to parent -> child, in mv list, it is no way to distinguish.

fix Bug #71898, change label of the mv that has parent vs.

---

web/projects/portal/src/app/portal/dialog/vpm-condition-dialog/vpm-condition-pane/vpm-condition-pane.component.html
web/projects/portal/src/app/portal/dialog/vpm-condition-dialog/vpm-condition-pane/vpm-condition-pane.component.ts

Because the same component is opened twice and their radio buttons have the same name, they are automatically rendered on the first page. Therefore, adding a unique identifier to the name can avoid this issue.

Fix Bug #71884:Add a unique identifier to prevent radio button selection errors.

---

core/src/main/java/inetsoft/web/portal/controller/database/QueryManagerService.java

caused by parseresult be changed when set sqlstring. fix by checking selection column count when create columnselection by uniformsql since column count should larger than 0 if really PARSE_SUCCESS or  PARSE_PARTIALLY

fix Bug #71927, fix not create right columnselection after getting columninfo by sqlstring.

---

core/src/main/java/inetsoft/sree/schedule/ServerPathInfo.java
core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java

Since setServerPaths() already includes a check for passwords with PLACEHOLDER_PASSWORD, there's no need to filter the password field again in new ServerPathInfo(). Additionally, the oldServerPath should be obtained from the scheduleManager.

Fix Bug #71959:Additionally, the oldServerPath should be obtained from the scheduleManager.

---

web/projects/em/src/app/settings/general/email-settings-view/email-settings-view.component.html

Since the dropdown already has a "None" option, the checkbox is redundant and should be removed.

Fix Bug #71962:The checkbox is redundant and should be removed.

---

core/src/main/java/inetsoft/uql/viewsheet/AbstractContainerVSAssembly.java

When removing assemblies, if it's an embedded viewsheet, its assembly name contains "viewsheet.", so it should be truncated before comparison.

Fix Bug #71803:For embedded viewsheets, perform string truncation before comparison.

---

core/src/main/java/inetsoft/sree/schedule/ScheduleTask.java
core/src/main/resources/inetsoft/util/srinter.properties

Modify the email subject when a task fails in Community edition to exclude organization information.

Fix Bug #71945:Modify the email subject when a task fails in Community edition to exclude organization information.

---

core/src/main/java/inetsoft/report/composition/execution/AssetDataCache.java
core/src/main/java/inetsoft/report/composition/execution/AssetQuery.java
core/src/main/java/inetsoft/report/internal/XNodeMetaTable.java

in live mode, if runtime tablelens can not be executed successfully, will create a metadata data, do not put it as a valid data cache.

fix Bug #71861, in live mode, if runtime tablelens can not be executed successfully, will create a metadata data, do not put it as a valid data cache.

---

web/projects/shared/util/date-type-formatter.ts

If the time zone is not set, directly returning 0 means there is no offset.

fix Bug #71999. Fix TypeError: cannot access "minuteOffset" when result is undefined

---

core/src/main/java/inetsoft/sree/internal/cluster/ClusterCache.java

1, do not try to lock when the CusterCache has been closed. 
2, when destroy lock failed, unlock then wait 5s try to destroy again, max try count is 10.

fix Bug #71990, fix server node can not access.

---

web/projects/em/src/app/common/util/editor-panel/editor-panel.component.ts

After clicking the Apply button, it should be immediately disabled to avoid exceptions caused by multiple repeated requests. In the cloud environment, due to slower response times, this issue is easily triggered. Debounce cannot solve this problem, because if the response is slow, repeated clicks on Apply can still send the same request multiple times, and the page will also refresh repeatedly when each request completes. Therefore, the Apply button should be disabled immediately after clicking it.

fix Bug #71975. Avoid sending duplicate requests.

---

web/projects/portal/src/app/graph/objects/chart-axis-area.component.ts
web/projects/portal/src/app/graph/objects/chart-plot-area.component.ts

if tile has no loaded flag should treated as loaded.

fix Bug #72011, fix chart always loading issue.

---

web/projects/portal/src/app/vsobjects/action/selection-list-actions.ts
web/projects/portal/src/app/vsobjects/action/selection-tree-actions.ts

If the selection list/tree is inside a selection container, "Show Enlarged" and "Show Actual Size" are not supported.

fix Bug #72020. Hide "Show Actual Size" action for selection list/tree in a selection container.

---

core/src/main/java/inetsoft/uql/jdbc/UniformSQL.java

for databricks and clickmouse db, it should fix map key for column, clickmouse is fixed on bug71915, so fix the same issue to databricks

Bug #71960: add logic for databricks to fix map key in db, the same as clickmouse

---

core/src/main/java/inetsoft/sree/internal/cluster/ClusterCache.java

for ignite waring "Unordered map java.util.HashMap is used for putAll operation on cache DatabaseSecurityCache:db.organizationName. This can lead to a distributed deadlock. Switch to a sorted map like TreeMap instead." use tree map to replace the hashmap.

fix Bug #72025, fix ignite waring.

---

core/src/main/java/inetsoft/web/viewsheet/model/VSSelectionBaseModel.java

for adhoc filter, it should always show in client, but its show type maybe dropdown in container. So just show in client for adhoc filter. Do not change its server show type for, it should keep show/hide in container after apply adhoc filter.

Bug #71333: should always show adhoc filter in client.

---

core/src/main/java/inetsoft/web/admin/content/repository/ResourcePermissionService.java

Because if this method is called internally within the same class (rather than through the Spring proxy object), AOP will not take effect. Therefore, the aspect needs to be added to the method that is directly called by the Spring proxy.

Fix Bug #72013: The aspect needs to be added to the method that is directly called by the Spring proxy.

---

core/src/main/java/inetsoft/web/portal/controller/HomePageController.java

when do not define default theme for organization, its theme in organzation property can not apply. Because it also used customeTheme, so we should set CustomTheme to true when set org theme by property pane.

Bug #72033: when organization set custom theme, should set customTheme to true

---

core/src/main/antlr/inetsoft/uql/util/sqlparser/SQLParser.g
core/src/main/java/inetsoft/util/Tool.java

for oracle, should not convert the table or column name to uppercase when it is quoted, because quoted column or table name is case-sensitive.

fix Bug #71987, fix parsed sql can not execute for oracle.

---

core/src/main/java/inetsoft/util/Debouncer.java
core/src/main/java/inetsoft/util/DefaultDebouncer.java
core/src/main/java/inetsoft/web/composer/ComposerDisconnectListener.java
core/src/main/java/inetsoft/web/viewsheet/service/RuntimeViewsheetManager.java
web/projects/portal/src/app/common/test/test-utils.ts
web/projects/portal/src/app/common/viewsheet-client/viewsheet-client.service.ts
web/projects/portal/src/app/embed/viewer/embed-viewer.component.html
web/projects/portal/src/app/embed/viewer/embed-viewer.component.ts
web/projects/shared/stomp/stomp-client.service.ts
web/projects/shared/stomp/stomp-client.ts

Allow the web socket to reconnect. Don't close the viewsheets right away. 
On error just hide the viewer-app instead of destroying it as that doesn't allow the web socket to reconnect and would require the page to be reloaded.

Merge forward fix for Bug #71869 - web socket reconnect

---

core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java
core/src/main/java/inetsoft/util/ImageHashService.java
core/src/main/java/inetsoft/web/viewsheet/controller/AssemblyImageService.java
core/src/main/java/inetsoft/web/viewsheet/controller/GetImageController.java
core/src/main/java/inetsoft/web/viewsheet/model/VSImageModel.java
web/projects/portal/src/app/common/test/test-utils.ts
web/projects/portal/src/app/vsobjects/model/output/vs-image-model.ts
web/projects/portal/src/app/vsobjects/objects/output/image/vs-image.component.html
web/projects/portal/src/app/vsobjects/objects/output/image/vs-image.component.ts

Create a hash for an image and then retrieve the image using the hash. Make sure that the browser caches the image response so that subsequent requests just retrieve the image from the browser cache.

Merge forward fix for Bug #71924 - cache images

---

core/src/main/java/inetsoft/uql/asset/AssetEntry.java
core/src/main/java/inetsoft/web/admin/viewsheet/ViewsheetModel.java

add "(Shared Host Global Scope) " prefix for sheet name of the shared host vs when create ViewsheetModel, to distingush viewsheets from organization and the host, to avoid users mistakenly thinking they have seen monitor data  of  other organizations.
To minimize the impact of changes, only handle them in ViewsheetModel instead of directly modifying AssetEntry. getSheetName, because when calling AssetEntry. getSheetName, we are unsure if we have set the orgid for threadlocal.

fix Bug #72071, distingush viewsheets from organization and the host

---

web/projects/portal/src/app/vsobjects/objects/mini-toolbar/mini-toolbar.component.ts

When the mini toolbar is used as a popup component, its position is calculated within the `VSPopComponentDirective`, so it should not be affected by the `topY` calculation logic in `MiniToolbar`.

fix Bug #72087. Fix mini toolbar position change caused by search icon click.

---

core/src/main/java/inetsoft/uql/jdbc/JDBCHandler.java
core/src/main/java/inetsoft/uql/viewsheet/internal/RangeCondition.java

the bug is only exist for single binding, composite binding will change date to java.sql.Date when dataType of ref is "date", so just do the same issue for single binding. Should change condition value to java.sql.Date when create range condition, so it can split date and dateTime in JDBCHandler.execute.
for clickHouse db, date and dateTime should split to fix.
test for date type and dateTime type for clickHouse and normal db, they all works right.

Bug #72072: fix date binding for range slider

---

web/projects/portal/src/app/vsobjects/objects/data-tip/data-tip.service.ts
web/projects/portal/src/app/vsobjects/objects/data-tip/pop-component.service.ts
web/projects/portal/src/app/vsobjects/objects/vs-object-container.component.ts

Fix the issue where the embedded viewsheet's gray overlay layer has an incorrect state due to failure to promptly detect the visibility status of the popup or datatip components.

fix Bug #72086. Fix incorrect gray overlay state in embedded viewsheet.

---

core/src/main/java/inetsoft/web/composer/vs/objects/controller/ComposerGroupController.java

When creating a group, it should be ensured that the children within the current group (or indirectly contained tabs) are excluded from each other. Therefore, when adding childrenName, such cases should be explicitly filtered out. Otherwise, it may lead to an infinite loop.

Fix Bug #72108: It should be ensured that the children within the current group (or indirectly contained tabs) are excluded from each other

---

web/projects/em/src/app/app.module.ts
web/projects/em/src/app/custom-route-reuse-strategy.ts
web/projects/em/src/app/page-header/page-header.component.ts

Implement a custom RouteReuseStrategy to avoid route reuse on the next navigation. This prevents the page from not refreshing when re-routing to the current page due to organization changes caused by route reuse.

fix Bug #72104. Fix the issue of the page not refreshing due to route reuse.

---

core/src/main/java/inetsoft/web/GlobalStyleController.java

When applying a theme, if the organization's stored theme has been deleted from the manager, the default theme should be used instead.

Fix Bug #72129:Use default theme if org's theme is missing in manager.

---

core/src/main/java/inetsoft/sree/internal/cluster/ClusterCache.java

Add catch for ClusterTopologyCheckedException to prevent breaking processTasks() when cluster is unstable

Bug #72066

---

web/projects/portal/src/app/binding/editor/chart/field/chart-fieldmc.component.html

increase the z-index of chart fieldmc drop down, because chart z-index will increase by 100,000 in max mode.

fix Bug #72162, increase the z-index of chart fieldmc drop down, because chart z-index will increase by 100,000 in max mode.

---

core/src/main/java/inetsoft/web/portal/controller/database/QueryManagerService.java

should create ExpressionRef for expression field to avoid quote the expression field as normal field when expression field contains keyword(see SQLHelper.generateSelectClause line1310).

fix Bug #72178, don't quote expression column.

---

core/src/main/java/inetsoft/uql/jdbc/util/JDBCUtil.java

sync expression status to avoid quote expression field.(see SQLHelper.generateSelectClause line1310).

fix Bug #72178, sync expression status to avoid quote expression field.

---

web/projects/portal/src/app/vsobjects/action/chart-actions.ts

The actionin annotationsdoes not require Reset Size, so it should not be added when creating the action.

Fix Bug #72090:The actionin annotationsdoes not require Reset Size, so it should not be added when creating the action.

---

core/src/main/java/inetsoft/sree/internal/cluster/ignite/IgniteCluster.java
core/src/main/java/inetsoft/sree/internal/cluster/ignite/IgniteDistributedMap.java
core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCache.java

1, replace Identity[] type with IdentityArrayWrapper for ignite cache, Identity[] will be deserialized as Object[], causing a ClassCastException 
2, create ignite cache can not in transaction, remove it. 
3, clear method of ignite cache can not call in transaction, replace with removeAll.

fix Bug #72187, fix ignite cache error.

---

core/src/main/java/inetsoft/sree/security/ldap/LdapAuthenticationCache.java

for LDAP provider cache, clear method of ignite cache can not call in transaction, replace with removeAll.

for LDAP provider cache, clear method of ignite cache can not call in transaction, replace with removeAll.

---

core/src/main/java/inetsoft/uql/jdbc/DatabricksHelper.java

for Databricks, "default" should not the keyword, the same as clickmouse

fix Bug #72188:for Databricks, "default" should not the keyword, the same as clickmouse

---

core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCache.java

to avoid deadlock during refresh the database provider cache, if refresh service owner is current server node then Directly invoke the task.

fix Bug #72192,fix deadlock during refresh the database provider cache.

---

core/src/main/java/inetsoft/report/io/viewsheet/AbstractVSExporter.java

the bug is caused by when expand table in vs, it use default row height(20 pixel) to calculate its expand height, but the actual row height is 18, so its table will have some empty lines on the bottom. In fact, we should get row height from tablelens, the same as write table cell row.
old bug, 13.6 is also have the same bug.

fix Bug #72198: use right row height to expand table when export

---

core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCacheServiceImp.java
core/src/main/java/inetsoft/web/admin/security/user/SecurityTreeServer.java

1. don't pop up no org warning for non multitenat.
2. break deadlock 
"http-nio-8080-exec-10@24364" tid=0x10d nid=NA waiting
java.lang.Thread.State: WAITING
at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
at org.apache.ignite.internal.util.future.GridFutureAdapter.get0(GridFutureAdapter.java:181)
at org.apache.ignite.internal.util.future.GridFutureAdapter.get(GridFutureAdapter.java:144)
at org.apache.ignite.internal.AsyncSupportAdapter.saveOrGet(AsyncSupportAdapter.java:109)
at org.apache.ignite.internal.IgniteServicesImpl.deployAll(IgniteServicesImpl.java:245)
at org.apache.ignite.internal.IgniteServicesImpl.deploy(IgniteServicesImpl.java:228)
at inetsoft.sree.internal.cluster.ignite.IgniteCluster.getSingletonService(Ig …

fix Bug #72223, break deadlock

---

core/src/main/java/inetsoft/sree/security/ldap/LdapAuthenticationCache.java

to avoid deadlock during refresh the ldap provider cache, if refresh service owner is current server node then Directly invoke the task.

fix Bug #72221, fix deadlock  for ldap privoder refresh cache.

---

core/src/main/java/inetsoft/util/Plugins.java

should delete plugin file after reset db provider connection, because provider is used plugin.

fix Bug #72225, should delete plugin file after reset db provider connection, because provider is used plugin.

---

core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCache.java
core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCacheServiceImp.java

Don't call the init(), cancel(), execute() methods directly. They are for internal use by Ignite to manage the services lifecycle when it is deployed and undeployed.
I put a stack trace in the init() method and verified that it was called at server startup as expected and was able to log into the EM with a database user.
```
java.lang.Exception: Stack trace
at java.base/java.lang.Thread.dumpStack(Thread.java:2210)
at inetsoft.sree.security.db.DatabaseAuthenticationCacheServiceImp.init(DatabaseAuthenticationCacheServiceImp.java:88)
at org.apache.ignite.services.Service.init(Service.java:158)
at org.apache.ignite.internal.processors.service.IgniteServiceProcessor.redeploy(IgniteServiceProcessor.java:1327)
at org.apache.ignite.internal.processors.service.ServiceDeploymentTask.lambda$processDe …
```

Bug 72220 don't call Ignite service internal methods directly.

---

web/projects/portal/src/app/binding/editor/chart/field/chart-fieldmc.component.html

Roll back the changes of #72162, as the z-index of embedded in the binding pane has already been reduced, so there is no longer a need to modify the z-index of dropdownMenu separately, otherwise it will override the dialog.

Fix Bug #72207:Revert #72162 - dropdownMenu z-index change redundant (binding pane's embedded z-index already fixed), prevents dialog overlap.

---

core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCacheServiceImp.java

By reading the source code of IgniteServiceProcessor, the scenarios that trigger Service.cancel include: undeploy, redeploy, onKernalStop, and onDeActivate processor. Therefore, I think it might be better to destroy the distributed map when disconnecting the service, also should perform clientCount.decrementAndGet() in the cancel function.

 fix Bug #72234, reset counter and destroy necesarry distributed map.

---

core/src/main/java/inetsoft/web/portal/controller/database/DataSourceService.java

When determining whether the dataSource in the old meta is the same as the new dataSource, it should be based on fullName, because fullName includes the folder name, to avoid still fetching the old meta after renaming the folder.

Fix Bug #71469:Use fullNameinstead of name.

---

core/src/main/java/inetsoft/report/io/viewsheet/AbstractVSExporter.java

get correct table expand row count, now export use real row height not AssetUtil.defh.

fix Bug #72198, get correct table expand row count, now export use real row height not AssetUtil.defh.

---

core/src/main/java/inetsoft/web/viewsheet/service/VSExportService.java

should not localize the bookmark name when export, after localize make the bookmark not find in bookmark list and will export null image

fix Bug #72242: should not add localize for bookmark name when filter bookmark

---

core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleControllerService.java
core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java

Don't send SetRuntimeIdCommand after handleOpenSheet, breaks SetPermissionsCommand and is extraneous because call occurs in handleOpenSheet

Bug #72280,

---

core/src/main/java/inetsoft/report/composition/execution/AssetQuerySandbox.java
core/src/main/java/inetsoft/report/composition/execution/ViewsheetSandbox.java
core/src/main/java/inetsoft/report/script/viewsheet/ViewsheetVSAScriptable.java
core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java
core/src/main/java/inetsoft/web/viewsheet/controller/OnClickController.java

Add a script function to refresh a dashboard.
Make sure that data in script also uses fresh data on refresh. Use the touch timestamp of the viewsheet sandbox when available such as when executing script in viewsheets. Don't show the loading mask when using the script refresh function so that it doesn't appear as if the entire viewsheet is loading.

Merge forward Bug #72270 - dashboard refresh script function

---

core/src/main/java/inetsoft/sree/web/dashboard/DashboardManager.java

Bug #70778 has changed Anonymous user Identity type to User for the Dashboard, so should use user type for Anonymous user during get Dashboards.

fix Bug #72380, fix enable dashboard error.

---

core/src/main/java/inetsoft/web/portal/controller/database/PhysicalModelManagerService.java

the bug is caused by the RuntimeXPartition will save before add table, so when fixTableBounds it will not get tables and popup null point exception. So after addtable to RuntimeXPartition, we should save it. Then fixTableBounds will get latest tables and works well(it will get runtime partition by runtimePartitionService.getRuntimePartition(runtimeId)).

fix Bug #72321: should save runtimePartition after addTable

---

core/src/main/java/inetsoft/web/viewsheet/service/VSBookmarkService.java

Because the value of currBookmark is the currently opened bookmark, if it is not opened, it will be null, which may cause a NullPointerException. Therefore, it is necessary to add null checks to prevent NPE.

Fix Bug #72361:

---

core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java
core/src/main/java/inetsoft/web/portal/controller/PortalController.java

During SSO login, the principal may be null, so pId would also be null. Therefore, retrieving the Alias based on pId would trigger a NullPointerException (NPE). Adding null checks can prevent the NPE.

Bug 72362: Adding null checks can prevent the NPE.

---

core/src/main/java/inetsoft/uql/jdbc/JDBCQuery.java

should fixed XTrinaryCondition to get right types from column when XTrinaryCondition is in XSet, if not in XSet, it is already fixed.

fix Bug #72275: fix XTrinaryCondition when it is in XSet to get right types

---

core/src/main/java/inetsoft/web/viewsheet/event/calendar/CalendarSelectionEvent.java

for calendar, the getCurrentDate2 should be nullable because user can only select currentDate1

fix Bug #72396: the getCurrentDate2 should be nullable because user can only select currentDate1

---

core/src/main/java/inetsoft/report/script/formula/CachedRowSelector.java
core/src/main/java/inetsoft/report/script/formula/CrosstabGroupSelector.java
core/src/main/java/inetsoft/report/script/formula/FormulaFunctions.java
core/src/main/java/inetsoft/report/script/formula/NamedCellRange.java
core/src/main/java/inetsoft/report/script/formula/RangeSelector.java

Don't use a class level lock. Lock on the selector key to allow other threads with other tables to proceed.

Merge forward changes for Bug #72356 - selector locking

---

core/src/main/java/inetsoft/web/viewsheet/controller/TouchAssetController.java

Check for null before call to proxied touchAsset to prevent stale call to touch deleted asset from throwing error

Bug #72391

---

web/projects/em/src/app/settings/content/repository/dashboard/repository-dashboard-settings-view/repository-dashboard-settings-view.component.ts

Since this component directly assigns values based on the model, the oldModel should be reassigned after clicking "Apply". Otherwise, the oldModel will remain the initially opened model, which affects the disabling of the "Apply" button.

Bug 72438: Apply Button Enable Logic Fix

---

core/src/main/java/inetsoft/sree/ClientInfo.java

should clone user's login user when clone client info, so it can check  user login to get right result

fix Bug #72458: should clone user's login user when clone client info

---

core/src/main/java/inetsoft/web/composer/vs/objects/controller/ComposerAdhocFilterService.java

set correct z-index for the adhoc filter when the target assembly is max mode.

fix Bug #72434, set correct z-index for the adhoc filter when the target assembly is max mode.

---

core/src/main/java/inetsoft/mv/MVDef.java
core/src/main/java/inetsoft/web/admin/content/repository/MVController.java
core/src/main/java/inetsoft/web/admin/content/repository/MVService.java
core/src/main/java/inetsoft/web/admin/content/repository/MVSupportService.java
core/src/main/java/inetsoft/web/admin/content/repository/model/AnalyzeMVResponse.java
core/src/main/java/inetsoft/web/portal/controller/PortalMVController.java
web/projects/em/src/app/settings/content/materialized-views/mv-management-view/mv-management-view.component.ts
web/projects/em/src/app/settings/content/repository/analyze-mv-page/analyze-mv-page.component.ts
web/projects/portal/src/app/portal/dialog/analyze-mv/analyze-mv-dialog.component.ts
web/projects/shared/util/model/mv/analyze-mv-response.ts

Don't store MV analysis in a session attribute. Add it to a distributed map instead and pass an analysis identifier to retrieve it. Reverted the changes for restoring MVContainer. Just make it serializable and there is no need for this additional logic.

Bug #72503 - don't store MV analysis in a session attribute

---

core/src/main/java/inetsoft/report/lib/logical/AbstractLogicalLibrary.java
core/src/main/java/inetsoft/report/lib/logical/ScriptLogicalLibrary.java
core/src/main/java/inetsoft/report/lib/logical/TableStyleFolderLogicalLibrary.java
core/src/main/java/inetsoft/report/lib/logical/TableStyleLogicalLibrary.java

1, add lock to load lib assets logic to ensure nodes data are consistent.
2, lower the lock level, make it scope is org.

Bug 72524, fix assset tree refresh error after change an asset name.

---

core/src/main/java/inetsoft/mv/data/DetailMergedTableBlock.java
core/src/main/java/inetsoft/mv/data/MergedTableBlock.java

fix tablelens serialize error after crete mv. make  MergedTableBlock is Serializable and ignore MVQuery, because MVQuery just use during execute.

Bug #72574, fix open mv vs error.

---

core/src/main/java/inetsoft/report/composition/RuntimeWorksheet.java

need not to init the AssetQuerySandbox if the entry of RuntimeWorksheet is null. just joinWs entry is null.

Bug #72636, fix npe during edit ws join.

---

core/src/main/java/inetsoft/web/security/AbstractLogoutFilter.java
core/src/main/java/inetsoft/web/security/AbstractSecurityFilter.java
core/src/main/java/inetsoft/web/security/InvalidateSessionFilter.java

Make sure that the session is released on sso logout and redirected properly when using the portal.logout.url property.
Fix session invalidation issues due to client info mismatch when SSO is enabled.
Ensure that the client info in the Principal object matches the users map in SecurityEngine to prevent sessions from being invalidated immediately and to allow proper session cleanup.

Bug #72455 - fix session handling when SSO is enabled

---

core/src/main/java/inetsoft/web/admin/content/repository/MVService.java

should not add Identity Type to localized, for it will create MaterializedViewUser by it, then it will throw error to do not find type. should using type not localized and it will works right.
the bug exist on main branch and session branch, so just commit it to main

Bug #72670: should not localize identity type for mv

---

core/src/main/java/inetsoft/analytic/composition/event/VSEventUtil.java

Currently, the variable table is cleared after we get the parameters.
This means that the execution will only get a list of variables that exist, but are not defined yet in the variable table.
This list of parameters is prompted and inserted in to the empty variable table later on, but the variables that were originally in the table never get prompted, until it is reset again.

Bug #72692  When resetting parameters, clear the variable table before getting parameters

---

core/src/main/java/inetsoft/uql/viewsheet/Viewsheet.java

Revert to check when AbstractVSAssembly, otherwise getScriptDependings() skips assemblies with scripts relating to change

Bug #72673

---

core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java

Before the stateless session changes, the runtime viewsheet id was determined solely if fullScreenId was defined.
So before, this section of code had an condition block checking if the rvsId was null.
Now, the id always needs to be defined since this is inside a proxied method and the condition block was removed.
However, this particular logic should still only execute if fullScreenId is defined.

Bug #72708  Do not use the runtime viewsheet's init var table if fullScreenId is null
