- README.md
added a link to full Docs, will probably need to update URL
> Update README.md with Doc link

- core/src/main/java/inetsoft/web/viewsheet/service/PlaceholderService.java
Load tables in lock on viewsheet open to prevent race conditions
> Merge forward changes for Bug #70029

- core/src/main/java/inetsoft/report/script/formula/FormulaFunctions.java
merge changes of Bug #69913 to 14.0, custom case, fix "null" as null
> fix Bug #70043:

- core/src/main/java/inetsoft/web/composer/vs/dialog/HighlightDialogController.java
using Tool.equals when compare two strings to avoid null point exception
> fix Bug #70071:

- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/youtubeanalytics/endpoints.json
- web/projects/portal/src/app/widget/tabular/tabular-rest-parameters-editor.component.scss
1. show the placeholder for the tabular rest query parameter. 
2. for Channel id parameter, change the "id of youtube channel" label to "id" and change to placeholder from "channel==MINE" to "channel==CHANNEL ID Or contentOwner==OWNER NAME"
> Bug #70034

- web/projects/portal/src/app/binding/editor/chart/aesthetic/aesthetic-pane.component.html
input the assetId for the field-mc component to avoid the NPE.
> Bug #70067

- core/src/main/java/inetsoft/uql/erm/AbstractModelTrapContext.java
the bug is caused by when check model trap for worksheet table, it do not add ranking condition fields to check trap, should fix ranking conditon the same as pre condition list and post condition list.
> fix Bug #70080:

- core/src/main/java/inetsoft/uql/viewsheet/Viewsheet.java
The case imported into the current organization should have all its information converted to match the current organization, and the base entry should also be updated to reflect the current organization.
> Fix Bug #70047:

- core/src/main/java/inetsoft/sree/security/AuthenticationService.java
- core/src/main/java/inetsoft/sree/security/LocaleService.java
1,If the user's locale and the organization's locale are both set to default, use the user's client locale as the primary locale and apply localization based on it. 
2,update principal locale for the Google SSO user.
> fix Bug #70091, Bug #70089,

- core/src/main/java/inetsoft/util/migrate/MigrateWorksheetTask.java
fix Bug #70107, sync org id when import ws.
> fix Bug #70107, sync org id when import ws.

- connectors/inetsoft-googledoc/src/main/java/inetsoft/uql/gdata/GDataDataSource.java
- connectors/inetsoft-googledoc/src/main/java/inetsoft/uql/gdata/GDataQuery.java
- connectors/inetsoft-googledoc/src/main/java/inetsoft/uql/gdata/GDataRequestInitializer.java
- connectors/inetsoft-googledoc/src/main/java/inetsoft/uql/gdata/GDataRuntime.java
- core/src/main/java/inetsoft/uql/tabular/GoogleFile.java
- core/src/main/java/inetsoft/uql/tabular/GooglePicker.java
- core/src/main/java/inetsoft/uql/tabular/TabularEditor.java
- core/src/main/java/inetsoft/uql/tabular/TabularUtil.java
- web/package-lock.json
- web/package.json
- web/projects/portal/src/app/common/data/tabular/google-picker.ts
- web/projects/portal/src/app/widget/tabular/google-picker/google-picker.service.ts
- web/projects/portal/src/app/widget/tabular/google-picker/tabular-google-picker-editor.component.html
- web/projects/portal/src/app/widget/tabular/google-picker/tabular-google-picker-editor.component.scss
- web/projects/portal/src/app/widget/tabular/google-picker/tabular-google-picker-editor.component.ts
- web/projects/portal/src/app/widget/tabular/tabular-view.component.html
- web/projects/portal/src/app/widget/tabular/tabular.module.ts
- web/projects/portal/src/scss/internal/_layout.scss
- web/projects/portal/tsconfig.app.json
Migrate the google spreadsheets data source to google picker api
> Bug #69950 Migrate the google spreadsheets data source to google picker api

- core/src/main/java/inetsoft/util/migrate/MigrateWorksheetTask.java
code review, sync org id when clone org.
> code review, sync org id when clone org.

- core/src/main/java/inetsoft/web/viewsheet/service/VSBookmarkService.java
fix simple scheduler show for shared dashboard, but warning is wrong
> Bug #70136

- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/json/RestJsonQuery.java
- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/pagination/AbstractParameterParser.java
- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/pagination/HttpResponseParameterParser.java
- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/pagination/PagedIterationIteratorStrategy.java
- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/pagination/ParameterParser.java
- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/pagination/PathParameterParser.java
- connectors/inetsoft-rest/src/test/java/inetsoft/uql/rest/json/PagedIterationIteratorStrategyTest.java
Support JSON Path for page offset parameter to write in the iteration strategy
> Merge forward Bug #70124 - Support JSON Path for page offset parameter in the iteration strategy

- core/src/main/java/inetsoft/web/viewsheet/service/VSEmailService.java
Prohibit the display of the org name in the email subject format.
> Bug #70159

- web/projects/em/src/app/settings/schedule/schedule-task-list/schedule-task-list.component.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-list/schedule-task-list.component.ts
when no time for next run, should show "" in schedule list
> fix Bug #70169:

- core/src/main/java/inetsoft/uql/viewsheet/internal/VSAssemblyInfo.java
Check hyperlink orgid against asset orgid when reading in link path
> Bug #70193

- core/src/main/java/inetsoft/web/portal/controller/RepositoryTreeSearchController.java
fix Bug #70157, add defaultOrgAsset flag for replet folder.
> fix Bug #70157, add defaultOrgAsset flag for replet folder.

- core/src/main/java/inetsoft/sree/schedule/ScheduleTask.java
should clone time zone when clone task options.
> fix Bug #70208:

- core/src/main/java/inetsoft/web/admin/content/repository/MVService.java
- core/src/main/java/inetsoft/web/admin/content/repository/model/MVManagementModel.java
- web/projects/em/src/app/settings/content/materialized-views/mv-management-view/mv-management-model.ts
- web/projects/em/src/app/settings/content/materialized-views/mv-management-view/mv-management-view.component.ts
for mv list, should add date format to client, and using lastModifiedTimestamp to calculate time according its local timezone to show in mv list.
> fix Bug #70170:

- core/src/main/java/inetsoft/uql/DrillPath.java
- core/src/main/java/inetsoft/uql/DrillSubQuery.java
ensure current organization when reading in drill data
> Bug #70194

- core/src/main/java/inetsoft/uql/asset/internal/MirrorAssemblyImpl.java
ensure current organization when reading in mirror ws reference
> Bug #70188

- core/src/main/java/inetsoft/sree/PropertiesEngine.java
- core/src/main/java/inetsoft/uql/jdbc/SQLHelper.java
apply the log properties after them are changed. before save changed properties the changeListener will be removed, so can not the apply the log config modification.
> fix Bug #70177

- core/src/main/java/inetsoft/util/dep/ViewsheetAsset.java
When exporting, handle the dependencies of the script within the "edit calcFields" section.
> Bug #70134

- web/projects/portal/src/app/portal/schedule/schedule-task-editor/options/task-options-pane.component.html
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/options/task-options-pane.component.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-editor.component.html
support add time zone option for portal schedule task option
> fix Bug #70216:

- core/src/main/java/inetsoft/web/admin/content/repository/MVSupportService.java
Pass org admin user id to MV config Users when only one user with org admin role, pass org admin role when multiple
> Bug #70184

- core/src/main/java/inetsoft/sree/security/Permission.java
- core/src/main/java/inetsoft/sree/security/PermissionChecker.java
pass identity organization when checking permissions
> Bug #70222

- web/projects/portal/src/app/vsobjects/bookmark/vs-bookmark-pane.component.ts
do not show set default bookmark for globally visible viewsheets
> Bug #70221

- core/src/main/java/inetsoft/report/composition/RuntimeSheet.java
- core/src/main/java/inetsoft/web/admin/properties/PropertiesController.java
Force reload RuntimeSheet maxIdle when asset.max.idle is changed
> Bug #70225

- core/src/main/java/inetsoft/mv/VSMVAnalyzer.java
- web/projects/portal/src/app/widget/dialog/message-dialog/message-dialog.component.scss
For overly long strings, a line break identifier should be added in the middle to ensure normal display on the UI.
> Bug #70168

- core/src/main/java/inetsoft/web/portal/data/DataSetService.java
when user have alias, the ws should use alias not user name.
> Fix Bug #70158:

- core/src/main/java/inetsoft/web/portal/controller/LoginController.java
correct parse the requestedUrl after login by the Google SSO.
> fix Bug #70246

- core/src/main/java/inetsoft/web/admin/cache/CacheManagerController.java
- core/src/main/java/inetsoft/web/admin/cache/CacheManagerMBean.java
- core/src/main/java/inetsoft/web/admin/cache/CacheService.java
remove codes for reports because we do not support report in stylebi. the properties are set for report cache size.
> fix Bug #70218:

- web/projects/em/src/app/settings/security/users/users-settings-page/users-settings-page.component.ts
Display a loading page during the process of renaming a user.
> fix Bug #70108. 

- web/projects/portal/src/app/portal/schedule/schedule-task-list/schedule-task-list.component.ts
using getLocalTime to fix date as local time zone
> fix Bug #70249:

- core/src/main/java/inetsoft/web/portal/controller/PortalProfileController.java
- web/projects/portal/src/app/vsobjects/dialog/profiling-dialog.component.ts
It is required to modify the time to the client's local time, and the dayjs(value) method will be called on the frontend to perform timezone conversion.
> Fix Bug #70171:

- core/src/main/java/inetsoft/web/composer/model/vs/TableAdvancedPaneModel.java
- core/src/main/resources/inetsoft/report/defaults.properties
fix Bug #70197, remove useless attribute.
fix Bug #70210, remove property "schedule.task.file" which is used for BC issue.
> remove useless code.

- core/src/main/java/inetsoft/sree/schedule/jobstore/ClusterJobStore.java
Due to the missing `principal` in `ThreadContext`, the `EmbeddedTableStorage.getStorage()` method fails to obtain the correct organization ID, resulting in an exception.
> fix Bug #70166.

- core/src/main/java/inetsoft/sree/internal/HTMLUtil.java
remove codes for “html.directory" property, it is used for Report
> fix Bug #70218：

- core/src/main/java/inetsoft/web/viewsheet/service/VSInputService.java
merge changes of Bug #69985 from 13.8 to 14.0
> fix Bug #70263：

- core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
Fail asset permission if non site admin attempts to access another's private repo
> Bug #70234

- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleTaskController.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
- core/src/main/java/inetsoft/web/portal/controller/ScheduleTaskController.java
- web/projects/em/src/app/settings/schedule/schedule-task-list/schedule-task-list.component.ts
- web/projects/portal/src/app/portal/schedule/schedule-save.guard.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.component.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-dialog.component.html
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-editor.component.html
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-editor.component.ts
- web/projects/shared/schedule/model/task-condition-pane-model.ts
In the portal scheduler, apply the "schedule.condition.taskDefaultTime" property when adding conditions to an existing task.
Also cleaned up references to the property in the backend.
> Bug #70147  Fix issues with the "schedule.condition.taskDefaultTime" in the portal scheduler

- core/src/main/java/inetsoft/sree/internal/DataCycleManager.java
- core/src/main/java/inetsoft/sree/schedule/cloudrunner/CloudRunner.java
Use organization to distinguish pregenerated tasks, and only generate tasks for the affected organizations.
> fix Bug #70204. 

- core/src/main/java/inetsoft/web/admin/deploy/DeployService.java
Caused by Bug #69597, the condition for determining SecurityEnabled must be checked.
> Fix Bug #70303:

- core/src/main/java/inetsoft/web/viewsheet/service/VSExportService.java
- core/src/main/resources/inetsoft/util/srinter.properties
handle passing correct assetEntry when export globally visible asset by url
> Bug #70232

- web/projects/portal/src/app/widget/repository-tree/repository-tree.component.ts
Pass globally visible asset flag when iterating through nodes based on path
> Bug #70272

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
logout principals after deleting user.
> fix Bug #70286, logout principals after deleting user.

- core/src/main/java/inetsoft/report/composition/RuntimeSheet.java
- core/src/main/java/inetsoft/report/internal/table/TableFormat.java
- core/src/main/java/inetsoft/sree/PropertiesEngine.java
- core/src/main/java/inetsoft/util/Tool.java
- core/src/main/java/inetsoft/web/MapSession.java
- core/src/main/java/inetsoft/web/MapSessionRepository.java
- core/src/main/java/inetsoft/web/admin/properties/PropertiesController.java
allow runtime changes to properties to take effect immediately, add handling to propagate to all nodes in clustered environment
> Bug 70230, Bug #70225, Bug #70129

- core/src/main/java/inetsoft/report/internal/Common.java
- core/src/main/java/inetsoft/report/internal/Gop.java
- core/src/main/java/inetsoft/report/internal/j2d/Gop2D.java
- core/src/main/resources/inetsoft/report/defaults.properties
clean up outdated properties. rename stylereport.ditherImage to Graphics.Image.ScaleSmooth to better align with functionality
> Bug #70227

- core/src/main/java/inetsoft/sree/portal/CustomTheme.java
- core/src/main/java/inetsoft/sree/portal/CustomThemesManager.java
- core/src/main/java/inetsoft/web/admin/content/dataspace/DataSpaceContentSettingsService.java
Reload the custom themes after deleting a theme JAR from storage.
> fix Bug #70292.

- core/src/main/java/inetsoft/web/composer/ws/dialog/ImportCSVDialogController.java
the bug is caused by  do some csv file with wrong data so it can not read right data for dataTable, so should show right warning for user.
> fix Bug #70289:

- core/src/main/java/inetsoft/report/io/viewsheet/pdf/PDFVSExporter.java
- core/src/main/java/inetsoft/uql/viewsheet/internal/VsToReportConverter.java
Retrieve svg files of SERVER_IMAGE type from storage instead of from the viewsheet.
> fix Bug #70356.

- core/src/main/java/inetsoft/analytic/composition/SheetLibraryEngine.java
Roll back the changes of #67236, which affect the autoSave prompt, and revise them again.
> Fix Bug #70328:

- core/src/main/java/inetsoft/sree/RepletEngine.java
When renaming a folder, update the MVs of the entries within the folder.
> fix Bug #70346.

- core/src/main/java/inetsoft/sree/internal/DeployManagerService.java
when import auto save asset, audit should only show user and vs name, type will show in record type in recod page.
> fix Bug #70381:

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
fix Bug #70286, invalidate http sessions after user was deleted.
> invalidate http sessions after user was deleted.

- core/src/main/java/inetsoft/web/viewsheet/service/VSEmailService.java
email asset link should be "shared_global" for the gl obal share asset to ensure link can be opened correctly.
> fix Bug #70350

- core/src/main/java/inetsoft/sree/internal/SUtil.java
- core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java
check global vs visible, should use the org id of current use to replace the current org id.
> fix Bug #70319

- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/AbstractRestRuntime.java
- core/src/main/java/inetsoft/uql/asset/TabularTableAssembly.java
- core/src/main/java/inetsoft/uql/tabular/TabularQuery.java
- core/src/main/java/inetsoft/uql/tabular/TabularRuntime.java
- core/src/main/java/inetsoft/uql/tabular/impl/TabularHandler.java
Remove the restriction that made variables required to be set to execute a tabular query. Fill null variables with empty string for REST data sources.
> Merge forward Bug #70311 - make tabular params optional

- core/src/main/java/inetsoft/web/portal/controller/RepositoryTreeController.java
check isVisible for globally visible assets too
> Bug #70369

- core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
Filter out nonexistent organizations when parsing bookmark users
> Bug #70379

- core/src/main/java/inetsoft/sree/internal/SUtil.java
Check each path subsection for folder alias when localizing
> Bug #70386

- core/src/main/java/inetsoft/sree/security/AuthenticationProvider.java
only return true for active user when checking anonymous user
> Bug #70278

- web/projects/portal/src/app/widget/asset-tree/asset-tree.component.ts
When saving a sheet using "Sign Up User," the private dashboard should be selected by default.
> Fix Bug #67236:

- core/src/main/java/inetsoft/web/admin/content/repository/RepositoryViewsheetController.java
- core/src/main/java/inetsoft/web/admin/content/repository/RepositoryWorksheetController.java
- core/src/main/java/inetsoft/web/admin/content/repository/SheetService.java
- web/projects/em/src/app/settings/content/repository/content-repository-page/content-repository.service.ts
- web/projects/em/src/app/settings/content/repository/repository-viewsheet-settings-page/repository-viewsheet-settings-page.component.ts
- web/projects/em/src/app/settings/content/repository/repository-worksheet-settings-page/repository-worksheet-settings-page.component.ts
Format the date using the user's client time zone.
> fix Bug #70388.

- web/projects/portal/src/app/portal/report/tree/repository-tree-view.component.ts
- web/projects/portal/src/app/widget/repository-tree/repository-tree.component.ts
select and expand to path after setting  root node.
> fix Bug #70383,  select and expand to path after setting  root node.

- web/projects/em/src/app/settings/content/data-space/data-space-file-settings-view/data-space-file-settings-view.component.html
- web/projects/em/src/app/settings/content/data-space/data-space-file-settings-view/data-space-file-settings-view.component.ts
after change file of format.css, we should update content of new file on the pane then content and file will be matched.
> fix Bug #70339:

- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
change simple schedule to use local time zone to show time, the time will be bookmark default name.
> fix Bug #70130:

- core/src/main/java/inetsoft/web/composer/vs/objects/controller/VSTableService.java
clone columnselection to avoid changing ws table columns.
> fix Bug #70400, clone columnselection

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
invalidate http sessions after user was deleted.
>  fix Bug #70286, invalidate http sessions after user was deleted.

- web/projects/em/src/app/settings/schedule/task-options-pane/task-options-pane.component.html
At the "Task Owner Settings" in the "em Schedule," display the user alias if the user has one; otherwise, display the user name
> fix Bug #70426, 

- core/src/main/java/inetsoft/uql/viewsheet/internal/VsToReportConverter.java
do not convert the component assembly and data view assembly to report element when export print layout vs to pdf.
> fix Bug #70362

- core/src/main/java/inetsoft/web/portal/controller/RepositoryTreeChangeController.java
- web/projects/shared/schedule/time-zone.service.ts
1. fix NPE which happened before client subscribe.
2. add minuteOffset attribute for timezone model.
> fix Bug #70389, fix NPE which happened before client subscribe.

- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
- core/src/main/java/inetsoft/web/WebSocketConfig.java
- core/src/main/java/inetsoft/web/admin/monitoring/MonitoringDataService.java
- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleController.java
- core/src/main/java/inetsoft/web/admin/schedule/IdentityChangedMessage.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleUsersChangeService.java
- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
- core/src/main/java/inetsoft/web/service/BaseSubscribeChangHandler.java
- web/projects/shared/schedule/schedule-users.service.ts
1. update the task action use email after user changed. 
2. update the schedule-users.service data after current org use is changed.
> fix Bug #70393

- core/src/main/java/inetsoft/web/admin/content/repository/MVSupportService.java
avoid save mv to others org, set current use as the thread context when run the mv at background
> fix Bug #70432

- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/datasource/mailchimp/MailchimpDataSource.java
The data center of the Mailchimp data source should not depend on the credential component.
> fix Bug #70420.

- core/src/main/java/inetsoft/web/admin/content/repository/RepositoryDashboardService.java
Exempt admins from being removed from selected Dashboards when permissions change
> Bug #70374

- core/src/main/java/inetsoft/report/composition/execution/ViewsheetSandbox.java
Allow changes to embedded viewsheets to propagate a refresh to the parent viewsheet
> Bug #70423  Propagate embedded vs changes to parent vs

- core/src/main/java/inetsoft/sree/internal/DeployManagerService.java
- core/src/main/java/inetsoft/uql/asset/internal/AssetUtil.java
check if importing using ThreadLocal as checking for null clashes with embedded asset refreshes
> Bug #62654

- core/src/main/java/inetsoft/sree/security/Permission.java
fix get organization scoped grants.
> fix Bug #70435, fix get organization scoped grants.

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
logout after changing password.
> fix Bug_70250, logout after changing password.

- core/src/main/java/inetsoft/web/viewsheet/service/VSEmailService.java
fix bookmark name for bookmarks which shared by user in same group.
> fix Bug #70434, fix bookmark name.

- core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java
- core/src/main/java/inetsoft/web/viewsheet/controller/VSBookmarkController.java
- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
change bookmark date to use local time zone to show.
The bookmark tooltip is create in server and use server time zone, should send local time zone to server when get bookmarks and set to date format.
> fix Bug #70446:

- core/src/main/java/inetsoft/sree/schedule/TimeCondition.java
the timestamp will not changed for different time zone. so the two method to change time zone for timestamp is no need. Remove the methods meaningless.
> coding review for time zone:

- core/src/main/java/inetsoft/web/admin/content/repository/MVService.java
- core/src/main/java/inetsoft/web/admin/general/MVSettingsService.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleCycleService.java
Cycle permission id needs to be scoped by org
> Bug #70412

- web/projects/em/src/app/settings/schedule/task-options-pane/task-options-pane.component.html
do not show the use alias in the em task owner list, because the alias just for the portal not em.
> fix Bug #70454

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleCycleController.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleCycleService.java
- web/projects/em/src/app/settings/schedule/schedule-cycle-list-page/schedule-cycle-list-page.component.ts
when add new data cycle in server, should get local time zone to server to set condition's time zone to local time zone by default.
> fix Bug #70471:

- core/src/main/java/inetsoft/report/composition/execution/JoinQuery.java
can not reproduce, only fix the array out bound issue. 
The size of the table is used in this for loop, but the values are taken from the result, so there is a risk of going out of bounds. check for two list.
> fix Bug #70413：

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleCycleController.java
- web/projects/em/src/app/settings/schedule/schedule-cycle-list-page/schedule-cycle-list-page.component.ts
1. fix url path.
2. encode timezone id.
> fix Bug 70497, fix url path

- core/src/main/java/inetsoft/web/portal/controller/database/DatabaseModelBrowserService.java
- core/src/main/java/inetsoft/web/portal/model/database/DatabaseDataModelBrowserModel.java
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-data-model-browser/database-data-model-browser.component.ts
- web/projects/portal/src/app/portal/data/model/datasources/database/database-data-model-browser-model.ts
for datasource model and view, should show create time by local time zone.
add date format setting from em to apply to the time info.
> fix Bug #70491：

- core/src/main/java/inetsoft/mv/SubMVTask.java
during create mv, can not get the org id of the mv then throw error and record log.
> fix Bug #70494

- core/src/test/java/inetsoft/report/lens/FormulaTableLensTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/CalendarVSAScriptableTest.java
- core/src/test/java/inetsoft/web/viewsheet/controller/CancelViewsheetLoadingControllerTest.java
fixed exception and add two demo testcase.
> fixed exception and add two demo testcase.

- core/src/main/java/inetsoft/web/portal/data/DataSourceConnectionStatusRequest.java
- core/src/main/java/inetsoft/web/portal/service/datasource/DataSourceStatusService.java
- web/projects/portal/src/app/portal/data/data-datasource-browser/data-datasource-browser.component.ts
- web/projects/portal/src/app/portal/data/model/data-source-connection-status-request.ts
Modify the end time of the dataSource message to local time.
> Fix Bug #70480:

- connectors/inetsoft-googledoc/src/main/resources/inetsoft/uql/gdata/Bundle.properties
- connectors/inetsoft-onedrive/src/main/resources/inetsoft/uql/onedrive/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/adobeanalytics/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/box/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/constantcontact/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/firebase/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/github/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/googlecal/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/gsearchconsole/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/hubspot/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/keap/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/linkedin/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/quickbooks/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/shopify/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/surveymonkey/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/twitter/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/wordpress/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/xero/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/datasource/youtubeanalytics/Bundle.properties
- connectors/inetsoft-rest/src/main/resources/inetsoft/uql/rest/json/Bundle.properties
- core/src/main/resources/inetsoft/util/srinter.properties
- web/projects/portal/src/app/widget/tabular/tabular-view.component.html
Pass documentation link for API key required tip
> Bug #70456

- core/src/main/java/inetsoft/sree/internal/DataCycleManager.java
- core/src/main/java/inetsoft/sree/schedule/ScheduleManager.java
clear extension tasks after deleting org.
> fix Bug #70521, clear extension tasks after deleting org.

- web/projects/em/src/app/settings/security/users/users-settings-page/users-settings-page.component.ts
code review. Branches that have Use of(null) to return a default value, ensuring that the subscription is not interrupted.
> Fix Bug #70499:

- core/src/main/java/inetsoft/web/portal/controller/database/DataSourceService.java
- core/src/main/java/inetsoft/web/portal/model/database/AssetListBrowseModel.java
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-data-model-browser/database-vpm-browser/database-vpm-browser.component.ts
- web/projects/portal/src/app/portal/data/model/datasources/database/asset-list-browse-model.ts
for vpm, should show create time by local time zone.
add date format setting from em to apply to the time info.
> fix Bug #70492：

- web/projects/em/src/app/settings/general/license-key-settings-view/api-key/api-key.component.html
When not input anything,save button should be disable.
> Fix Bug #70515:

- core/src/main/java/inetsoft/uql/DrillPath.java
fix drill link for old version case.
> fix Bug #70422, fix drill link for old version case.

- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
sync identities related attributes when clone org.
> fix Bug #70505, sync identities related attributes when clone org.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-datasource/datasources-datasource-editor/datasources-datasource-editor.component.ts
Just need to display the more accurate reason for the authentication failure.
> fix Bug #70513.

- core/src/main/java/inetsoft/util/dep/ScheduleTaskAsset.java
checking the task exist in the ScheduleTaskAsset, task id should not contain the task folder.
> fix Bug #70518

- core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java
Set runtime user bookmark to update default bookmark immediately
> Bug #70427

- web/projects/em/src/app/settings/general/general-settings-page/general-settings-page.component.html
- web/projects/em/src/app/settings/general/general-settings-page/general-settings-page.component.ts
Add API key to settings nav link options
> Bug #70469

- web/projects/em/src/app/settings/general/license-key-settings-view/edit-license-key-dialog/edit-license-key-dialog.component.html
- web/projects/em/src/app/settings/general/license-key-settings-view/edit-license-key-dialog/edit-license-key-dialog.component.ts
Remove extraneous key label check
> Bug #70495

- web/projects/portal/src/app/portal/schedule/schedule-task-editor/execute-as-dialog/execute-as-dialog.component.ts
check for alias in node "label" property containing alias
> Bug #70472

- web/projects/em/src/app/settings/content/materialized-views/mv-management-view/mv-management-view.component.ts
Check if using dateAsAges before applying format and overwriting lastModified string
> Bug #70473

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
reload schedule task users after deleting identity.
> fix Bug #70514, reload schedule task users after deleting identity.

- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
sync bookmark users after renaming org.
> fix Bug #70504, sync bookmark users after renaming org.

- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartMaxModeController.java
- core/src/main/java/inetsoft/web/viewsheet/controller/table/VSTableMaxModeController.java
- core/src/main/java/inetsoft/web/viewsheet/service/MaxModeAssemblyService.java
Merged forward from the fix to the 13.7 issue Bug #70141.
> Bug #70528  Fix enlarged chart z-index issue

- core/src/main/java/inetsoft/util/dep/DependencyInfo.java
- core/src/main/java/inetsoft/util/dep/XAssetDependency.java
- core/src/main/java/inetsoft/web/admin/content/repository/ContentRepositoryTreeNode.java
- core/src/main/java/inetsoft/web/admin/content/repository/ContentRepositoryTreeService.java
- core/src/main/java/inetsoft/web/admin/content/repository/model/RequiredAssetModel.java
- core/src/main/java/inetsoft/web/admin/content/repository/model/SelectedAssetModel.java
- core/src/main/java/inetsoft/web/admin/deploy/DeployService.java
- web/projects/em/src/app/settings/content/repository/import-export/required-asset-list/required-asset-list.component.html
- web/projects/em/src/app/settings/content/repository/import-export/required-asset-list/required-asset-list.component.ts
- web/projects/em/src/app/settings/content/repository/import-export/required-asset-model.ts
- web/projects/em/src/app/settings/content/repository/import-export/selected-asset-list/selected-asset-list.component.html
- web/projects/em/src/app/settings/content/repository/import-export/selected-asset-list/selected-asset-list.component.ts
- web/projects/em/src/app/settings/content/repository/import-export/selected-asset-model.ts
- web/projects/em/src/app/settings/content/repository/repository-tree-node.ts
- web/projects/shared/util/date-type-formatter.ts
change all time string to timestamp when export and import, then it can show according to its local time zone.
after change time string to timestamp, should deliver dateFormat from server to client to apply.
> fix Bug #70524：

- core/src/test/java/inetsoft/report/lens/JoinTableLensTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/CalcTableVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/CalendarVSAScriptableTest.java
- core/src/test/java/inetsoft/util/ExtendedDateFormatTest.java
add new testcase and fixed some exception when execute test
> add new test case and fixed case issue.

- core/src/main/java/inetsoft/web/AutoSaveUtils.java
- core/src/main/java/inetsoft/web/admin/content/repository/AutoSaveController.java
- web/projects/em/src/app/settings/content/repository/auto-save-recycle-bin/auto-save-recycle-bin-page.component.ts
for auto save file, it should using local time zone to show time info
> fix Bug #70522：

- core/src/main/java/inetsoft/mv/MVManager.java
> fix Bug #70544, list mv for current org.

- web/projects/portal/src/app/widget/schedule/simple-schedule-dialog.component.ts
update the task condition time zone after set the default time zone for the task condition.
> fix Bug #70506

- core/src/main/java/inetsoft/util/Tool.java
- core/src/main/java/inetsoft/web/admin/properties/PropertiesController.java
Directly check string.compare.caseSensitive property when determining if should check case
> Bug #70241

- core/src/main/java/inetsoft/report/script/viewsheet/CalendarVSAScriptable.java
> fix Bug #70543, fix week of month.

- core/src/main/java/inetsoft/web/portal/controller/PortalController.java
- core/src/main/java/inetsoft/web/portal/model/PortalCreationPermisisons.java
- web/projects/portal/src/app/portal/app.component.html
- web/projects/portal/src/app/portal/app.component.ts
- web/projects/portal/src/app/portal/custom/portal-creation-permissions.ts
refresh creation perrmisons when popup creation list.
>  fix Bug #70540, refresh creation perrmisons when popup creation list.

- web/projects/em/src/app/settings/schedule/task-action-pane/backup-file/backup-file.component.ts
just ignore the additional datasource when select datasource and click add all in the backup action.
> fix Bug #70551

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
clear new user cache DashboardRegistry before rename user, new use DashboardRegistry cache maybe exist if storage is error.
> fix Bug #70561

- core/src/main/java/inetsoft/web/admin/content/repository/model/ExportedAssetsModel.java
- core/src/main/java/inetsoft/web/admin/deploy/DeployService.java
- web/projects/em/src/app/settings/content/repository/import-export/exported-assets-model.ts
- web/projects/em/src/app/settings/content/repository/import-export/import-asset-dialog/import-asset-dialog.component.html
- web/projects/em/src/app/settings/content/repository/import-export/import-asset-dialog/import-asset-dialog.component.ts
when import jars, it will show jar file exporting time in import dialog. So we should using local time zone to show it
> fix Bug #70560:

- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartController.java
- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartMaxModeController.java
- web/projects/portal/src/app/vsobjects/event/vs-chart-event.ts
1, modify the Bug #62807 changed to make it just affect the vs wizard.
2, change the chart to max mode, also refresh the others assembly to make sure them can apply visible correctly, but do not reload the others assembly data to keep the performance.
> fix Bug #70570, merge from 13_8

- core/src/main/java/inetsoft/web/admin/content/repository/model/SelectedAssetModel.java
- core/src/main/java/inetsoft/web/admin/deploy/DeployService.java
1 should add nullable to lastModifyTime for some folder do not saved it. 
2 using Long instead of long so it can use nullable to deliver data to client, so should check null or not for the values.
> fix Bug #70559:

- web/projects/portal/src/app/composer/gui/vs/layouts/layout-object.component.html
- web/projects/portal/src/app/embed/chart/embed-chart.component.html
- web/projects/portal/src/app/vsobjects/objects/vs-object-container.component.html
- web/projects/portal/src/app/vsview/view/vs-object-view.component.html
make sure vsInfo setted before model.
> fix Bug #70536, make sure vsInfo setted before model.

- core/src/test/java/inetsoft/report/script/viewsheet/CheckBoxVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/ComboBoxVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/RadioButtonVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SliderVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SpinnerVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/TextInputVSAScriptableTest.java
add unit cases for InputVSAScriptable and its subclasses
> InputVSAScriptable unit case

- core/src/main/java/inetsoft/mv/MVManager.java
- core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
While modifying the user name, also update the user in the materialized view (MV).
> Fix Bug #70508:

- core/src/main/java/inetsoft/report/composition/execution/TimeSliderVSAQuery.java
set correct StateSelectionList at runtime mode, ensure the range slider can create correct condition to filter data.
> Bug #70591

- web/projects/portal/src/app/vsobjects/objects/submit/vs-submit.component.scss
Fix the submit button style issue after importing cases into version 14.0 by merging the changes from Bug #69658.
> fix Bug #70574

- core/src/main/java/inetsoft/sree/internal/SUtil.java
- core/src/main/java/inetsoft/storage/BlobStorage.java
should get real org id to init indexstorage, else will exist root folders with both orgid and lower case orgid.
> fix Bug #70557, should get real org id to init indexstorage.

- core/src/main/java/inetsoft/report/internal/Util.java
for auto save file's action record, if null user, should show user name as "anonymous", if have user identity, should only show name in path.
> fix Bug #70578:

- core/src/main/java/inetsoft/web/admin/content/repository/MVSupportService.java
use current org id when deleting mvs.
> fix Bug #70593, use current org id when deleting mvs.

- core/src/main/java/inetsoft/uql/erm/HiddenColumns.java
- core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
While renaming the role, also update the role's display name in the "Grant to" panel within the Virtual Private Model.
> Fix Bug #70612:

- core/src/main/java/inetsoft/web/composer/RuntimeSheetTransformController.java
Fix NPE (NullPointerException) since some sheets may not have created bookmarks.
> Fix Bug #70601:

- core/src/main/java/inetsoft/sree/security/OrganizationManager.java
- core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java
- core/src/main/java/inetsoft/web/messaging/MessageScopeInterceptor.java
- core/src/main/java/inetsoft/web/share/ShareController.java
- core/src/main/java/inetsoft/web/viewsheet/controller/GetImageController.java
for share global assets, all runtime viewsheet operate request temp switch to host org.
> fix Bug #70538

- core/src/main/java/inetsoft/web/admin/content/repository/RepositoryFolderService.java
fix empty alias cause resource not displayed issue.
> fix Bug #70605, fix empty alias cause resource not displayed issue.

- core/src/main/java/inetsoft/uql/asset/sync/AssetDependencyTransformer.java
Rename worksheets and worksheet folders, and update their display in the MV list.
> Fix Bug #70525:

- core/src/main/java/inetsoft/web/portal/controller/database/DataSourceService.java
- core/src/main/java/inetsoft/web/portal/controller/database/LogicalModelService.java
- core/src/main/java/inetsoft/web/portal/controller/database/PhysicalModelManagerService.java
- core/src/main/java/inetsoft/web/portal/data/DataSourceBrowserService.java
- core/src/main/java/inetsoft/web/viewsheet/DatasourceIgnoreGlobalShare.java
- core/src/main/java/inetsoft/web/viewsheet/EventAspect.java
add DatasourceIgnoreGlobalShare annotation and aspect to ignore the global share data source during create new object and check it exist.
> fix Bug #70553

- core/src/main/java/inetsoft/web/portal/controller/PortalController.java
- web/projects/shared/util/guard/global-parameter-guard.service.ts
Encode the viewsheet path to fix the 400 error.
> fix Bug #70625. Encode the viewsheet path to fix the 400 error.

- core/src/main/java/inetsoft/sree/internal/SUtil.java
- core/src/main/java/inetsoft/web/AutoSaveUtils.java
- core/src/main/java/inetsoft/web/admin/content/repository/ContentRepositoryTreeService.java
Only append organization to autosave path when security is enabled
> Bug #70385

- core/src/main/java/inetsoft/uql/asset/AssetEntry.java
- core/src/main/java/inetsoft/uql/asset/sync/UpdateDependencyHandler.java
- core/src/main/java/inetsoft/util/dep/DashboardAsset.java
- core/src/main/java/inetsoft/util/dep/VSSnapshotAsset.java
- core/src/main/java/inetsoft/util/dep/ViewsheetAsset.java
- core/src/main/java/inetsoft/util/dep/WorksheetAsset.java
change assets to current org when importing assets.
> fix Bug #70643, change assets to current org when importing assets.

- core/src/test/java/inetsoft/report/script/viewsheet/CheckBoxVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/ComboBoxVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/RadioButtonVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SelectionListVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SliderVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SpinnerVSAScriptableTest.java
> unit cases for InputVSAScriptable and its subclasses

- core/src/main/java/inetsoft/sree/security/SecurityEngine.java
for chart type, if user do not set the permission, to use the parent folder permission.
> fix Bug #70538,

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
- core/src/main/java/inetsoft/web/admin/schedule/model/UsersModel.java
- core/src/main/java/inetsoft/web/viewsheet/controller/dialog/EmailDialogController.java
- core/src/main/java/inetsoft/web/viewsheet/controller/dialog/ScheduleDialogController.java
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/options/task-options-pane.component.ts
- web/projects/shared/schedule/model/users-model.ts
- web/projects/shared/schedule/schedule-users.service.ts
get correct email groups for the simple schedule dialog. emailGroupBaseNames has removed, so use emailGroups, it is same with the schedule task.
> fix Bug #70562,

- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
update the org id of the query asset entry when migrate the batch action of the task.
> fix Bug #70618

- core/src/main/java/inetsoft/sree/schedule/ViewsheetAction.java
do not export the bookmarks that the task user do not get permission to access.
> fix Bug #70635

- core/src/main/java/inetsoft/mv/MVManager.java
execute the mv when org user open the share global dashboard.
> fix Bug #70602

- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleBatchActionController.java
- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleTaskActionController.java
- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleTaskActionService.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskActionService.java
- core/src/main/java/inetsoft/web/admin/schedule/model/ScheduleAlertModel.java
- core/src/main/java/inetsoft/web/portal/controller/ScheduleTaskActionController.java
Refactor ScheduleTaskActionService to proxy required methods
> Feature #70119

- core/src/test/java/inetsoft/report/script/viewsheet/RangeSliderVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SelectionListVSAScriptableTest.java
add unit case for RangeSliderVSAScriptable
> unit case for RangeSliderVSAScriptable

- core/src/main/java/inetsoft/sree/internal/DeployManagerService.java
when user is null, should show "anonymous" for user.
> fix Bug #70644:

- core/src/main/java/inetsoft/sree/schedule/ScheduleManager.java
just update current org tasks when the sheet is changed
> fix Bug #70684, just update current org tasks when the sheet is changed.

- core/src/main/java/inetsoft/web/security/DefaultAuthorizationFilter.java
for ORG_COOKIE, set SameSite by the config setting
> fix Bug #70709, for ORG_COOKIE, set SameSite by the config setting.

- web/projects/portal/src/app/binding/widget/binding-tree/vs-binding-tree-actions.ts
> Fix Bug #70677:

- core/src/main/java/inetsoft/uql/util/filereader/CSVLoader.java
ignore the empty lines at the beginning of the CSV file during import it to ws
> fix Bug #70654, ignore the empty lines at the beginning of the CSV file during import it to ws

- core/src/main/java/inetsoft/sree/internal/SUtil.java
- core/src/main/java/inetsoft/web/portal/controller/PreferencesDialogController.java
1, disable the changed emails options for Non-editable user. 
2, throw error when edit the Non-editable user emails.
> fix Bug #70703

- web/projects/portal/src/app/portal/data/move-data-model-dialog/move-data-model-dialog.component.html
fix close button position is wrong in move dialog
> Bug #70668

- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
>  fix Bug #70649, sync task path.

- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartAxesVisibilityController.java
- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartAxesVisibilityService.java
- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartControllerService.java
- core/src/main/java/inetsoft/web/viewsheet/event/chart/VSChartEvent.java
I also needed to make some fixes to the parent VSChartControllerService
> Feature #70119 VSChartAxesVisibilityController service proxy

- web/projects/portal/src/app/composer/gui/vs/layouts/layout-object.component.html
- web/projects/portal/src/app/composer/gui/vs/layouts/layout-object.component.scss
for layout object, do not overlay the resize and move handle by the non-editable object overlay div.
> fix Bug #70661, for layout object, do not overlay the resize and move handle by the non-editable object overlay div.

- core/src/main/java/inetsoft/web/composer/vs/dialog/ImagePreviewPaneController.java
- web/projects/portal/src/app/widget/image-editor/image-preview-pane.component.html
support tiff type image for vs image, tiff is same with tif.
> fix Bug #70604, support tiff type image for vs image, tiff is same with tif.

- core/src/main/java/inetsoft/web/admin/security/SecurityConfigController.java
save SreeEnv after set "security.login.orgLocation" property.
> fix Bug #70740, save SreeEnv after set "security.login.orgLocation" property.

- core/src/main/java/inetsoft/web/portal/data/DatasourcesBaseService.java
Automatically assign datasource permissions because of special folder permissions in self org
> Bug #70752

- web/projects/portal/src/app/composer/gui/vs/editor/viewsheet-pane.component.ts
Fix the confirmation message for the sheet being expired.
> fix Bug #70688

- core/src/main/java/inetsoft/web/admin/content/repository/RepositoryDashboardService.java
when rename dashboard in em(global dashboard or user dashboard), should transform  tasks used it dashboards in backup actions.
> fix Bug #70671：

- core/src/main/java/inetsoft/util/migrate/MigrateDocumentTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateViewsheetTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateWorksheetTask.java
- core/src/main/java/inetsoft/web/AutoSaveUtils.java
- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
migrate the auto save file to new org when rename an org.
> fix Bug #70686, migrate the auto save file to new org when rename an org.

- core/src/main/java/inetsoft/uql/asset/sync/AssetWSDependencyTransformer.java
When moving the ws to a private folder, modify the AutoDrill xml file by adding the user attribute.
> Fix Bug #70728:

- core/src/main/java/inetsoft/uql/asset/internal/MirrorAssemblyImpl.java
Append org directly to handle mismatch when importing old assets not originally containing org id
> Bug #70700

- core/src/test/java/inetsoft/report/script/viewsheet/RadioButtonVSAScriptableTest.java
fix error in RadioButtonVSAScriptableTest
> Bug #70790-fix unit case error

- core/src/main/java/inetsoft/uql/asset/AssetEntry.java
- core/src/main/java/inetsoft/util/BlobIndexedStorage.java
- core/src/main/java/inetsoft/util/migrate/MigrateViewsheetTask.java
When renaming a user, it is necessary to consider viewsheets where the user is null, because the hyperlink in a viewsheet may be a private viewsheet.
> Fix Bug #70783:

- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
When migrating the ScheduleTask, the modification should simultaneously update the email values in both MailTo and Notify content.
> Fix Bug #70769:

- core/src/main/java/inetsoft/sree/security/Permission.java
- core/src/main/java/inetsoft/sree/security/SecurityEngine.java
Check org scoped isBlank to prevent false negative when other org permission exists
> Bug #70779, Bug #70777

- web/projects/portal/src/app/vsobjects/objects/data-tip/vs-data-tip.directive.ts
date tip assembly should not out the viewport area when it in the embedded vs.
> fix Bug #70717, date tip assembly should not out the viewport area when it in the embedded vs.

- core/src/main/java/inetsoft/util/migrate/MigrateDocumentTask.java
when copy organiztion or ranme organization, it will send task add request to add new tasks to scheduleclient service. So it will get new info to run tasks.
when rename user, the user is used for task info(email info for backup action), after migate task, should add task to schedule client so there is no need to restart schedule client to run old tasks.
copy organization and rename user name in different method to migate, so will not fix it duplicate.
Bug #70567 is the same issue.
> fix Bug #70599：

- core/src/main/java/inetsoft/sree/schedule/ViewsheetAction.java
do not filter the home bookmark by user for the viewsheet action.
> fix Bug #70765, do not filter the home bookmark by user.

- core/src/main/java/inetsoft/report/composition/WorksheetEngine.java
- core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
- core/src/main/java/inetsoft/uql/asset/AssetRepository.java
just check private assets permission when open the sheet, ensure the em can repository can load the use private assets for the org admin.
> fix Bug #70556 , just check private assets permission when open the sheet,

- core/src/main/java/inetsoft/uql/asset/sync/DependencyTransformer.java
- core/src/main/java/inetsoft/uql/erm/XDataModel.java
sync the extend models for backup action when the base model name is changed.
> fix Bug #70763, sync the extend models for backup action when the base model name is changed.

- core/src/main/java/inetsoft/sree/security/AbstractEditableAuthenticationProvider.java
sync the auto save files after clone the org to create a new org.
> fix Bug #70781, sync the auto save files after clone the org to create a new org.

- core/src/main/java/inetsoft/web/security/AnonymousUserFilter.java
for websocket request, reject request when do not create principal(user do not authenticate).
> fix Bug #70652, for websocket request, reject request when do not create principal(user do not authenticate).

- core/src/main/java/inetsoft/web/portal/data/DataSourceBrowserService.java
- web/projects/portal/src/app/portal/data/data-datasource-browser/data-datasource-browser.component.html
for create query action of the datasource, just check the physical table permission for the JDBC datasource.
> fix Bug #70812, for create query action of the datasource, just check the physical table permission for the JDBC datasource.

- core/src/main/java/inetsoft/uql/asset/sync/AssetWSDependencyTransformer.java
When renaming AutoDrill, replaceAttribute should only be executed when modifying a viewsheet or a viewsheet's folder, and worksheet entries should only be modified when altering a worksheet.
> Fix Bug #69036:

- core/src/main/resources/inetsoft/util/srinter.properties
Because the page has been deleted, the link has been removed.
> Fix Bug #70815:

- core/src/main/resources/inetsoft/web/resources/login.html
Adjust the position of the close icon using the modal-header component.
> Bug #70816

- core/src/main/java/inetsoft/web/admin/content/repository/ResourcePermissionTreeController.java
- core/src/main/java/inetsoft/web/admin/security/user/SecurityTreeServer.java
- web/projects/em/src/app/settings/schedule/schedule-configuration-page/time-range-editor/time-range-editor.component.html
- web/projects/em/src/app/settings/security/resource-permission/resource-permission.component.ts
- web/projects/em/src/app/settings/security/security-tree-dialog/security-tree-dialog-data.ts
- web/projects/em/src/app/settings/security/security-tree-dialog/security-tree-dialog.component.ts
Since the Schedule setting is global and can only be configured by the host organization, the timeRange should only display the host's settings—showing other organizations' could cause confusion.
> Fix Bug #70814:

- web/projects/em/src/app/navbar/organization-dropdown.service.ts
- web/projects/em/src/app/settings/security/security-provider/authentication-provider-list-page/authentication-provider-list-page.component.ts
- web/projects/em/src/app/settings/security/security-settings-page/security-settings-page.component.ts
> fix Bug #70808, refresh providers

- core/src/main/java/inetsoft/web/viewsheet/controller/VSBookmarkController.java
- core/src/main/resources/inetsoft/util/srinter.properties
the bug is caused is user do not have permission to delete a bookmark, we will not show it in ui, but user can using codes to delete bookmark without delete permission. So should check permission for delete action in server, and if do not have permission, should show warning for user.
> fix Bug #70101:

- web/projects/em/src/app/settings/security/users/users-settings-page/users-settings-page.component.ts
refresh providers after creating organization
> refresh providers after creating organization

- core/src/main/java/inetsoft/mv/MVDef.java
site admin should not get the others uses mv data, the data is different for different use when datasource has vpm
> fix Bug #70775, site admin should not get the others uses mv data, the data is different for different use when datasource has vpm.

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
fix NPE when there's no session service.
> fix Bug #70731, fix NPE when there's no session service.

- core/src/main/java/inetsoft/sree/internal/SUtil.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
- core/src/main/java/inetsoft/web/admin/schedule/model/UsersModel.java
- core/src/main/java/inetsoft/web/portal/controller/PortalController.java
- web/projects/em/src/app/settings/security/users/identity-id.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/actions/action-accordian/action-accordion.component.ts
- web/projects/portal/src/app/widget/email-dialog/email-pane.component.ts
- web/projects/portal/src/app/widget/email-dialog/embedded-email-pane.component.ts
- web/projects/shared/schedule/model/users-model.ts
- web/projects/shared/schedule/schedule-users.service.ts
Revert changes for portal side user alias for scheduled emails, defer change for Bug #70713
> Bug #70822

- core/src/main/java/inetsoft/sree/web/dashboard/DashboardRegistry.java
- core/src/main/java/inetsoft/util/dep/DashboardAsset.java
- core/src/main/java/inetsoft/web/admin/content/repository/ContentRepositoryTreeService.java
- core/src/main/java/inetsoft/web/admin/content/repository/RepositoryDashboardService.java
- core/src/main/java/inetsoft/web/portal/controller/ArrangeDashboardDialogController.java
- core/src/main/java/inetsoft/web/portal/controller/DashboardController.java
Anonymous user identity should be type User for consistent storage reference
> Bug #70778

- web/projects/portal/src/app/common/abstract-highlight.component.ts
fix highlight is not complete pop up message contain special char
> Bug #70835

- web/projects/portal/src/app/vsobjects/objects/selection/selection-list-cell.component.html
- web/projects/portal/src/app/vsobjects/objects/selection/selection-list-cell.component.scss
- web/projects/portal/src/app/vsobjects/objects/selection/selection-list-cell.component.ts
- web/projects/portal/src/app/vsobjects/objects/selection/vs-selection.component.html
increase mobile selection list/selection tree icon size for max mode.
> fix Bug #70800, increase mobile selection list/selection tree icon size for max mode.

- web/projects/portal/src/app/composer/gui/ws/editor/ws-pane.component.ts
> Fix Bug #70846：

- core/src/main/java/inetsoft/mv/MVDef.java
fix NPE during create mv and source has vpm hidden columns.
> Bug #70803, fix NPE during create mv and source has vpm hidden columns.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/datasources-database.component.ts
> Fix Bug #70849：

- core/src/main/java/inetsoft/web/composer/RuntimeSheetTransformController.java
when rename bookmark, send event to change other browse open same vs and bookmark to reselect the bookmark, if the sheet do not have opened bookmark, should not check it.
> fix Bug #70871:

- web/projects/portal/src/app/composer/gui/vs/editor/viewsheet-pane.component.ts
should check null for orgInfo to avoid caused communicate errors. fix it, the errors are all ok.
> fix Bug #70873:

- core/src/main/java/inetsoft/web/composer/vs/objects/controller/ComposerObjectController.java
- web/projects/portal/src/app/vsobjects/objects/output/text/vs-text.component.ts
Merge forward Bug #69954 and Bug #69955 to address performance issues with nested dashboards
> Bug #70676 - performance issues with nested dashboards

- web/projects/portal/src/app/widget/schedule/simple-schedule-dialog.component.html
Use the correct way to manage the state of the 'Only Data Elements' field.
> fix Bug #70877

- core/src/main/java/inetsoft/mv/VSMVAnalyzer.java
- core/src/main/java/inetsoft/mv/trans/TransformationFault.java
- core/src/main/java/inetsoft/mv/trans/TransformationInfo.java
- core/src/main/resources/inetsoft/util/srinter.properties
Show a warning that MV conditions will not be applied to the user.
Fix grammar mistakes.
> Bug #70844 Show a warning that MV conditions will not be applied

- core/src/main/java/inetsoft/util/BlobIndexedStorage.java
- core/src/main/java/inetsoft/util/migrate/MigrateCubeTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateDocumentTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateLogicalModelTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateViewsheetTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateWorksheetTask.java
Pass orgID to MigrateDocumentTask, call renameDependencies when updating user name
> Bug #70845, Bug #70824

- core/src/main/java/inetsoft/uql/asset/sync/AssetDependencyTransformer.java
- core/src/main/java/inetsoft/uql/asset/sync/AssetHyperlinkDependencyTransformer.java
> fix Bug #70855, sync bookmark in hyperlink.

- core/src/main/java/inetsoft/sree/RepletRegistry.java
transform previous global RepletRegistry to isolate by org.
> fix Bug #70861, transform previous global RepletRegistry to isolate by org.

- core/src/main/resources/inetsoft/util/srinter.properties
- web/projects/shared/util/datasource/data-source-settings-page.ts
Each user under self is independent, but dataSources are organized by the organization. Therefore, simply modify the prompt accordingly.
> Fix Bug #70841：

- core/src/main/java/inetsoft/web/portal/data/DatasourcesTreeService.java
do not check the physical table permission for tabular source create query action.
> fix Bug #70863, do not check the physical table permission for tabular source create query action.

- core/src/main/java/inetsoft/uql/asset/sync/AssetEmbedDependencyTransformer.java
The user field in the entry is an IdentityID object and cannot be directly compared with a String.
> Fix Bug #70883：

- core/src/main/java/inetsoft/sree/RepletRegistry.java
- core/src/main/java/inetsoft/sree/security/AbstractEditableAuthenticationProvider.java
- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
1, change the "Repository XML file not found" message to debug level log, if org do not have replet folder, the file do not exist. it is correct. after create folder and save Repository, the file will be created. 
2, clear RepletRegistry cache of the org, when rename or remove the org.
> fix Bug #70866,

- core/src/main/java/inetsoft/mv/MVManager.java
The warning should use vs name not full vs entry
> Fix Bug #70888:

- core/src/main/java/inetsoft/web/admin/content/repository/ImportAssetController.java
ignore the import request if current import is processing.
> fix Bug #70882, ignore the import request if current import is processing.

- web/projects/portal/src/app/vsobjects/objects/selection/selection-list-cell.component.html
add padding select tree item the expand button and status button.
> fix Bug #70800, add padding select tree item the expand button and status button.

- core/src/main/java/inetsoft/uql/asset/sync/TaskAssetDependencyTransformer.java
Handle logical model not containing folderSplitter key by default
> Bug #70850

- core/src/main/java/inetsoft/report/composition/execution/AssetQuery.java
- core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java
If a date range col is used in a pre condition then add it to the no aggregate table so that the condition can be evaluated
> Bug #70851 - MV pre condition ignored

- core/src/main/java/inetsoft/util/migrate/MigrateDocumentTask.java
- core/src/main/java/inetsoft/util/migrate/MigrateViewsheetTask.java
Update Bookmark's default bookmark entry on owner name change
> Bug #70826

- core/src/main/java/inetsoft/web/viewsheet/controller/VSBookmarkController.java
- core/src/main/java/inetsoft/web/viewsheet/service/VSBookmarkService.java
check bookmark is used in the task vs action, should check vs, user, and bookmark name.
> fix Bug #70897, check bookmark is used in the task vs action, should check vs, user, and bookmark name.

- web/projects/em/src/app/settings/content/repository/content-repository-page/content-repository.service.ts
> Fix Bug #70908:

- core/src/main/resources/inetsoft/util/srinter.properties
- web/projects/portal/src/app/portal/data/data-navigation-tree/data-sources-tree-actions.service.ts
Optimize the prompt message when creating a datasource folder with a duplicate name.
> fix Bug #70906

- core/src/main/java/inetsoft/web/admin/user/TopUsersMonitoringTableModel.java
- web/projects/em/src/app/monitoring/summary/summary-monitoring-page/summary-monitoring-page.component.ts
Add an organizationId column to the top5user page to let others know which organization this user belongs to.
> Fix Bug #70921:

- core/src/main/java/inetsoft/web/portal/data/DatasourcesBaseService.java
Every time after editing the dataSource and clicking OK, the last modified time should be updated.
> Fix Bug #70918:

- core/src/main/java/inetsoft/uql/viewsheet/Viewsheet.java
Allow viewsheet assemblies to overlap.
> Merge forward changes for Bug #70890 - allow viewsheet assemblies to overlap

- core/src/main/java/inetsoft/sree/RepletRegistry.java
Pass old userID to ensure correct update, only update if registries are different
> Bug #70909

- core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
save properties to storage after editing org properties.
> fix Bug #70974, save properties to storage.

- core/src/main/java/inetsoft/sree/RepletRegistry.java
> fix Bug #70958, add FolderContext.

- core/src/main/java/inetsoft/uql/util/XUtil.java
- core/src/main/java/inetsoft/web/portal/data/BaseDataSourceDefinition.java
- core/src/main/java/inetsoft/web/portal/data/DatasourcesBaseService.java
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-datasource/datasources-datasource-editor/datasources-datasource-editor.component.ts
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-datasource/datasources-datasource.component.ts
- web/projects/shared/util/model/data-source-definition-model.ts
update permission for additional datasource
> fix Bug #70938, update permission for additional datasource.

- web/projects/portal/src/app/composer/dialog/ws/import-csv-dialog.component.html
- web/projects/portal/src/app/composer/dialog/ws/import-csv-dialog.component.ts
- web/projects/portal/src/app/vsobjects/objects/table/preview-table.component.html
- web/projects/portal/src/app/vsobjects/objects/table/preview-table.component.ts
1 when loading all data for upload file, should show warning if header is invalid(only show warning after edit one header before) 
2 when column header is invalid, show background for the header to show user which one is wrong.
> fix Bug #70965:

- core/src/main/java/inetsoft/util/dep/ViewsheetAsset.java
fix org id for bookmark users when import viewsheets.
> fix Bug #70975, fix org id for bookmark users when import viewsheets.

- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleTaskController.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
On the portal side, the label of the task's viewsheet action should display the alias of the viewsheet.
> fix Bug #70937

- core/src/main/java/inetsoft/web/admin/security/AuthenticationProviderService.java
three shell issues the vs and model can not execute rightly for do not add classes folder to LocalContext, just add them. For user it should using "@EnableAspectJAutoProxy(proxyTargetClass = true)" to avoid using JDK Proxy but Using AuthenticationProviderService in UserTreeService.
> fix Bug #70954:

- web/projects/portal/src/app/vsobjects/objects/mini-toolbar/mini-toolbar.service.ts
- web/projects/portal/src/app/vsobjects/objects/vs-object-container.component.ts
fix mini toolbar position error for the max mode chart of the embedded vs.
> fix Bug #70952, fix mini toolbar position error for the max mode chart of the embedded vs.

- core/src/main/java/inetsoft/web/admin/content/repository/RepositoryObjectService.java
use updated path when checking permission of physical view folder to properly check parent permissions
> fix Bug #70986, use updated path when checking permission of physical view folder to properly check parent permissions

- web/projects/portal/src/app/composer/data/vs/viewsheet.ts
- web/projects/portal/src/app/composer/data/vs/vs-layout-model.ts
- web/projects/portal/src/app/composer/gui/composer-main.component.ts
- web/projects/portal/src/app/composer/gui/composer-main.spec.ts
- web/projects/portal/src/app/composer/gui/vs/editor/viewsheet-pane.component.spec.ts
- web/projects/portal/src/app/composer/gui/vs/editor/viewsheet-pane.component.ts
- web/projects/portal/src/app/vs-wizard/gui/wizard-pane/vs-wizard-pane.component.ts
- web/projects/portal/src/app/widget/services/font.service.ts
use the default font from server in viewsheet and vs layout model.
> fix Bug #70946, use the default font from server

- core/src/test/java/inetsoft/report/script/viewsheet/CheckBoxVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/ComboBoxVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/RadioButtonVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SelectionListVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SelectionTreeVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/TabVSAScriptableTest.java
add unit case for tab and selection tree script
> add unit case for tab and selection tree script

- core/src/main/java/inetsoft/web/portal/data/DatasourcesBaseService.java
code review, add folder spliter.
> code review

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
remove old permission after renaming identity.
> fix Bug #71005, remove old permission after renaming identity.

- core/src/main/java/inetsoft/web/admin/schedule/model/ScheduleTaskModel.java
should check right type for backup action for task.
> fix Bug #70928:

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
Fix the issue where the action label shows "null" when the viewsheet does not have an alias.
> fix Bug #71000

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-physical-model/database-physical-model.component.ts
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-physical-model/physical-model-network-graph/physical-model-network-graph.component.ts
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-physical-model/physical-model-table-tree/physical-model-table-tree-node/physical-model-table-tree-node.component.ts
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-physical-model/physical-model-table-tree/physical-model-table-tree.component.ts
1, remove fireSelectedNodesChanged when the selectedGraphModels is changed, it will cause always emit change. 
2, adjust logic of the physical model table selected status during edit it, make it work well.
> fix Bug #70992

- core/src/main/java/inetsoft/util/migrate/MigrateScheduleTask.java
update the link uri during migrate schedule task.
> fix Bug #71013, update the link uri during migrate schedule task.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-physical-model/physical-model-network-graph/physical-model-network-graph.component.ts
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-physical-model/physical-model-table-tree/physical-model-table-tree.component.ts
1, emit selected node changed when click table on tree. 
2, update the dragNodes by the selectedGraphModels if the selectedGraphModels is changed.
> fix Bug #71026,

- core/src/main/java/inetsoft/uql/asset/DependencyHandler.java
- core/src/main/java/inetsoft/uql/asset/sync/DataDependencyTransformer.java
- core/src/main/java/inetsoft/uql/asset/sync/DependencyTransformer.java
- core/src/main/java/inetsoft/uql/asset/sync/RenameTransformHandler.java
- core/src/main/java/inetsoft/uql/erm/XDataModel.java
- core/src/main/java/inetsoft/web/portal/controller/database/PhysicalModelManagerService.java
fix all rename issues for extend model and extend view is used for backup tasks.
note: (1) for extend model and extend view, their type should the same as parent. 
(2)when rename transform should using organization id in rename info
(3) should collect all rename info list to renameDependencyInfo to update dependeny storage
> fix Bug #70988:

- core/src/main/java/inetsoft/report/LibManager.java
- core/src/main/java/inetsoft/web/admin/content/repository/ResourcePermissionController.java
- core/src/main/java/inetsoft/web/admin/content/repository/ResourcePermissionService.java
- core/src/main/java/inetsoft/web/composer/RenameAssetController.java
1. use table stylebi id as resource path.
2. update permission when renaming tablestyle folder.
> fix Bug #71023, update permission after renaming or moving tablestyle and tablestyle folder

- core/src/main/java/inetsoft/report/Hyperlink.java
Fix the bookmark user in hyperlink to match the current organization.
> fix Bug #71022

- core/src/main/java/inetsoft/util/BlobIndexedStorage.java
- core/src/main/java/inetsoft/util/migrate/MigrateBookmarkTask.java
migrate the bookmark when clone an org.
> fix Bug #71009, migrate the bookmark when clone an org.

- web/projects/portal/src/app/graph/objects/chart-plot-area.component.html
make chart reference Line Canvas apply chart-object-canvas class, ensure it can apply default color.
> fix Bug #71030

- core/src/test/java/inetsoft/report/script/viewsheet/GaugeVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/ImageVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SubmitVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/TabVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/TextVSAScriptableTest.java
add unit case for SubmitVSAScriptable, TextVSAScriptable, ImageVSAScriptable
> unit case for some output script

- core/src/main/java/inetsoft/sree/security/FileAuthorizationProvider.java
- core/src/main/java/inetsoft/sree/security/Permission.java
The permissions are already isolated by organization ID. Additional logic has been added to support legacy storage for build continuity.
> fix Bug #71061,   isolate permission by organization ID for legacy storage 

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleConditionService.java
fix array parameter for task, should format parameter values to match with client.
> fix Bug #71017:

- core/src/main/java/inetsoft/web/admin/content/repository/MVSupportService.java
get permission during create mv, when current resource permission is empty should get parent source permission.
> fix Bug #71037, get correct vs permision when create mv.

- core/src/main/java/inetsoft/web/admin/security/user/UserController.java
Find all the user's sessions and then close them.
> Fix Bug #71043:

- core/src/main/java/inetsoft/mv/MVDef.java
1, update the inner ws.
2, update tabular source query org.
> fix Bug #71039, for mv ws, update the query org id.

- core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
Place deleting old asset after updating dependencies and renaming bookmark to prevent rewriting now invalid reference
> Bug #70940

- core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
Set lower case when retrieving to match storing org identity properties
> Bug #71051

- core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
Sort org properties so that editable org properties come first.
> fix Bug #71055. Sort org properties.

- core/src/main/java/inetsoft/sree/internal/DeployManagerService.java
use current org dependency to check the asset changed when import the assets to the target folder.
> fix Bug #71092, use current org dependency to check the asset changed when import the assets to the target folder.

- core/src/main/java/inetsoft/web/security/BasicAuthenticationFilter.java
when setted the max.user.count property, ensure that at least one organization admin can log in
> fix Bug #71049,  ensure that at least one organization admin can log in

- core/src/test/java/inetsoft/report/script/viewsheet/GroupContainerVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/LineVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/RectangleVSAScriptableTest.java
- core/src/test/java/inetsoft/report/script/viewsheet/SelectionContainerVSAScriptableTest.java
unit case for group and shape script
> unit case for group and shape script

- core/src/main/java/inetsoft/sree/RepletRegistry.java
- core/src/main/java/inetsoft/util/ResourceCache.java
1. remove old repository.xml
2. clear all org replet register cache after finishing renaming org id.
> fix Bug #71041, fix user scope repository.xml content be cleared issue.

- core/src/main/java/inetsoft/report/pdf/FontManager.java
- core/src/main/java/inetsoft/report/pdf/TTFontInfo.java
Since the current TTFontInfo object does not conform to the assigned type, it is null. Simply add some null pointer checks.
> Fix Bug #71103:

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-datasource/datasources-datasource-editor/datasources-datasource-editor.component.ts
do not set old name for datasource if the name do not changed.
> fix Bug #71105, do not set old name for datasource if the name do not changed.

- core/src/main/java/inetsoft/sree/security/AbstractEditableAuthenticationProvider.java
org id in the properties should use lowerCase.
> fix Bug #71090,  fix the org scope can not copy during copy org.

- core/src/main/java/inetsoft/report/LibManager.java
reload the lib assets of org when storage is changed.
> fix Bug #70714, reload the lib assets of org when storage is changed.

- web/projects/portal/src/app/portal/schedule/schedule-task-list/move-task-dialog/move-task-dialog.component.html
Use modal-header to display the dialog header for consistent styling.
> Fix Bug #71114:

- core/src/main/java/inetsoft/mv/fs/internal/LocalFileSystem.java
do not rename same XBlock file multi time.
> fix Bug #71096, do not rename same XBlock file multi time.

- core/src/main/java/inetsoft/report/internal/binding/BaseField.java
- core/src/main/java/inetsoft/uql/asset/ColumnRef.java
- core/src/main/java/inetsoft/uql/erm/AttributeRef.java
- core/src/main/java/inetsoft/uql/erm/ExpressionRef.java
- core/src/main/java/inetsoft/uql/viewsheet/VSAggregateRef.java
- core/src/main/java/inetsoft/uql/viewsheet/VSDimensionRef.java
- core/src/main/java/inetsoft/web/binding/controller/ModifyAggregateFieldController.java
- web/projects/portal/src/app/binding/widget/binding-tree/vs-binding-tree-actions.ts
- web/projects/portal/src/app/widget/dialog/script-pane/script-pane.component.html
- web/projects/portal/src/app/widget/dialog/script-pane/script-pane.component.ts
- web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.html
- web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts
support delete Calc field aggregate.
> fix Bug #71089, support delete Calc field aggregate.

- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java
show edit vs icon in the toolbar when org use open share global vs.
> fix Bug #71124, show edit vs icon in the toolbar when org use open share global vs.

- core/src/main/java/inetsoft/web/WebSocketConfig.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskChangeController.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskFolderChangeController.java
- web/projects/em/src/app/settings/schedule/schedule-task-list/em-schedule-change.service.ts
for em and portal schedule folder changed, use different end point to avoid duplicate pushes message.
> fix Bug #71108, for em and portal schedule folder changed, use different end point to avoid duplicate pushes message.

- connectors/inetsoft-googledoc/src/main/java/inetsoft/uql/gdata/GDataQuery.java
during get the GooglePicker model, if the access token is time out refresh it.
> fix Bug #71136, during get the GooglePicker model, if the access token is time out refresh it.

- core/src/main/java/inetsoft/sree/security/AuthorizationChain.java
- core/src/main/java/inetsoft/sree/security/AuthorizationProvider.java
- core/src/test/java/inetsoft/sree/security/CustomAuthorizationProvider.java
save provider config when set permission to CustomAuthorizationProvider.
> fix Bug #71148, save provider config when set permission to CustomAuthorizationProvider.

- core/src/main/java/inetsoft/uql/asset/AbstractTableAssembly.java
- core/src/main/java/inetsoft/uql/asset/WorksheetInfo.java
- core/src/main/java/inetsoft/web/vswizard/controller/VSWizardObjectController.java
for performance, limit the row count when load format during open wizard object.
> fix Bug 71155, for performance, limit the row count when load format during open wizard object.

- core/src/main/java/inetsoft/mv/fs/internal/AbstractFileSystem.java
- core/src/main/java/inetsoft/mv/fs/internal/DefaultBlockSystem.java
- core/src/main/java/inetsoft/sree/security/AbstractEditableAuthenticationProvider.java
copy file system file and block system file from host-org when clone the host-org.
> fix Bug #71184, copy file system file and block system file from host-org when clone the host-org.

- web/projects/portal/src/app/widget/formula-editor/formula-editor-dialog.component.ts
Handle the issue caused by `userAggNames` being `undefined`.
> fix Bug #71220. Handle the issue caused by `userAggNames` being `undefined`.

- core/src/main/java/inetsoft/uql/asset/SnapshotEmbeddedTableAssembly.java
- core/src/main/java/inetsoft/uql/table/SnapshotEmbeddedTableDataCache.java
data of SnapshotEmbeddedTableAssembly is Non-editable, so share data for same SnapshotEmbeddedTableAssembly.
> fix Bug #71188, add SnapshotEmbeddedTableDataCache for snapshot table  data.

- core/src/main/java/inetsoft/sree/schedule/ScheduleManager.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
keep the group share bookmarks when the task user and bookmark user is same group.
> fix Bug #71183, keep the group share bookmarks when the task user and bookmark user is same group.

- core/src/main/java/inetsoft/uql/table/SnapshotEmbeddedTableDataCache.java
> fix Bug #71183, add Copyright Notice.

- core/src/main/java/inetsoft/web/viewsheet/service/VSInputService.java
Check for assembly references in script and make sure that dynamic values get executed.
> Merge forward Bug #71186 - Check for assembly references in script

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
Iterate through all auth providers when copying Identity Permissions
> Bug #71177

- core/src/main/java/inetsoft/report/composition/WorksheetEngine.java
Debounce accessSheet() call to avoid frequent write locks and serialization of the runtime sheet. This improves viewsheet load times.
> Viewsheet performance fix

- core/src/main/java/inetsoft/web/admin/general/DataSpaceSettingsService.java
- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleTaskController.java
disable backup task edit when use do not have the "settings/schedule/tasks" permission.
> fix Bug #71226,  disable backup task edit when use do not have the "settings/schedule/tasks" permission.

- core/src/main/java/inetsoft/sree/DynamicParameterValue.java
- core/src/main/java/inetsoft/sree/RepletRequest.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleConditionService.java
- core/src/main/java/inetsoft/web/composer/model/vs/DynamicValueModel.java
rollback Ramont's changes and some bugs caused by his changes, now all them are ok.
> Bug 71227: rollback Ramont's changes and some bugs fixed on this changes.

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
- core/src/main/java/inetsoft/web/viewsheet/controller/dialog/EmailDialogController.java
for smtp and gooleSmtp, should not use user email to send email, should use its from email configed in em, for smtp type,its from email must be setted in EM
> fix Bug #71166: SMTP should not use user email to send emails

- core/src/main/java/inetsoft/web/viewsheet/controller/VSRefreshController.java
after binding finish, show loading at table when loading the table data.
> fix Bug #71230, after binding finish, show loading at table when loading the table data.

- core/src/main/java/inetsoft/web/admin/security/user/RoleController.java
when deleting a role, prioritize checking if it is the last system admin
> fix Bug #71243, prioritize checking if it is the last system admin

- core/src/main/java/inetsoft/util/BlobIndexedStorage.java
sync bookmark user after renaming user id.
> fix Bug #71242, sync user id.

- web/projects/em/src/app/monitoring/summary/summary-monitoring-page/summary-monitoring-page.component.ts
In community, there is no organization, so the organization should not be displayed.
> Fix Bug #71224:

- core/src/main/java/inetsoft/util/BlobIndexedStorage.java
> fix Bug #71270, fix NPE when rename a user.

- core/src/main/java/inetsoft/util/log/LogContext.java
add org id for org scope resource name to make sure custom log for org resource worked.
> fix Bug #71272, add org id for org scope resource name

- core/src/test/java/inetsoft/util/script/JavaScriptEngineTest.java
add unit case for JavaScriptEngine
> add unit case for JavaScriptEngine

- core/src/test/java/inetsoft/web/composer/vs/dialog/LayoutOptionDialogControllerTest.java
- core/src/test/java/inetsoft/web/composer/vs/dialog/SelectionTreePropertyDialogControllerTest.java
Also needed to fix a the test in LayoutOptionDialogControllerTest
> Feature #70119  Fix test cases for SelectionTreePropertyDialogController

- core/src/main/java/inetsoft/web/viewsheet/controller/VSSelectionListController.java
- core/src/main/java/inetsoft/web/viewsheet/event/ApplySelectionListEvent.java
- core/src/main/java/inetsoft/web/viewsheet/service/VSSelectionService.java
- web/projects/portal/src/app/vsobjects/event/apply-selection-list-event.ts
- web/projects/portal/src/app/vsobjects/model/vs-selection-base-model.ts
- web/projects/portal/src/app/vsobjects/objects/selection/selection-base-controller.ts
- web/projects/portal/src/app/vsobjects/objects/selection/selection-list-controller.ts
- web/projects/portal/src/app/vsobjects/objects/selection/vs-selection.component.html
- web/projects/portal/src/app/vsobjects/objects/selection/vs-selection.component.ts
when apply the selection changed, Segment and submit events when cell count is too high.
> fix Bug #71275, for performance

- core/src/main/java/inetsoft/web/admin/content/repository/RepletRegistryManager.java
The Alias stored in the registry should be compared with the currently entered Alias.
> Fix Bug #71294:File alias settings.

- web/projects/portal/src/app/vsobjects/objects/table/preview-table.component.ts
do not update the scrollY when the vertical scrollbar do not show.
> fix Bug #71289, do not update the scrollY when the vertical scrollbar do not show.

- core/src/main/java/inetsoft/web/composer/vs/objects/controller/ComposerBindingController.java
calendar should not support binding cube, so should not dnd cube column to it.
> fix Bug #71274: should not dnd cube column to calendar.

- core/src/test/java/inetsoft/util/script/CalcStatTest.java
- core/src/test/java/inetsoft/util/script/JavaScriptEngineTest.java
> add unit case for CalcStat

- core/src/main/java/inetsoft/util/script/CalcStat.java
k should large than 0 and less than or equal to 1 when calc k-th percentile of values in a range.
> fix Bug #71297,k should large than 0 and less than or equal to 1 

- core/src/main/java/inetsoft/sree/schedule/ScheduleViewsheetService.java
- core/src/main/java/inetsoft/uql/VariableTable.java
- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleControllerService.java
- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java
- core/src/main/java/inetsoft/web/viewsheet/service/VSLifecycleControllerService.java
- core/src/main/java/inetsoft/web/viewsheet/service/VSLifecycleService.java
- core/src/test/java/inetsoft/test/ControllersExtension.java
- core/src/test/java/inetsoft/web/composer/vs/dialog/ImagePropertyDialogControllerTest.java
Proxy necessary methods for CoreLifecycleService and VSLifecycleService
> Bug #71310

- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java
Update the highlights after setting the text value
> Merge forward changes for Bug #71268 - text highlight fix

- core/src/main/java/inetsoft/uql/service/DataSourceRegistry.java
Repair root data source folder too when using the repair-repository-folders shell command
> Merge forward changes for Bug #71248 - repair root ds folder

- core/src/main/java/inetsoft/sree/RepletRegistry.java
- core/src/main/java/inetsoft/sree/web/dashboard/DashboardRegistry.java
during new org by clone, do not copy user RepletRegistry and DashboardRegistry when the old user Registry do not exist.
> fix Bug #71301, do not copy user RepletRegistry and DashboardRegistry when the old user Registry do not exist.

- core/src/main/java/inetsoft/graph/internal/ManualOrderComparer.java
for cube dimension, when set manual, shoud use its caption to sort, for all data will show caption as data.
> fix Bug #71282: add manual sort for cube dimensions

- core/src/main/java/inetsoft/util/log/LogLevelSetting.java
- core/src/main/java/inetsoft/util/log/LogManager.java
- core/src/main/java/inetsoft/web/admin/logviewer/LogLevelDTO.java
- core/src/main/java/inetsoft/web/admin/logviewer/LogSettingService.java
- core/src/main/java/inetsoft/web/service/RootAppAccessController.java
- core/src/main/resources/inetsoft/util/srinter.properties
- web/projects/em/src/app/settings/logging/LogLevelDTO.ts
- web/projects/em/src/app/settings/logging/add-logging-level-dialog/add-logging-level-dialog.component.html
- web/projects/em/src/app/settings/logging/add-logging-level-dialog/add-logging-level-dialog.component.ts
- web/projects/em/src/app/settings/logging/logging-level-table/logging-level-table.component.ts
- web/projects/em/src/app/settings/logging/logging-settings-view/logging-settings-view.component.html
- web/projects/em/src/app/settings/logging/logging-settings-view/logging-settings-view.component.ts
- web/projects/shared/util/app-info.service.ts
1. add organization name selector in log context dialog.
2. save log context name with org id.
> fix Bug #71272, support select org name for custom resource log context.

- core/src/main/java/inetsoft/util/script/CalcMath.java
fix sumif function, only when there is no sum_range should the range value be summed up
> fix Bug #71337, fix sumif function

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
1. should delete user scoped assets after deleting user.
2. should create self user create db after removing self user.
> fix Bug #71334, remove user scoped assets after deleting user.

- web/projects/portal/src/app/widget/condition/condition-list.component.ts
enlarge the condition dialog to make it show well when open from the condition-list component.
> fix Bug #71360, enlarge the condition dialog to make it show well.

- core/src/main/java/inetsoft/report/io/viewsheet/html/HTMLSelectionTreeHelper.java
Fix the NPE because `format` may be null.
> fix Bug #71335. Fix NPE.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-query/query-main/query-field-pane/edit-field-dialog/edit-field-dialog.component.html
Add 'Help' icon for edit-field-dialog.
> fix Bug #71362. Add 'Help' icon for edit-field-dialog.

- core/src/main/java/inetsoft/uql/viewsheet/DynamicValue.java
- core/src/main/java/inetsoft/uql/viewsheet/VSFormat.java
- core/src/main/java/inetsoft/web/viewsheet/controller/table/BaseTableController.java
- core/src/main/java/inetsoft/web/viewsheet/model/table/BaseTableCellModel.java
hash code of DynamicValue just use dvalue, if use it to calc the hashcode for format, should also use rvalue.
> fix Bug #71369, fix vs format display error

- core/src/main/java/inetsoft/web/viewsheet/handler/VSDrillHandler.java
keep the highlight after process drill filter.
> fix Bug #71388, keep the highlight after process drill filter.

- core/src/main/java/inetsoft/sree/PropertiesEngine.java
- core/src/main/java/inetsoft/util/log/logback/LogbackInitializer.java
do not set inetsoft_audit default logger level, it is no longer in use.
> fix Bug #71358,do not set inetsoft_audit default logger level, it is no longer in use.

- core/src/main/java/inetsoft/web/composer/RuntimeSheetTransformController.java
> Bug #71400, fix NPE

- web/projects/portal/src/app/composer/dialog/ws/show-hide-columns-dialog.component.html
remove useless html class to ensure the cdk-virtual-scroll-viewport can work well.
> fix Bug #71385, remove useless html class to ensure the cdk-virtual-scroll-viewport can work well.

- web/projects/em/src/app/settings/logging/add-logging-level-dialog/add-logging-level-dialog.component.ts
Set 'host org' as the default selection for the organization field and make it mandatory.
> Fix Bug #71393:Set 'host org' as the default selection for the organization field and make it mandatory.

- core/src/main/java/inetsoft/sree/schedule/ScheduleViewsheetService.java
- core/src/main/java/inetsoft/web/ServiceProxyContext.java
- core/src/main/java/inetsoft/web/composer/vs/controller/ComposerViewsheetController.java
- core/src/main/java/inetsoft/web/composer/vs/controller/ComposerViewsheetService.java
- core/src/main/java/inetsoft/web/composer/ws/CloseWorksheetService.java
- core/src/main/java/inetsoft/web/composer/ws/OpenWorksheetController.java
- core/src/main/java/inetsoft/web/viewsheet/EventAspect.java
- core/src/main/java/inetsoft/web/viewsheet/EventAspectService.java
- core/src/main/java/inetsoft/web/viewsheet/controller/TouchAssetController.java
- core/src/main/java/inetsoft/web/viewsheet/controller/VSSelectionListController.java
- core/src/main/java/inetsoft/web/viewsheet/model/RuntimeViewsheetRef.java
- core/src/main/java/inetsoft/web/viewsheet/model/RuntimeViewsheetRefService.java
- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleControllerService.java
- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java
- core/src/main/java/inetsoft/web/viewsheet/service/RuntimeViewsheetManager.java
- core/src/main/java/inetsoft/web/viewsheet/service/VSExportService.java
- core/src/main/java/inetsoft/web/viewsheet/service/VSLifecycleControllerService.java
- core/src/main/java/inetsoft/web/viewsheet/service/VSLifecycleService.java
- core/src/main/java/inetsoft/web/vswizard/controller/VSWizardDialogController.java
- core/src/test/java/inetsoft/test/ControllersExtension.java
Bug #71311, proxy out required methods using runtime sheets, handle opening and processing sheets within same proxy, clean up related methods
> Bug #71311

- core/src/test/java/inetsoft/util/script/CalcTextDataTest.java
Millisecond rounding to a double adds returns one more day
> Fix failing CalcTextDataTest

- core/src/main/java/inetsoft/web/admin/properties/PropertiesController.java
While deleting the property, the corresponding log should also be removed from the LogManager.
> Fix Bug #71416:While deleting the property, the corresponding log should also be removed from the LogManager.

- core/src/main/java/inetsoft/util/script/CalcUtil.java
after convert start and end time to update origin date.
> fix Bug #71383, after convert start and end time to update origin date.

- core/src/main/java/inetsoft/util/script/CalcFinancial.java
in Excel, syd method period range  0 > period, make it is same with Excel.
> ix Bug #71399, in Excel, syd method period range  0 > period, make it is same with Excel.

- web/projects/portal/src/app/vsobjects/objects/combo-box/vs-combo-box.component.html
- web/projects/portal/src/app/vsobjects/objects/combo-box/vs-combo-box.component.scss
- web/projects/portal/src/app/vsobjects/objects/combo-box/vs-combo-box.component.ts
- web/projects/portal/src/app/vsobjects/vs-object.module.ts
use cdk-virtual-scroll-viewport when combox labels length is larger than 500.
> fix Bug #71439, fix performance issue

- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartController.java
When exiting the chart's enlarged mode, if the VSAssembly to be reloaded is a viewsheet, the `reloadVSAssembly` method should be executed recursively to ensure that all assemblies in nested viewsheets can be properly displayed.
> fix Bug #71423. Fix crosstab showing blank in embedded viewsheet after exiting chart enlarged mode.

- core/src/main/java/inetsoft/uql/xmla/Domain.java
- core/src/main/java/inetsoft/uql/xmla/XMLAUtil.java
make cube cache dir is org scope.
> fix Bug #71445, make cube cache dir is org scope.

- core/src/main/java/inetsoft/web/vswizard/recommender/object/VSCrosstabDefaultRecommendationFactory.java
do not filter the non group type dimension ref for crosstab binding.
> fix Bug #71448, do not filter the non group type dimension ref for crosstab binding.

- core/src/main/java/inetsoft/report/composition/execution/AbstractCrosstabVSAQuery.java
at metadata, crosstab filter should not to apply the post condition.
> fix Bug #71463, at metadata, crosstab filter should not to apply the post condition.

- core/src/main/java/inetsoft/web/admin/deploy/DeployService.java
> Fix Bug #71298:Fix NPE.

- web/projects/em/src/app/settings/schedule/task-action-pane/backup-file/backup-file.component.ts
should not show cube catalog for schedule task list
> fix Bug #71486: should not list cube catalog in schedule backup list

- core/src/main/java/inetsoft/web/composer/ComposerAccessController.java
fix Bug #71480, composer access permission should depends on access permission of worksheet and viewsheet.
> merge from 13.8

- web/projects/portal/src/app/portal/data/data-datasource-browser/data-datasource-browser.component.ts
should support dnd olap data source in portal data pane.
> fix Bug #71505: should support dnd olap data source in portal data pane.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-query/data-query-model.service.ts
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/database-query/query-preview/sql-query-preview-pane.component.ts
finish show lading when user cancel the variables input dialog.
> fix Bug #71513, finish show lading when user cancel the variables input dialog.

- web/projects/portal/src/app/vsobjects/objects/viewsheet/vs-viewsheet.component.html
- web/projects/portal/src/app/vsobjects/objects/viewsheet/vs-viewsheet.component.scss
- web/projects/portal/src/app/vsobjects/objects/viewsheet/vs-viewsheet.component.ts
> fix Bug #71484, fix  z-index of embedded vs

- core/src/main/java/inetsoft/web/MapSessionRepository.java
Dynamically control session expiration time based on the 'http.session.timeout' property
> fix Bug #71596, Dynamically control session expiration time based on the 'http.session.timeout' property

- web/projects/portal/src/app/vsobjects/objects/data-tip/vs-data-tip.directive.ts
make data tip assembly above the pop up assembly.
> fix Bug #71492,  make data tip assembly above the pop up assembly..

- web/projects/portal/src/app/portal/app.component.ts
Only show the 'Create Visualization' wizard the first time the route navigates to '/portal/tab/report'.
> fix Bug #71589. Fix the display issue of the 'Create Visualization' wizard.

- core/src/main/java/inetsoft/util/log/LogManager.java
Iterate through matching nodes only to prevent countdown causing timeout
> Bug #71633

- core/src/main/java/inetsoft/sree/RepletEngine.java
- core/src/main/java/inetsoft/sree/security/PermissionChecker.java
- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleController.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
- core/src/main/java/inetsoft/web/admin/schedule/model/ScheduleTaskNamesModel.java
- core/src/main/java/inetsoft/web/admin/schedule/model/TaskConditionPaneModel.java
- core/src/main/java/inetsoft/web/portal/controller/ScheduleController.java
- web/projects/em/src/app/app.module.ts
- web/projects/em/src/app/settings/schedule/schedule-task-editor-page/schedule-task-editor-page.component.ts
- web/projects/em/src/app/settings/schedule/task-condition-pane/completion-condition-editor/completion-condition-editor.component.html
- web/projects/em/src/app/settings/schedule/task-condition-pane/completion-condition-editor/completion-condition-editor.component.spec.ts
- web/projects/em/src/app/settings/schedule/task-condition-pane/completion-condition-editor/completion-condition-editor.component.ts
- web/projects/em/src/app/settings/schedule/task-condition-pane/task-condition-pane.component.html
- web/projects/portal/src/app/portal/portal-app.module.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.component.html
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.component.scss
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.component.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/conditions/task-condition-pane.spec.ts
- web/projects/portal/src/app/portal/schedule/schedule-task-editor/schedule-task-editor.component.ts
- web/projects/shared/schedule/model/schedule-task-names-model.ts
- web/projects/shared/schedule/schedule-task-names.service.ts
Optimize the permission checking. Check for the owner first and then at each stage return immediately if the condition is true.
Retrieve the schedule tasks for completion condition in the background.
> Merge forward Bug #71661 - portal schedule page optimization

- core/src/main/java/inetsoft/sree/PropertiesEngine.java
- core/src/main/java/inetsoft/sree/UserEnv.java
- core/src/main/java/inetsoft/util/script/ContextJavaPackage.java
- core/src/main/java/inetsoft/util/script/JavaScriptEngine.java
- core/src/main/java/inetsoft/util/script/SecureClassShutter.java
- core/src/main/resources/inetsoft/util/srinter.properties
Bug #71561, support use stream object in the javascript.
Bug #71573, allow java primitive Array
Bug #71568,
add some inetsoft package and class are supported in script to the white list.
other changes:
1. Block env setter functions in js.
2. Allow env getter functions in js, it should be ok since administrator can use permission to decide who can write script.
> fix related issues of bug #71424:

- core/src/main/java/inetsoft/web/viewsheet/controller/dialog/ScheduleDialogController.java
Prohibit modifying the enabled state of the button via F12 debugging to trigger the click method.
> Fix Bug #71607:Prevent F12 from modifying button properties to interfere with subsequent operations.

- core/src/main/java/inetsoft/web/admin/schedule/EMScheduleTaskController.java
Implement backend enforcement to block browser debug tools (F12) from overriding disabled button states and executing click handlers.
> Fix Bug #71611:Prevent F12 from modifying button properties to interfere with subsequent operations.

- core/src/main/java/inetsoft/web/viewsheet/service/VSExportService.java
fix Bug #71693, filter bookmark by permission before export vs by api.
fix Bug #71711: the bug is caused by Bug #71693, it only check bookmark name to compare will be wrong, if other user's bookmark it will be show bookmark with user name, so we should get right display name for bookmark to match with select bookmark to filter
> fix Bug #71693 and fix Bug #71711: filter bookmarks

- core/src/main/java/inetsoft/web/composer/vs/objects/controller/VSObjectPropertyService.java
when group have embed as child, do no support it as data tip view and fly over component
> fix Bug #71653: group with embed vs should not as data tip view

- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
fix Bug #71616, do not show copy link dialog when user do not have permission for vs.
fix Bug #71623. For embedded viewers, if there is only one bookmark, the bookmark icon should not be displayed on the viewer toolbar. 
fix Bug #71650, when use angular element custom element, should call detectChanges at native listener call back and http call back.
fix Bug #71674, hide Edit button in embed viewer.
fix Bug #71710. Ensure that the view is refreshed immediately after the context menu is created.
fix Bug #71708. The purpose of the `ResizeSensor` in this code is to address the issue where the page cannot be opened by Studio (i.e. when the report links to the viewsheet). However, after checking previous versions, I found that this issue already existed. Therefore, when embedding the viewsheet …
> fix Bug #71616, Bug #71623, Bug #71650, Bug #71674, Bug #71710, Bug #71708. Merge changes.

- core/src/main/java/inetsoft/web/portal/data/DataSetService.java
- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java
- web/projects/portal/src/app/portal/data/data-datasource-browser/data-datasource-browser.component.html
- web/projects/portal/src/app/portal/data/data-datasource-browser/data-datasource-browser.component.ts
fix Bug #71557:
for new query action should use querable permission is ok, it will check read permission for datasource and physical table permission for normal datasource and for tabular source only check its db permission, so we should not add physical table permissi
fix Bug [#71583]
should using last index of to find last layer vs and to remove it from last vs.
fix Bug #71565：
should not check write permission for user scope folder, we can create user scope folder directly, the same as composer
> Bug 71583 and fix Bug #71557 and fix Bug #71565

- core/src/main/java/inetsoft/web/portal/controller/ScheduleTaskController.java
Restrict F12-devtool modifications to button states and content via permission checks.
> Fix Bug #71687:Prevent F12 from modifying button properties to interfere with subsequent operations.

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskService.java
Add a permission check for InternalTask, as InternalTask can independently verify permissions in EM, so a write permission check is required for InternalTask.
> Fix Bug #71712:Add a permission check for InternalTask

- core/src/main/java/inetsoft/web/viewsheet/controller/ComposerController.java
- core/src/main/resources/inetsoft/util/srinter.properties
- web/projects/em/src/app/common/util/datepicker/datepicker.component.ts
- web/projects/em/src/app/settings/schedule/schedule-task-editor-page/schedule-task-editor-page.component.html
- web/projects/portal/src/app/portal/data/data-folder-browser/data-folder-list-view/data-folder-list-view.component.html
- web/projects/portal/src/app/portal/data/model/worksheet-browser-info.ts
- web/projects/portal/src/app/portal/data/move-asset-dialog/move-asset-dialog.component.ts
- web/projects/portal/src/app/vsobjects/action/chart-actions.ts
If no worksheet permission, only can not edit worksheet but can rename and move, rename and move only check asset permission, but edit ws should open composer so should have worksheet permission in composer
fix Bug#71599
1 rollback changes of Bug [#47014], should check valid and task changed to decide check save button enable or not. old bug is fixed by others, should not emit value change when save condition.
2 when save run once condition, it will caused model change to init date value to caused task changed to true. When init date value should not emit form change event to caused task changed to true
fix Bug [#71598]
should support filter when chart in max mode the same as Bug [#71590]
> fix Bug #71622, fix Bug#71599,fix Bug #71598

- core/src/main/resources/inetsoft/util/srinter.properties
> add localization.

- core/src/main/java/inetsoft/report/composition/execution/SQLBoundQuery.java
Modify the log name setting of the query. If it is private, it remains as userName + "/" + ws.path + "." + queryName.
> Fix Bug #71472:Modify the log name.

- connectors/inetsoft-serverfile/src/main/java/inetsoft/uql/serverfile/ServerFileRuntime.java
- core/src/main/java/inetsoft/report/composition/execution/AssetDataCache.java
- core/src/main/java/inetsoft/report/composition/execution/ViewsheetSandbox.java
- core/src/main/java/inetsoft/uql/XTableNode.java
- core/src/main/java/inetsoft/uql/util/CompositeTableNode.java
- core/src/main/java/inetsoft/uql/util/XNodeTable.java
do not use cache data, when data is canceled.
> fix Bug #71321, do not use cache data, when data is canceled.

- web/projects/portal/src/app/composer/gui/vs/composer-object.service.ts
- web/projects/portal/src/app/composer/gui/vs/editor/editable-object-container.component.html
- web/projects/portal/src/app/composer/gui/vs/editor/editable-object-container.component.ts
- web/projects/portal/src/app/embed/chart/embed-chart.component.ts
- web/projects/portal/src/app/embed/chart/embed-chart.module.ts
- web/projects/portal/src/app/vsobjects/objects/spinner/vs-spinner.component.html
- web/projects/portal/src/app/vsobjects/objects/spinner/vs-spinner.component.ts
- web/projects/portal/src/app/vsobjects/objects/vs-object-container.component.ts
fix Bug #71639, show minitoolbar for adhocfilter.
fix Bug #71673, show adhocfilter.
fix Bug #71648, use VSDataTip and VSPopComponent directive for spinner label to make sure pop directive can set styles for right html element.
fix Bug #71691, add AdhocFilterService for embed chart.
fix Bug #71707, adhoc filter should not make other component as convered component.
> fix some bugs by merging

- core/src/test/java/inetsoft/mv/formula/CompositeAverageFormulaTest.java
- core/src/test/java/inetsoft/mv/formula/CompositeCorrelationFormulaTest.java
- core/src/test/java/inetsoft/mv/formula/CompositeCovarianceFormulaTest.java
- core/src/test/java/inetsoft/mv/formula/CompositeVarianceFormulaTest.java
add unit case for some formula class
> add unit case for formula

- core/src/main/java/inetsoft/uql/util/ColumnCache.java
merge from 13_7,Bug #71533, format date part.
> Fix Bug #71751: format date part.

- core/src/main/java/inetsoft/sree/schedule/ScheduleParameterScope.java
change get current, last, next quarter method logic of schedule parameter to make sure it works well.
> fix Bug #71783, change get current, last, next quarter method logic of schedule parameter to make sure it works well.

- core/src/main/java/inetsoft/mv/formula/NthMostFrequentFormula.java
> Bug #71764, fix recurses infinitely.

- core/src/main/java/inetsoft/mv/formula/NthMostFrequentFormula.java
fix clone obj error to ensure subclass can return correct type clone obj.
> fix Bug #71786, fix clone obj error to ensure subclass can return correct type clone obj.

- web/projects/portal/src/app/vsobjects/objects/chart/vs-chart.component.html
Constrain ZIndex of chart title in composer to prevent displaying over other components
> merge Bug #71776

- bom/pom.xml
Update commons-io to 2.18.0 to match poi 5.4.0.
> fix Bug #71810, Update commons-io to 2.18.0 to match poi 5.4.0.

- core/src/main/java/inetsoft/report/composition/execution/InputVSAQuery.java
- web/projects/portal/src/app/vsobjects/dialog/combo-box-editor.component.html
- web/projects/portal/src/app/vsobjects/dialog/combo-box-editor.component.ts
- web/projects/portal/src/app/vsobjects/objects/combo-box/vs-combo-box.component.html
1. reduce nested loops.
2. use cdk-virtual-scroll-viewport in combo-box-editor when values num larger than 500.
> fix Bug #71768, fix performance issue.

- core/src/main/java/inetsoft/util/SparseMatrix.java
do not allow multi thread to set value for SparseMatrix.ObjectList at same time.
> fix Bug #71518, do not allow multi thread to set value for SparseMatrix.ObjectList at same time.

- core/src/main/java/inetsoft/report/composition/graph/GraphGenerator.java
before crete graph, update the sort others last of the runtime chart descriptor.
> fix Bug #71843, before crete graph, update the sort others last of the runtime chart descriptor.

- core/src/main/resources/inetsoft/web/resources/js/login.js
do not call multi authenticate when user click enter key for login page. key keypress listerner has been add to document.
> fix Bug #71842, do not call multi authenticate when user click enter key for login page.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/datasources-database.component.ts
> Fix Bug #71858:Fix special characters appearing in the prompt message.

- core/src/main/java/inetsoft/uql/asset/SQLBoundTableAssembly.java
clone the query before get query parameters to avoid deadlock.
> fix Bug #71883, clone the query before get query parameters to avoid deadlock.

- core/src/main/java/inetsoft/web/composer/ws/SaveWorksheetController.java
ignore disposed runtime ws save request.
> fix Bug #71841, ignore disposed runtime ws save request.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/driver-wizard/driver-wizard.component.ts
Add the necessary parameter uploadType for frontend-backend transmission.
> Fix Bug #71887:Add the necessary parameter uploadType for frontend-backend transmission.

- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
after rename global role, keep the others user members for new role.
> fix Bug #71911, after rename global role, keep the others user members for new role.

- core/src/main/java/inetsoft/report/internal/RuntimeAssetEngine.java
- core/src/main/java/inetsoft/uql/asset/AbstractAssetEngine.java
- core/src/main/java/inetsoft/uql/asset/AssetRepository.java
- core/src/main/java/inetsoft/web/admin/properties/PropertiesController.java
- core/src/main/java/inetsoft/web/composer/model/TreeNodeModel.java
- core/src/main/java/inetsoft/web/portal/controller/RepositoryTreeController.java
- web/projects/portal/src/app/widget/repository-tree/repository-tree.component.ts
- web/projects/portal/src/app/widget/tree/tree-node-model.ts
Force refresh repository tree on toggle globally visible default org assets, properly remove global folder when toggle false
> Bug #71856

- core/src/main/java/inetsoft/web/GlobalStyleController.java
get organzation from security engine and check null for it.
> Bug #71956: get organzation from security engine and check null for it.

- core/src/main/java/inetsoft/util/migrate/MigrateDocumentTask.java
should use organization id compare to organization id, not object.
> Bug #71947: should not compare id to object.

- core/src/main/java/inetsoft/mv/MVChangedMessage.java
- core/src/main/java/inetsoft/mv/MVManager.java
- core/src/main/java/inetsoft/web/admin/content/repository/MVChangeController.java
send MVChangedMessage to all nodes of the cluster when mv changed, to refresh the cycle tasks.
> fix Bug #71967, send MVChangedMessage to all nodes of the cluster when mv changed, to refresh the cycle tasks.

- core/src/main/java/inetsoft/web/admin/security/user/SecurityTreeServer.java
- web/projects/em/src/app/settings/security/users/users-settings-page/users-settings-page.component.ts
same with others place, throw InvalidOrgException if org do not exist during loading user tree.
> fix Bug #71973, same with others place, throw InvalidOrgException if org do not exist during loading user tree.

- core/src/main/java/inetsoft/sree/schedule/ScheduleTask.java
should show the user info in email,like admin:Task4
> Fix Bug #71945:Should show the user info in email,like admin:Task4

- web/projects/portal/src/app/vsobjects/objects/data-tip/pop-component.service.ts
- web/projects/portal/src/app/vsobjects/objects/output/image/vs-image.component.ts
- web/projects/portal/src/app/vsobjects/objects/output/text/vs-text.component.ts
- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
Don't send data/open to reexecute assembly after popComponent is set onClick to prevent removing already processed assemblies
> Bug #71907

- core/src/main/java/inetsoft/uql/jdbc/JDBCHandler.java
- core/src/main/java/inetsoft/uql/service/XEngine.java
fix java.lang.IllegalMonitorStateException: current thread is not owner.
> fix java.lang.IllegalMonitorStateException: current thread is not owner.

- core/src/main/java/inetsoft/web/composer/vs/objects/controller/VSObjectPropertyService.java
In this condition, if all satisfied cases return false, then the unsatisfied cases should return true.
> Fix Bug #72008:In this condition, if all satisfied cases return false, then the unsatisfied cases should return true.

- core/src/main/java/inetsoft/sree/internal/SUtil.java
- core/src/main/java/inetsoft/sree/security/UserProvider.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleService.java
- core/src/main/java/inetsoft/web/admin/schedule/ScheduleUsersChangeService.java
- core/src/main/java/inetsoft/web/admin/schedule/model/UsersModel.java
- core/src/main/java/inetsoft/web/admin/security/SSOSettingsService.java
- core/src/main/java/inetsoft/web/admin/security/SSOTypeChangedMessage.java
- web/projects/em/src/app/settings/schedule/task-options-pane/task-options-pane.component.ts
- web/projects/shared/schedule/schedule-users.service.ts
1, make owner option always enable when env config sso.
2, add getUsers method to the UserProvider to make can get all sso user by it.
> fix Bug #72019, change task owner setting logic for sso.

- core/src/main/java/inetsoft/web/binding/VSChartBindingController.java
- web/projects/portal/src/app/binding/editor/chart/aesthetic/aesthetic-pane.component.html
- web/projects/portal/src/app/binding/editor/chart/aesthetic/static-shape-pane.component.ts
just load host org shapes when org user edit global share vs at viewer.
> fix Bug #72034, just load host org shapes when org user edit global share vs at viewer.

- core/src/main/java/inetsoft/web/security/AbstractSecurityFilter.java
config sso and enable "Allow Default Form Login". during logging out, if current user is sso user, should make sso filter to log out.
> fix Bug #72038,  fix SAML sso user can not logout.

- core/src/main/java/inetsoft/web/admin/security/user/UserTreeService.java
should use theme id to compare to find theme.
> Bug #72006: should use it to find theme 

- core/src/main/java/inetsoft/web/GlobalStyleController.java
when no theme on organzation, should use default theme
> Bug #72006: when no organzation theme, should use default theme for portal

- core/src/main/java/inetsoft/web/viewsheet/controller/VSCheckFormDataController.java
do not process checkTables for runtime worksheet.
> fix Bug #72063, do not process checkTables for runtime worksheet.

- web/projects/portal/src/app/vsobjects/bookmark/vs-bookmark-pane.component.html
- web/projects/portal/src/app/vsobjects/viewer-app.component.html
- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
should not trigger goto bookmark when user click delete bookmark.
> fix Bug #72047,should not trigger goto bookmark when user click delete bookmark.

- core/src/main/java/inetsoft/web/vswizard/handler/VSWizardObjectHandler.java
remove it from container when wizard remove the original assembly.
> fix Bug #72098, remove it from container when wizard remove the original assembly.

- core/src/main/java/inetsoft/mv/MVManager.java
- core/src/main/java/inetsoft/mv/MVTool.java
- core/src/main/java/inetsoft/sree/RepletRegistry.java
- core/src/main/java/inetsoft/sree/internal/DataCycleManager.java
- core/src/main/java/inetsoft/web/admin/content/repository/MVChangeController.java
when mv changed, generate changed source org cycle tasks.
> fix Bug #72049, when mv changed, generate changed source org cycle tasks.

- core/src/main/java/inetsoft/util/BlobIndexedStorage.java
remove old user assets after migrate to others user.
> fix Bug #72125, remove old user assets after migrate to others user.

- core/src/main/java/inetsoft/web/admin/AdminPageController.java
the bug is caused by two issues(1) when set organization theme, admin should set customTheme to true. (2) when orgnization theme set EMDark to true, should set darkTheme to true to apply dark em.
> Bug #72122: apply organization theme for em

- connectors/inetsoft-onedrive/src/main/java/inetsoft/uql/onedrive/OneDriveDataSource.java
- connectors/inetsoft-rest/src/main/java/inetsoft/uql/rest/AbstractRestDataSource.java
- core/src/main/java/inetsoft/util/AbstractPasswordEncryption.java
Add warning when refresh token fails to decrypt when reading datasource
> Bug #72121

- core/src/main/java/inetsoft/uql/jdbc/JDBCHandler.java
When the "Table Name" option in the ClickHouse data source is set to "Table", it means that only tables will be available as tree nodes under the Datasource. In this case, if a default database is specified in the Datasource's connection URL, then only the tables under that database should be retrieved. If no default database is specified, the first non-system database should be used as the default catalog to retrieve tables.
> fix Bug #72119. For ClickHouse, when "Table Name" option is set to "Table", use a default catalog to get tables.

- core/src/main/java/inetsoft/report/composition/execution/CubeQuery.java
Narrow the scope of the synchronized block's impact.
> code review. Narrow the scope of the synchronized block's impact.

- core/src/main/java/inetsoft/web/viewsheet/service/VSBookmarkService.java
the bug is caused by home and bookmark with differnent values for range slider, so it will refresh range slider to new list and its state list will be cleared. In fact, we should re-set rangeslider's state list after bookmark vs is loaded.
> fix Bug #72119: refresh range slider after bookmark is loaded.

- core/src/main/java/inetsoft/web/admin/content/repository/DatabaseDatasourcesService.java
should not save Util.PLACEHOLDER_PASSWORD as password. Only save password when change it to others.
> fix Bug #72136: should not save “******” as password

- core/src/main/java/inetsoft/web/composer/ws/dialog/AssemblyConditionDialogController.java
- web/projects/portal/src/app/widget/condition/date-in-value-editor.component.html
- web/projects/portal/src/app/widget/condition/date-in-value-editor.component.ts
> Bug 72064: Add localization.

- core/src/main/java/inetsoft/web/admin/content/repository/DatabaseDatasourcesService.java
for addional db, should get its db by base path and its name as db path
is password is ******, should not set to db. for some cases db will not get from server(such as first time edit db which is not saved)
> fix Bug #72136: fix additional db password issue

- core/src/main/java/inetsoft/web/portal/controller/database/QueryManagerService.java
add catalog and schema relation properties to table entry for the runtime query.
> fix Bug #72137, add catalog and schema relation properties to table entry for the runtime query.

- core/src/main/java/inetsoft/util/log/LogManager.java
- core/src/main/java/inetsoft/web/admin/logviewer/LogMonitoringController.java
- core/src/main/java/inetsoft/web/admin/logviewer/LogMonitoringService.java
- web/projects/em/src/app/monitoring/log/log-monitoring-page/log-monitoring-page.component.ts
down load selected clustor node log when click em download log button.
> fix Bug #72163,  down load selected clustor node log when click em download log button.

- core/src/main/java/inetsoft/web/portal/controller/database/QueryGraphModelService.java
rollback some changes to fix "default" for db, fixed by Bug #72188
> fix Bug #72103: rollback some changes to fix "default" for db, fixed by Bug #72188

- core/src/main/java/inetsoft/report/gui/viewsheet/ImageManager.java
- core/src/main/java/inetsoft/report/gui/viewsheet/VSImage.java
- core/src/main/java/inetsoft/report/io/viewsheet/html/HTMLVSExporter.java
- core/src/main/java/inetsoft/report/io/viewsheet/pdf/PDFVSExporter.java
- core/src/main/java/inetsoft/report/io/viewsheet/svg/SVGVSExporter.java
- core/src/main/java/inetsoft/uql/viewsheet/internal/VSUtil.java
- core/src/main/java/inetsoft/uql/viewsheet/internal/VsToReportConverter.java
- core/src/main/java/inetsoft/util/ImageHashService.java
- core/src/main/java/inetsoft/util/graphics/SVGSupport.java
- core/src/main/java/inetsoft/web/viewsheet/controller/AssemblyImageService.java
- utils/inetsoft-xml-formats/src/main/java/inetsoft/report/io/viewsheet/excel/PoiExcelVSExporter.java
- utils/inetsoft-xml-formats/src/main/java/inetsoft/report/io/viewsheet/ppt/PPTVSExporter.java
- utils/inetsoft-xml-formats/src/main/java/inetsoft/util/graphics/BatikSVGSupport.java
[Bug #71924](https://github.com/inetsoft-technology/stylebi/commit/afb30b81872a6feb029a1d545cc9caef68e80f3d)
- Handle alignment issues with images generated on the server side such as when shadow is enabled.
- Add more properties to image info so that the image is regenerated once the property is changed.
- For dynamic image always send the response back as a png.
[Bug #72142](https://github.com/inetsoft-technology/stylebi/commit/a59e95fb34700860efcb268db9714d4afa1b47e8)
- Handle drawing a shadow when background is set. Don't fill with background color on the image where shadow will be applied.
- Size the svg correctly when rendered on the server to match the browser.
[Bug #72159](https://github.com/inetsoft-technology/stylebi/commit/2a5d806b35690792f3f2fee6f249183c89a95c54)
- Fix svg …
> Fix image display issues related to Bug #71924 changes

- core/src/main/java/inetsoft/web/viewsheet/service/CoreLifecycleService.java
- web/projects/portal/src/app/embed/viewer/embed-viewer.component.ts
- web/projects/portal/src/app/vsobjects/show-hyperlink.service.ts
- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
[Bug #72158](https://github.com/inetsoft-technology/stylebi/commit/922c370f4244d021ff3ac7b7ffc8a7cbd0263bb6)
Allow non _self target frames in hyperlinks in web components
[Bug #72157](https://github.com/inetsoft-technology/stylebi/commit/780f41f3da2da91c3abd703218f5d5c3817fb504)
Add an option to the viewer web component to enable scale to screen
[Bug #72172](https://github.com/inetsoft-technology/stylebi/commit/0d19bf1e80359287033ad3e261149ccdfbb7de33)
Fix watermark image url in a web component
> Viewer web component fixes

- core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCache.java
- core/src/main/java/inetsoft/sree/security/db/RefreshCacheTask.java
fix NPE. return empty array when database provider load identities failed.
> fix Bug #72208, fix NPE. return empty array when database provider load identities failed.

- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
Make the viewer toolbar stay on top in viewer web component on mobile
> Bug #71895 - fix viewer toolbar position on mobile

- core/src/main/java/inetsoft/web/composer/AssetTreeRefreshController.java
Only propagate asset change if global or current Organization to prevent extraneous refresh of other organizations
> Bug #72210

- core/src/main/java/inetsoft/sree/internal/DataCycleManager.java
- core/src/main/java/inetsoft/sree/schedule/ScheduleManager.java
when init DataCycleManager should reload all org cycle tasks.
> fix Bug #72226, when init DataCycleManager should reload all org cycle tasks.

- core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCacheServiceImp.java
Reverts inetsoft-technology/stylebi#1897
> Revert "fix Bug #72234, reset counters when cancel service."

- core/src/main/java/inetsoft/sree/security/db/DatabaseAuthenticationCache.java
avoid close cache during initializing it.
> fix Bug #72233, avoid close cache during initializing it.

- core/src/main/java/inetsoft/web/admin/user/TopUsersMonitoringTableModel.java
for top user, when org do not exist, show orgId.
> fix Bug #72239, for top user, when org do not exist, show orgId.

- core/src/main/java/inetsoft/uql/jdbc/drivers/DriverScanner.java
close URLClassLoader after scan driver in the jar.
> close URLClassLoader after scan driver in the jar.

- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
Make sure the viewer toolbar stays on top. Handle different cases such as when parent div or body is scrollable. Handle pinch zoom.
> Bug #71895 - make mobile toolbar stay on top inside the web component

- web/projects/portal/src/app/vsobjects/viewer-app.component.ts
Fix the export url inside the web component
> Bug #72248 - fix export url

- core/src/main/java/inetsoft/util/config/CosmosDBConfig.java
for aks, get cosmosdb accountHost, accountKey, blob connectionString from secret.
> for aks, get cosmosdb accountHost from secret.

- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/datasources-database.component.html
- web/projects/portal/src/app/portal/data/data-datasource-browser/datasources-database/datasources-database.component.ts
when set custom url for db, should trim its spaces before it or after it.
> fix Bug #72276: should trim custom url for db

- core/src/main/java/inetsoft/report/composition/execution/AbstractSelectionVSAQuery.java
- core/src/main/java/inetsoft/uql/viewsheet/SelectionListVSAssembly.java
- core/src/main/java/inetsoft/uql/viewsheet/SelectionTreeVSAssembly.java
Reverts inetsoft-technology/stylebi#1823 after discuss, it is not a bug for the databricks, it is because dbveaver will show diifferent accuracies with our product，so should rollback all changes on it
> Revert "fix Bug #72100, use date format with millis if millis in format is required."

- core/src/main/java/inetsoft/web/viewsheet/controller/VSCalendarService.java
- core/src/main/java/inetsoft/web/viewsheet/event/calendar/CalendarSelectionEvent.java
- core/src/main/java/inetsoft/web/viewsheet/event/calendar/ToggleDoubleCalendarEvent.java
- core/src/main/java/inetsoft/web/viewsheet/event/calendar/ToggleRangeComparisonEvent.java
- core/src/main/java/inetsoft/web/viewsheet/event/calendar/ToggleYearViewEvent.java
support deserialize and serialize for CalendarSelectionEvent to make  Calendar toggle can work well.
> fix Bug #72370,  fix calendar toggle error.

- core/src/main/java/inetsoft/web/composer/vs/controller/ExportController.java
keep old logic, should not close the vs after export the runtime viewsheet.
> fix Bug #72359, fix runtime vs expired after export.

- core/src/main/java/inetsoft/web/viewsheet/event/RefreshVSAssemblyEvent.java
support serialize and deserialize for RefreshVSAssemblyEvent.
> fix Bug #72286, support serialize and deserialize for RefreshVSAssemblyEvent.

- core/src/main/resources/inetsoft/util/srinter.properties
add localize for task condition label
> fix Bug #72348: add localize for label

- core/src/main/java/inetsoft/uql/viewsheet/internal/CalendarVSAssemblyInfo.java
- docker/src/main/docker/files/bin/start-server.sh
1, CalendarVSAssemblyInfo and VSAssemblyInfo have same name field "pixelsize", it causes ignite serialize error, so change  it name in the CalendarVSAssemblyInfo. 2, add open for java.time.chrono so that Point can be serialized
> fix Bug #72370,

- core/src/main/java/inetsoft/web/admin/schedule/model/ServerPathInfoModel.java
when no password for task, should not show "******" for user, only show it when has passowrd.
> fix Bug #72260: should not show ****** when task do not have password

- core/src/main/java/inetsoft/web/portal/controller/database/QueryGraphModelService.java
should save runtime query when add join to query
> fix Bug #72367: should save runtime query when add join to query

- core/src/main/java/inetsoft/web/viewsheet/controller/PresenterController.java
should write image data when not empty
> fix Bug #72371: should write image data when not empty

- core/src/main/java/inetsoft/sree/internal/cluster/ignite/IgniteCluster.java
> Revert "fix Bug #72363, check if client or schedule server and make the call …"

- core/src/main/java/inetsoft/web/admin/schedule/ScheduleTaskActionService.java
The folders should be placed at the front when obtaining the tree of the viewsheet.
> Fix Bug #72394:The folders should be placed at the front when obtaining the tree of the viewsheet.

- core/src/main/java/inetsoft/web/viewsheet/model/dialog/ExportDialogModel.java
should implement Serializable for model
> fix Bug #72410: should implement Serializable for model

- web/projects/em/src/app/settings/schedule/schedule-folder-tree/schedule-folder-tree.component.ts
Since triggering two refreshes during edit, move, new, and delete operations causes the records of expanded nodes to be cleared, thus preventing the node state from being preserved, the solution is to avoid invoking the refresh logic of scheduleChangeService.onFolderChange specifically during edit, move, new, and delete operations, while ensuring it remains effective in all other scenarios.
> Fix Bug #72399:Prevent Duplicate Refresh on CRUD Operations.

- core/src/main/java/inetsoft/util/cachefs/CacheMetadata.java
fix CacheMetadata Deserialized error.
> Bug #72430, fix CacheMetadata Deserialized error.

- core/src/main/java/inetsoft/report/LibManager.java
user correct storeID when reload Lib assets.
> fix Bug #72397, user correct storeID when reload Lib assets.

- core/src/main/java/inetsoft/web/viewsheet/command/LoadPreviewTableCommand.java
- core/src/main/java/inetsoft/web/viewsheet/command/LoadTableDataCommand.java
- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartShowDataService.java
- core/src/main/java/inetsoft/web/viewsheet/controller/chart/VSChartShowDetailsService.java
- core/src/main/java/inetsoft/web/viewsheet/controller/table/BaseTableService.java
- core/src/main/java/inetsoft/web/viewsheet/controller/table/BaseTableShowDetailsService.java
serialize the prototypeCache of LoadTableDataCommand, because it will send between the server node.
> fix Bug #72464, serialize the prototypeCache of LoadTableDataCommand, because it will send between the server node.

- core/src/main/resources/inetsoft/util/srinter.properties
Update the comments in the srinter.properties file, let AI to translate accurately and correctly.
> Update the comments in the srinter.properties file.

- core/src/main/java/inetsoft/report/composition/WorksheetEngine.java
should set current user to ThreadContext so it can get right principal to check permission for chart type and chart shape...
Bug #72422 is fixed by this.
> fix Bug #72450:

- core/src/main/java/inetsoft/sree/internal/SUtil.java
- core/src/main/java/inetsoft/web/messaging/SessionConnectionService.java
- core/src/main/java/inetsoft/web/session/IgniteSessionRepository.java
- core/src/main/java/inetsoft/web/session/PrincipalChangedEvent.java
if em principal is changed just update the principal of the em websocket, app principal is changed just update the principal of the app websocket.
> Bug #72509,  fix em users monitor show others org user.

- core/src/main/java/inetsoft/report/composition/execution/DistributedTableCacheStore.java
Reduce DistributedTableCacheStore key length
> Bug #72575 - Reduce DistributedTableCacheStore key length

- core/src/main/java/inetsoft/report/composition/RuntimeSheetCache.java
- core/src/main/java/inetsoft/report/composition/WorksheetEngine.java
sync to save the new runtime viewsheet to cluster cache to ensure others node can get it.
> fix Bug #72518, fix can not get runtime viewsheet during create new vs.

- core/src/main/java/inetsoft/sree/internal/DataCycleManager.java
get correct org ids during generate the cycle tasks.
> fix Bug #72566, fix can not create cycle tasks when security is false.

- core/src/main/java/inetsoft/web/composer/AssetTreeRefreshController.java
ensure tree can refresh correctly, listen all lib assets change event to refresh the tree, when node1 changed assets, nodes just reload them and fire reload event.
> Bug #72523,  fix asset tree can not refresh when reanme  a table style.

- core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java
- core/src/main/java/inetsoft/report/composition/RuntimeViewsheetState.java
write OriginalId to RuntimeViewsheetState to make sure finishing binding can work well.
> Bug #72576, fix binding changed can not save after finish binding pane.

- core/src/main/java/inetsoft/web/messaging/SessionConnectionService.java
- core/src/main/java/inetsoft/web/service/SessionExpirationController.java
- core/src/main/java/inetsoft/web/session/IgniteSessionRepository.java
- core/src/main/java/inetsoft/web/session/PrincipalChangedEvent.java
- core/src/main/java/inetsoft/web/session/SessionCreatedEvent.java
- core/src/main/java/inetsoft/web/session/SessionDeletedEvent.java
- core/src/main/java/inetsoft/web/session/SessionEvent.java
- core/src/main/java/inetsoft/web/session/SessionExpiredEvent.java
use cluster message insteadof application context event to make sure session event can be handled in cluster.
> fix Bug #72569, use cluster message insteadof application context event

- web/projects/shared/ai-assistant/ai-assistant.service.ts
Other changes in index.ts and chatService.ts ，Since Hunter is also modifying these files, to avoid conflicts, he will submit these two files.
> add crosstab context by june

- core/src/main/java/inetsoft/sree/portal/CustomThemesImpl.java
- core/src/main/java/inetsoft/sree/portal/CustomThemesManager.java
- core/src/main/java/inetsoft/sree/security/AbstractEditableAuthenticationProvider.java
- core/src/main/java/inetsoft/web/admin/security/IdentityService.java
- core/src/main/java/inetsoft/web/admin/security/user/IdentityThemeService.java
Restructure CustomThemesImpl customThemes to KeyValueStorage to function properly in clustered environment
> Bug #72304

- core/src/main/java/inetsoft/sree/schedule/CompletionCondition.java
- core/src/main/java/inetsoft/storage/AbstractStorageTransfer.java
- core/src/main/java/inetsoft/storage/ExportStorageTask.java
Fix backup/restore when a blob file is missing.
> Bug 72565 - merge forward backup/restore fixes

- core/src/main/java/inetsoft/report/composition/RuntimeViewsheet.java
- core/src/main/java/inetsoft/report/composition/RuntimeViewsheetState.java
- core/src/main/java/inetsoft/report/composition/WorksheetEngine.java
- core/src/main/java/inetsoft/report/composition/WorksheetService.java
- core/src/main/java/inetsoft/util/ImageHashService.java
- core/src/main/java/inetsoft/web/composer/vs/controller/ComposerViewsheetService.java
the bug is caused by when get runtime viewsheet from RuntimeCache, it will not save and load ImageHashService, so its image will be lost. Should save image and load it from runtime viewsheet.
> Bug #72633: Should save image and load it from runtime viewsheet.

- core/src/main/java/inetsoft/report/composition/execution/PreAssetQuery.java
- core/src/main/java/inetsoft/uql/asset/SubQueryValue.java
Refix Bug #55898, handle checking if column exists when entity is blank
> Merge changes for Bug #72744 - check if subquery column exists

- core/src/main/java/inetsoft/graph/visual/BarVO.java
- core/src/main/java/inetsoft/report/composition/region/DefaultArea.java
- core/src/main/java/inetsoft/web/graph/GraphBuilder.java
Convert pie sliced regions to donut sliced regions for a special donut chart which is composed of two pie charts.
> Merge forward changes for Bug #72766 - handle special donut chart
